### ISSUE TITLE
APC 2016

### ISSUE THREAD

**Issue by k-okada** [start-jsk/jsk_apc#1011]
https://github.com/start-jsk/2015-semi/issues/44

@pazeshun
@kimhc6028
@knorth55
@ban-masa

**Comment by k-okada** [comment]
- https://github.com/start-jsk/jsk_apc/pull/999 をベースに２０１６年度版の環境を作る
- ２０１６年度版のjsonを作るプログラムを作る　（ 2015年度版は -> ? https://github.com/start-jsk/jsk_apc/blob/b25455c30501bc5914e0cbd1b9a9b3aa33f86b00/jsk_2015_05_baxter_apc/node_scripts/interface_generator.py　）
- json から gazeboができるとよい。eusの環境は出きると思う。
- 動作レベル飲みでのテストプログラム https://github.com/start-jsk/jsk_apc/blob/b25455c30501bc5914e0cbd1b9a9b3aa33f86b00/jsk_2015_05_baxter_apc/euslisp/main.l
- gazebo で試す
- 実機で試す

**Comment by k-okada** [comment]
- グリッパーどうするか
- tote から objectを stowする
- bin の奥にあるものをとる。　(gripper + vacuum)? 両手を使う？

**Comment by kimhc6028** [comment]
1.シミュレーションの動画（@knorth55)
2.実機の動画@kimhc6028)
3.グリッパーをどうするか(@pazeshun,@ban-masa)
4.画像処理(＠みんな)
5.Motion Planning(@みんな)

**Comment by kimhc6028** [comment]
グリッパーの問題：
１．棚に入るのか？
２．本が取れない。
３．袋などはやぶれてしまう。
 4. どうしても吸引は必要でしょう。

**Comment by pazeshun** [comment]
胸の部分にテーブルをつけておき、違うものをとったらその上にものを置く。
目当てのものが見つかったら戻す

**Comment by kimhc6028** [comment]
SAKE Roboticsがグリッパーを貸してくれるらしいです。

    SAKE Robotics wants to partner with you in the Amazon Picking Challenge by lending you an EZGripper Robotic Gripper so you have a better chance to win the challenge!

    Why would we do that? 

    1) We believe the SAKE Robotics EZGripper can help you win the competition.  The EZGripper picks things up very easily and reliably.  See the attached brochure.

    2) We want your feedback on how to improve our products or apply them in new ways

    3) We hope Amazon sees our SAKE Robotics EZGripper improving the success of our partners and they'll buy some for their warehouses :^)
    Even if you have already chosen an alternative gripper, give ours a try.    
    Contact us for your EZGripper robotic grippers at APC@SAKErobotics.com

    Sincerely,

    Paul Ekas

    President

    Notes:

    - The EZGripper robotic gripper will be on loan to the teams competing in the APC until August 15, 2016.

    - The teams will need to supply the related Robotis components: 1 MX-64 servo, 1 12V supply, 1 USB2Dynamixel, SMPS2Dynamixel and cables (total ~$400)

    - SAKE Robotics will repair or replace damaged EZGrippers fast (but we don't think you'll break them)

    - EZGrippers will be available Feb 15 for shipping to you

    - All videos, papers, or cool things you do with our EZGrippers are super appreciated

    Attachments area
    Preview attachment EZGripperTM Dual and Quad Robotic Grippers.pdf
    EZGripperTM Dual and Quad Robotic Grippers.pdf

SAKE Robotics: Free Robotic Grippers for APC Competition by Paul Ekas (21 Jan 2016 23:18 UTC)
Reply to list

    with attachment

    SAKE Robotics wants to partner with you in the Amazon Picking Challenge by lending you an EZGripper Robotic Gripper so you have a better chance to win the challenge!

    Why would we do that? 

    1) We believe the SAKE Robotics EZGripper can help you win the competition.  The EZGripper picks things up very easily and reliably.  See the attached brochure.

    2) We want your feedback on how to improve our products or apply them in new ways

    3) We hope Amazon sees our SAKE Robotics EZGripper improving the success of our partners and they'll buy some for their warehouses :^)
    Even if you have already chosen an alternative gripper, give ours a try.  
    Contact us for your EZGripper robotic grippers at APC@SAKErobotics.com

    Sincerely,

    Paul Ekas

    President

    Notes:

    - The EZGripper robotic gripper will be on loan to the teams competing in the APC until August 15, 2016.

    - The teams will need to supply the related Robotis components: 1 MX-64 servo, 1 12V supply, 1 USB2Dynamixel, SMPS2Dynamixel and cables (total ~$400)

    - SAKE Robotics will repair or replace damaged EZGrippers fast (but we don't think you'll break them)

    - EZGrippers will be available Feb 15 for shipping to you

    - All videos, papers, or cool things you do with our EZGrippers are super appreciated
http://archives.simplelists.com/pickingchallenge2016/cache/3334581/2.pdf

**Comment by k-okada** [comment]
http://amazonpickingchallenge.org/APC_2016_Official_Rules.pdf

**Comment by k-okada** [comment]
今週中が締め切りなのでがんばりましょう．物品追加調達できたかな？

１）@kimhc6028 できているところを　https://docs.google.com/document/d/1ftQ5g6tTUsiUjor2yGbkMSwXUUPkO4UWdaq7IYEyi6w/edit　とマージしてみて下さい．
２）@knorth55 gazebo，出来ているところをWIPでPullRequestにしてみてください

**Comment by kimhc6028** [comment]
はい。今、友達に英語を直してもらっている中ですので、今日中にマージします。

**Comment by ban-masa** [comment]
[arm.zip](https://github.com/start-jsk/jsk_apc/files/111905/arm.zip)

今日議論していた思いついたハンドの概形をeuslispでおおまかにモデリングしてみたので、それについて岡田先生のご意見を伺いたいです。このハンドの有望度はどのくらいのものでしょうか。可動部で物体を挟み、円筒部分は吸盤のつもりです。

**Comment by k-okada** [comment]
2自由度？とりあえず作ってみましょう．

--
◉ Kei Okada


2016-02-01 18:02 GMT+09:00 Bando Masahiro <notifications@github.com>:

**Comment by wkentaro** [comment]
物体認識のサンプル(oreo): http://jsk-recognition.readthedocs.org/en/latest/jsk_perception/bof_object_recognition.html
もっといいやつ: https://github.com/start-jsk/jsk_apc/blob/master/jsk_2015_05_baxter_apc/launch/include/object_recognition.launch

**Comment by knorth55** [comment]
JSONからworldファイルを作れるようにerbを変更しました #1043

**Comment by knorth55** [comment]
- Stow Movie
- Pick Movie 
とりました
https://onedrive.live.com/redir?resid=F937F3BB48BB5A3!2502&authkey=!AKfAgn-HpkLCWf0&ithint=folder%2c

**Comment by ban-masa** [comment]
@k-okada 
pick object among obstaclesというのは認識した上でやるのでしょうか。それとも決め打ちでやる感じでしょうか。
それとstowタスクのeusの動画というのは何を映せばよいでしょうか。

**Comment by k-okada** [comment]
決め打ちです．

１）決め打ちでどうさ （物体の位置は固定）
２）認識ありで動作 （物体の位置が変わる，でも物体そのものは知っている）
２）もっと認識ありで動作 （物体の位置も種類も変わる）

という風に段階的に進めていくのが良いです．

eusは作った姿勢の（キーポーズ）の画像をはるとか，それを動かした動画をはるとか．キーポーズは何点ぐらいを作ったのかな．

--
◉ Kei Okada


2016-02-04 21:16 GMT+09:00 Bando Masahiro <notifications@github.com>:

**Comment by knorth55** [comment]
@pazeshun 
- New Vaccum Gripper movie uploaded 

https://onedrive.live.com/redir?resid=F937F3BB48BB5A3!2502&authkey=!AKfAgn-HpkLCWf0&ithint=folder%2c

**Comment by knorth55** [comment]
@k-okada 一応オレオを認識してpickする動画をとって[OneDrive](https://onedrive.live.com/redir?resid=F937F3BB48BB5A3!2502&authkey=!AKfAgn-HpkLCWf0&ithint=folder%2c)にあげたのですがこれも使いますか？

**Comment by k-okada** [comment]
Pickの方は買ってきた物体が前にあるのが良いです
まずはどれぐらいの隠れまで認識できるかが知りたいです

--
◉ Kei Okada

2016/02/05 1:54、Shingo Kitagawa <notifications@github.com> のメッセージ:

**Comment by knorth55** [comment]
今日試してみたのですがまた明日オレオの前にものをかぶせてやってみます

**Comment by k-okada** [comment]
出来る／出来ないのバイナリではなくて，
どこまでだったら出来る／出来ないという境界線を調べましょう．
卒論，修論でもよく言われることです．

--
◉ Kei Okada

**Comment by kimhc6028** [comment]
@k-okada
11日に先生がエントリーを出しますか？それとも我らで誰かぎ出しますか？

**Comment by k-okada** [comment]
エントリーはもうメールしてあるので，大丈夫です．

--
◉ Kei Okada

**Comment by pazeshun** [comment]
@k-okada
新グリッパー用のサーボモータについてなのですが、とりあえずよさげなものを買ってみようと思います。
その際、領収書をもらってくればいいのでしょうか？それとも、他に何か特別な手続きが必要でしょうか？

**Comment by k-okada** [comment]
アマゾンのリンクがあればそれを送ってくれるのが一番助かります。
なければ、Webショップのリンクでもいいです。
--
◉ Kei Okada


2016-02-15 22:38 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by pazeshun** [comment]
http://akizukidenshi.com/catalog/g/gM-01911/
とりあえずこれを狙っていたんですが、アマゾンじゃ取り扱ってないみたいで、他に売ってるところもよくわかりませんでした

**Comment by k-okada** [comment]
あったらいいかな，というのを３，４種類みつくろってください．

--
◉ Kei Okada


2016-02-15 23:32 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by k-okada** [comment]
あと金属ギアでなくていのかな

--
◉ Kei Okada

2016/02/15 23:32、pazeshun <notifications@github.com> のメッセージ:

**Comment by pazeshun** [comment]
遅くなってしまい、すみません。
金属ギアの方（http://akizukidenshi.com/catalog/g/gM-01724/）は今品切れしてるみたいで、入荷時期もよくわからなかったので、ナイロンギアの方にしました。細かい寸法がネットからだとよくわからず、設計の関係で早くほしいなと思った次第です。
それなりにトルクがあって（ホースを曲げないといけないので）、薄型のサーボがほしいです。
他の候補は、トルクが足りるのかよくわかりませんが、
http://www.amazon.co.jp/ROBOTIS-XL-320-DARWIN-MINI-%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E5%BC%8F%E3%82%B5%E3%83%BC%E3%83%9C%E3%83%A2%E3%83%BC%E3%82%BF%E3%83%BC/dp/B00NBLDG6A/ref=sr_1_26?ie=UTF8&qid=1455759614&sr=8-26&keywords=%E3%82%B5%E3%83%BC%E3%83%9C%E3%83%A2%E3%83%BC%E3%82%BF
とかでしょうか・・・。もうちょっと探してみます。

**Comment by pazeshun** [comment]
@k-okada 
地下の3Dプリンタで2台目のハンドを作ろうとしたのですが、材料がなくて作れませんでした。
材料を買っていただけませんか？また、買った場合、届くのはいつになるのでしょうか。
あまり遅くなるのでしたら、Dimensionでもうまく作れるような設計に変更しようとも思うのですが、なかなか難しいです。

**Comment by k-okada** [comment]
お，無いとなると，１週間以上かかるかも．
削らなくてもサポートを取る方法を探してみましょう．

--
◉ Kei Okada


2016-03-14 20:18 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by wkentaro** [comment]
Closes now.
