### ISSUE TITLE
kinect2 の設定

### ISSUE THREAD

**Issue by k-okada** [start-jsk/jsk_apc#1016]
以下のバージョンの情報を使うと良い

https://github.com/code-iai/iai_kinect2/tree/ed57f55ea4c8c34592fd91eb9e3809c5863d2a95

https://github.com/OpenKinect/libfreenect2/tree/7691a032ab86965f89577e2b334f156596c25251

**Comment by k-okada** [comment]
@kimhc6028

**Comment by kimhc6028** [comment]
![screenshot from 2016-01-25 21 45 08](https://cloud.githubusercontent.com/assets/15006217/12551638/56974414-c3af-11e5-983b-55e434f06985.png)
????できました。

**Comment by k-okada** [comment]
お，すばらしい！後は，箱の中に４０こ物をいれて画像を取ってみましょう

--
◉ Kei Okada

**Comment by kimhc6028** [comment]
![screenshot from 2016-01-26 16 16 36](https://cloud.githubusercontent.com/assets/15006217/12575353/251e0846-c44f-11e5-8638-f3cb22917ea4.png)
![screenshot from 2016-01-26 16 16 50](https://cloud.githubusercontent.com/assets/15006217/12575354/25204af2-c44f-11e5-8400-42cc8e2d28dc.png)
![screenshot from 2016-01-26 16 42 14](https://cloud.githubusercontent.com/assets/15006217/12575355/2523e108-c44f-11e5-9c69-5a0916f9ace4.png)
![screenshot from 2016-01-26 16 42 34](https://cloud.githubusercontent.com/assets/15006217/12575352/251e03c8-c44f-11e5-8695-c7a6a3f91b91.png)

bagファイル撮りましたが、これもPRしますか？

OpenClが動作しなかった問題がありました。
解決策：
'''
sudo su
echo 0 > /sys/module/i915/parameters/enable_cmd_parser
'''

**Comment by k-okada** [comment]
とりあえずPRおねがいします．
実際のカメラーTotoの距離と同じかな．
カメラは物体との距離で視野範囲が決まって，さらに距離カメラは映る／映らないも出てくるので，そこがチェック項目ですね．

--
◉ Kei Okada

**Comment by kimhc6028** [comment]
遅くなってすみません。PRを送ろうとしたら、バグファイルの大きさが１GBぐらいでpushができないですけど、どうすればいいですか？
```
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 828c67a3a0d0a41a364ea884c1599376
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File jsk_2016_01_baxter_apc/bag/shelf.bag is 935.44 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File jsk_2016_01_baxter_apc/bag/tote.bag is 1030.37 MB; this exceeds GitHub's file size limit of 100.00 MB

```
カメラーとトートの距離は、腰ぐらいに他のKINECTがあることを想定しました。BAXTERの頭の上にあるキネクトだとトートが見えないと思いました。

**Comment by k-okada** [comment]
rosbag info hogehoge.bag
してみてください．

--
◉ Kei Okada

**Comment by kimhc6028** [comment]
path:        shelf.bag
version:     2.0
duration:    4.9s
start:       Feb 01 2016 14:31:29.82 (1454304689.82)
end:         Feb 01 2016 14:31:34.73 (1454304694.73)
size:        935.4 MB
messages:    171
compression: none [171/171 chunks]
types:       sensor_msgs/Image [060021388200f6f0f447d0fcd9c64743]
topics:      /kinect2/hd/image_color        131 msgs    : sensor_msgs/Image
             /kinect2/hd/image_depth_rect    40 msgs    : sensor_msgs/Image
です。

**Comment by wkentaro** [comment]
Closes via #1077
