### ISSUE TITLE
Recognize object label in bin

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1038]
@knorth55 
https://drive.google.com/folderview?id=0B9P1L--7Wd2vNGppNmFYX29paVE&usp=sharing

![in_bin_recognition_rosbag_play](https://cloud.githubusercontent.com/assets/4310419/12754076/2471fea2-ca0d-11e5-8797-70baf2315791.png)

```
rosbag play *.bag
roslaunch jsk_data kinect2_bridge_play.launch
```

**Comment by wkentaro** [comment]
need #1039

**Comment by knorth55** [comment]
thank you
I made an easy program for visulization #1043

**Comment by wkentaro** [comment]
done?

**Comment by knorth55** [comment]
yes thank you
