### ISSUE TITLE
Error while using Kinect2: "no kinect2 device found!"

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1055]
- [ ] try fixing with https://github.com/code-iai/iai_kinect2/issues/194#issuecomment-164278699
- [ ] report this to https://github.com/OpenKinect/libfreenect2 and fix this bug

**Env**

* Ubuntu 14.04
* T440P

For "kinect2_external", building environment to use kinect2 is necessary.
Could you please try by reporting this issue on libfreenect2?
@knorth55 @kimhc6028

**Comment by knorth55** [comment]
Actually, in my case, it was BIOS setting miss for usb3.0.
I haven't seen this error after fixing the problem above.
maybe @kimhc6028 has different error cause.

**Comment by wkentaro** [comment]
Closing this, now. Please reopen when you have encounter this again.
