### ISSUE TITLE
Error while using Kinect2: LIBUSB_ERROR_XXX, depth publishing rate: ~nan hz

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1056]
- [ ] try fixing this by master branch of code-iai/iai_kinect2
- [ ] report this issue on https://github.com/code-iai/iai_kinect2/issues

Could you please try these? @kimhc6028 @knorth55 
"**kinect2_external**" is necessary for the stow task. (if not this issue must be fixed)

**Comment by kimhc6028** [comment]
Sorry for late, I will report this issue tomorrow

**Comment by wkentaro** [comment]
Closing this, now. Please reopen when you have encounter this again.
