### ISSUE TITLE
Memory Error while extracting bof

### ISSUE THREAD

**Issue by kimhc6028** [start-jsk/jsk_apc#1084]
While extracting bof from siftdata using extract_bof.py on jsk_2015_05_baxter_apc/node_scripts, I got this error
```
fitting bag of features...
Traceback (most recent call last):
  File "extract_bof.py", line 66, in <module>
    main()
  File "extract_bof.py", line 58, in main
    bof.fit(X)
  File "/home/baxter/ros/indigo/src/start-jsk/jsk_apc/jsk_2015_05_baxter_apc/node_scripts/bag_of_features.py", line 23, in fit
    km.fit(X)
  File "/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py", line 1218, in fit
    X, x_squared_norms, self.cluster_centers_)
  File "/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py", line 471, in _labels_inertia
    centers)
  File "/usr/lib/python2.7/dist-packages/sklearn/cluster/k_means_.py", line 417, in _labels_inertia_precompute_dense
    squared=True)
  File "/usr/lib/python2.7/dist-packages/sklearn/metrics/pairwise.py", line 176, in euclidean_distances
    distances = safe_sparse_dot(X, Y.T, dense_output=True)
  File "/usr/lib/python2.7/dist-packages/sklearn/utils/extmath.py", line 83, in safe_sparse_dot
    return np.dot(a, b)
MemoryError

```
It looks like memory usage explodes when fitting bof. Is there any good solution for this except for reducing number of data?
RAM size on my pc is 32GB.

**Comment by k-okada** [comment]
what is the size of the matrix ?
http://stackoverflow.com/questions/27668462/numpy-dot-memoryerror-my-dot-very-slow-but-works-why


--
◉ Kei Okada

**Comment by kimhc6028** [comment]
```
X.shape: (17836788, 128)
```
with float16, which means total size of matrix is about 4.2GB.

**Comment by k-okada** [comment]
google says:
http://stackoverflow.com/questions/4318615/python-numpy-memoryerror suggest
to call gc
if that is sparse, we can use different function:
http://www.philippsinger.info/?p=464

--
◉ Kei Okada

**Comment by kimhc6028** [comment]
If using full dataset (siftdata from all 600*25 images from berkeley dataset),
```
X.shape: (17951817, 128)
```
with float16, which consumes 4.2GB of memory.

**Comment by k-okada** [comment]
how about
http://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html

--
◉ Kei Okada

**Comment by wkentaro** [comment]
You can create batch of images to extract bof with kmeans clustering:
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2015_05_baxter_apc/node_scripts/bag_of_features.py#L21-L23
sklearn.cluster.MiniBatchKmeans supports receiving ndarray (initial centers)
http://scikit-learn.org/stable/modules/generated/sklearn.cluster.MiniBatchKMeans.html

Also, I recommend to use bag_of_features and utilities implemented in jsk_recognition
- https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_recognition_utils%2Fpython%2Fjsk_recognition_utils%2Ffeature.py
- https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/node_scripts/bof_histogram_extractor.py
- https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/scripts/create_bof_dataset.py.

**Comment by kimhc6028** [comment]
Using utilities in jsk_recognition solved most of the problem. Thank you very much.

**Comment by k-okada** [comment]
@wkentaro how did you solve memory problem in jsk_recognition

2016年2月26日金曜日、Kim Heecheol<notifications@github.com>さんは書きました:

> Using utilities in jsk_recognition solved most of the problem. Thank you
> very much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1084#issuecomment-188862454>.
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
@k-okada I used a part of the Berkeley dataset.

**Comment by kimhc6028** [comment]
May I close this issue? I think using part of the dataset solves the issue

**Comment by wkentaro** [comment]
I see, please go ahead.

2016年3月8日火曜日、Kim Heecheol<notifications@github.com>さんは書きました:

> May I close this issue? I think using part of the dataset solves the issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1084#issuecomment-193703914>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com
