### ISSUE TITLE
Accuracy of SIFT-BOF

### ISSUE THREAD

**Issue by kimhc6028** [start-jsk/jsk_apc#1093]
I have tested accuracy of sift-bof based classification, but this didn't work out really well.
Using utilities in jsk_recognition, I trained classifier with Berkeley dataset. Accuracy test on collected_images (#1060) shows very bad result.
```
score of classifier: 0.0899830220713
```
Because testing on Berkeley dataset shows really good result(score of classifier: 0.984259259259
), I doubt if SIFT-BOF is really extracting good features.
@wkentaro  Have you ever accomplished similar test before?

Script for testing accuracy is here 
https://github.com/kimhc6028/jsk_apc/blob/accuracy_test/jsk_2016_01_baxter_apc/scripts/accuracy_test_bof.py

**Comment by wkentaro** [comment]
Have you normalized the X?

2016年2月26日金曜日、Kim Heecheol<notifications@github.com>さんは書きました:

> I have tested accuracy of sift-bof based classification, but this didn't
> work out really well.
> Using utilities in jsk_recognition, I trained classifier with Berkeley
> dataset. Accuracy test on collected_images (#1060
> <https://github.com/start-jsk/jsk_apc/pull/1060>) shows very bad result.
>
> score of classifier: 0.0899830220713
>
> Because testing on Berkeley dataset shows really good result(score of
> classifier: 0.984259259259
> ), I doubt if SIFT-BOF is really extracting good features.
> @wkentaro <https://github.com/wkentaro> Have you ever accomplished
> similar test before?
>
> Script for testing accuracy is here
>
> https://github.com/kimhc6028/jsk_apc/blob/accuracy_test/jsk_2016_01_baxter_apc/scripts/accuracy_test_bof.py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1093>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by kimhc6028** [comment]
I think normalize is done at here
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/scripts/create_bof_dataset.py#L56

**Comment by wkentaro** [comment]
In that case I have no idea at this time to fix the problem.
In my case, I used the collected images as the part of both train and test data.

Maybe you can debug it by printing out the actual predicted labels and vector values to check if it is really normalized.

**Comment by wkentaro** [comment]
Close at this time.
