### ISSUE TITLE
Get to know how to run APC2015

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1099]
## TODO
- [x] json for APC2016
- [x] setup objects

## LOG
https://drive.google.com/drive/u/1/folders/0B9P1L--7Wd2vY0FWLTdrcHBWVGc

## Image Gallery
<img src="https://cloud.githubusercontent.com/assets/4310419/13572306/f3be1eec-e4bc-11e5-8c69-b0d5b7039766.jpg" width="30%" />
<img src="https://cloud.githubusercontent.com/assets/4310419/13572308/f3c0ce62-e4bc-11e5-9a75-4059f5e17ad2.jpg" width="30%" />

**Comment by wkentaro** [comment]
Link: https://drive.google.com/drive/u/1/folders/0B9P1L--7Wd2vLXo1TGVYLVh3aE0

**Comment by wkentaro** [comment]
@knorth55 Please upload images here.

**Comment by yuyu2172** [comment]
I got it. Thanks

**Comment by wkentaro** [comment]
I shared with the 4 people.

**Comment by knorth55** [comment]
@wkentaro Uploaded
