### ISSUE TITLE
IK解けるかチェック

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1105]

**Comment by pazeshun** [comment]
@knorth55

**Comment by k-okada** [comment]
baxterのIKは
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/test/test-baxter.l#L27
で確認しています．
解けたら良いIKの座標（あるいはもう領域？）をおしえてください．

**Comment by knorth55** [comment]
#1125

**Comment by knorth55** [comment]
https://github.com/jsk-ros-pkg/jsk_robot/issues/302#issuecomment-97105492

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_robot/pull/569
でIK失敗した時に変な姿勢にならないようにしたつもりです．
