### ISSUE TITLE
安全眼鏡の認識失敗

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1106]
安全眼鏡の裏側のデータを追加して学習

**Comment by pazeshun** [comment]
@kimhc6028

**Comment by pazeshun** [comment]
Berkeleyのデータセットには、安全眼鏡の裏側のデータが入っていない。
collected data setには含まれているが、データ数が少ないうえに一方向から見たデータしかない。

**Comment by kimhc6028** [comment]
僕がデータとって学習しておきます
