### ISSUE TITLE
Achieve 30 points in setup for APC2016

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1107]

**Comment by pazeshun** [comment]
- [ ] ブラックリストの作成 #1104
- [ ] 手先位置での物体認識の評価用のデータセットの構築 #1108 
- [ ] 手先位置での物体認識の改善 #1106

**Comment by wkentaro** [comment]
@knorth55
https://drive.google.com/open?id=0B9P1L--7Wd2vMVRxeXgxQ0xQUE0
に4/6の分を上げましたが、30点取れたやつがないですね。。

**Comment by knorth55** [comment]
@wkentaro ぼくのところにも最後にやった45点のものがないですね･･････ そのときぼくの携帯で取ってたはずなんですがうまくとれてなかったみたいです

**Comment by wkentaro** [comment]
了解です。とりあえず、あれはできた、ということで、次に様々なレイアウトでできるようにしたいというのがありますね。

いろいろとリストアップすると以下のようになるかと思いますが、
僕の提案としては、2015年の物品で（物品数が多数あるため）、旧グリッパを使い（新の方だと達成に時間かかりそうだから）達成するのがいいかと思います。
簡単でいいですが、システム図とタスクリストが必要になる（多分一度紙に書いたほうがいいと思います）のではないでしょうか。
あと、2016年の物品で今あるのは数が少ないと感じますが、研究室に１種類につき何個あり、競技では何個存在するのでしょうか。

### 目標
**安定的に３０点が取れるようにする**

### まず決めること
- グリッパは新/旧どちらを使うか
- 物品は新/旧どちらを使うか
- 手のカメラは使うことになりそうだがどうする？
- そろそろシステム図がほしい

### つぎに行うこと
- ランダムにJSONを作る（いまあるのではなく本当にランダムでいいのでは？）
- 棚の中での物体検出プログラムを作成する

**Comment by pazeshun** [comment]
グリッパーについてなのですが、新グリッパーの方は明日くらいにmain.lから動かせるようにして、競技に使えるようにするつもりです。ただ、urdfについてるグリッパーモデルを換装したりするのにはもうちょっと時間を要するので、認識系に障害がでる恐れがあります。しかも、新グリッパーはとりあえず右手だけなので、左手と右手でできることが違う状態に陥ると思います。

この、安定的に30点を取るというのは、認識系を改善することで達成できるものなのでしょうか。もし、グリッパーの動かし方まで変えるとなると、旧グリッパー依存となってしまい、安定的に30点を取る実験のたびにグリッパーを換装するという手間が発生するのですが。もし、認識系の改善のみで何とかなるのであれば、早急にurdfをなんとかして、右手だけ新グリッパーの状態になってくれると一番うれしいです。

あと、2016年の物品についてなのですが、僕が覚えている限りでは、それぞれ1個ずつしかないものが多く、たまに2個ある状態だったと思います。

**Comment by wkentaro** [comment]
> この、安定的に30点を取るというのは、認識系を改善することで達成できるものなのでしょうか。

はい、可能だとは思いますし、新たな変更が旧グリッパ依存にならないようにすればいいかと思います。

> 安定的に30点を取る実験のたびにグリッパーを換装するという手間が発生するのですが。

左腕は旧グリッパだということと、手につけるカメラが今はひとつしかないことから、左手にカメラを付け替えて左手だけで実験すると、そのような問題もないかと思います。
ただ結局どうするかは、@knorth55 たちと相談して決めてください。

> あと、2016年の物品についてなのですが、僕が覚えている限りでは、それぞれ1個ずつしかないものが多く、たまに2個ある状態だったと思います。

なるほど、そのようですね。 https://github.com/start-jsk/jsk_apc/blob/master/jsk_apc2016_common/data/object_data_2016.yaml#L6

**Comment by pazeshun** [comment]
> 左腕は旧グリッパだということと、手につけるカメラが今はひとつしかないことから、左手にカメラを付け替えて左手だけで実験すると、そのような問題もないかと思います。

その通りだと思いました。ご指摘ありがとうございます。ただ、 #1243 のような問題が起こっているので、CREATIVE cameraを旧グリッパーにつける事になった場合は少々不安定かとは思います。とりあえず実験するのであれば、実験中にカメラのコードが引っかからないように気をつければ問題ないとは思いますが。

**Comment by wkentaro** [comment]
次の目標は　http://jsk-apc.readthedocs.org/en/latest/jsk_2016_01_baxter_apc/milestone/stable_achievement_30points.html　
で決まりました。
