### ISSUE TITLE
Generate json for APC2016

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1110]
### APC2015

| Number of bin_contents | Points | Number of bins |
|------------------------|--------|----------------|
| 1                      | 10     | 4              |
| 2                      | 15     | 5              |
| 3-                     | 20     | 3              |

### APC2016
| Number of bin_contents | Points | Expected number of bins |
|------------------------|--------|-------------------------|
| 1-2                    | 10     | 4                       |
| 3-4                    | 15     | 5                       |
| 5-                     | 20     | 3                       |

**Comment by kimhc6028** [comment]
**APC2016
**
Number of bin_contents|Points|Number of bins
---|---|---
1-2|10|5
3-4|15|2
5-|20|5

**Comment by kimhc6028** [comment]
***APC2016
| Number of bin_contents | Points | Number of bins |
|------------------------|--------|----------------|
|           1-2          |   10   |        4       |
|           3-4          |   15   |        5       |
|           5-           |   20   |        3       |

**Comment by wkentaro** [comment]
Thanks.
