### ISSUE TITLE
Please add @yuyu2172 to start-jsk

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1111]
@k-okada  please.

**Comment by k-okada** [comment]
done

**Comment by wkentaro** [comment]
@k-okada 
He's not there, is he?
<img width="1431" alt="screen shot 2016-04-08 at 4 46 09 pm" src="https://cloud.githubusercontent.com/assets/4310419/14377195/80f64fb4-fda9-11e5-8fed-9768a3bc7d05.png">

**Comment by k-okada** [comment]
![screenshot from 2016-04-08 16 51 40](https://cloud.githubusercontent.com/assets/493276/14377378/44356528-fdaa-11e5-9c49-3c2558bc48fc.png)

**Comment by wkentaro** [comment]
I'd like to add him to this group. https://github.com/orgs/start-jsk/teams/jsk_apc-team-k

**Comment by wkentaro** [comment]
to use this mention @start-jsk/jsk_apc-team-k

**Comment by wkentaro** [comment]
Could you please add him? Or are there any problem about it?

**Comment by k-okada** [comment]
I, see. Added

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Thank you.
