### ISSUE TITLE
オブジェクトを返す途中にvacuumがoffになることがある。

### ISSUE THREAD

**Issue by ban-masa** [start-jsk/jsk_apc#1131]
誤ったオブジェクトを吸引しverifyした後に元の位置へ戻す途中で、vacuumがoffになった。
その結果、オブジェクトをbinに戻す前に落としてしまった。
圧力センサがオブジェクトを把持していないと判断したためvacuumがoffになったと考えられるので要検証。

**Comment by wkentaro** [comment]
verifyで認識結果が来るかどうかも見ていて、10秒経っても来なかったらそもそも掴んでいないと判断します。それが原因かもしれません。

**Comment by wkentaro** [comment]
返す動作までやっているなら別の原因だと思いますが。

**Comment by ban-masa** [comment]
binの中へグリッパーが移動していたので、おそらく返す動作の途中でvacuumがoffになっていたと思います

**Comment by knorth55** [comment]
@ban-masa

**Comment by ban-masa** [comment]
stop-graspをいくつかコメントアウトした結果オブジェクトを返す途中でバキュームが切れて落とすことはなくなりました。不慣れなのでよく分からないのですがpull requestを送ればいいんでしょうか。

**Comment by k-okada** [comment]
はい．送ってみて下さい．

--
◉ Kei Okada


2016-03-14 13:46 GMT+09:00 Bando Masahiro <notifications@github.com>:

**Comment by ban-masa** [comment]
返す途中にバキュームがオフになるという問題に直接対処できたわけではないですが再現性が低いのでissueを閉じます
