### ISSUE TITLE
2016/03/10 Trial

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1132]
- [x] pickの際に実際はgraspできているが、それを認識できない(graspingpがnil)ので棚から腕を引き出す。しかしその動作が早いため吸引が切れる前に物体も一緒に引きずられて落ちる
- [ ] return objectの途中で掃除機が切れる
- [ ] returnしたobjectをまたとってしまう
- [ ] work orderがあまりよくない（9個アイテムがある棚に右手がいっている）
- [ ] 袋が大きい物体を棚に戻す際に棚の下にひっかかって落としてしまう

**Comment by knorth55** [comment]
やっていること
- return objectの途中で掃除機が切れる #1131 
- returnしたobjectを奥に入れる #1129 
やりたいこと
- collision checkをして右手左手で同時作業できるbinをみつけたい

**Comment by kimhc6028** [comment]
左手の吸引が、ちゃんと持っているのにいきなり切れてしまう

**Comment by knorth55** [comment]
movies https://drive.google.com/drive/u/1/folders/0B-9DG8FkNGtJUkpfQXhsMzBqM28

**Comment by wkentaro** [comment]
@knorth55 please move to doc.

**Comment by knorth55** [comment]
able to close
