### ISSUE TITLE
Failed to pull out arm, dragging objects to fall off

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1134]
When  the robot is grasping an object in real, however, ```graspingp``` is ```nil``` and it is trying to pull out its arm, the arm moves quickly so that some objects are dragged and fall off.

drag objects to fall out in ```:try-to-pick-in-bin```

**Comment by knorth55** [comment]
@ban-masa

**Comment by knorth55** [comment]
In 20160311_overall_apc_trial, when baxter moved its arm down in bin to retry grasping objects, the arm move backward so that it dragged objects to fall out.
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/baxter-interface.l#L278

**Comment by knorth55** [comment]
when the robot pull off the arm, do ```:spin-off-by-wrist```

**Comment by knorth55** [comment]
assigned to @knorth55

**Comment by wkentaro** [comment]
Closed via https://github.com/start-jsk/jsk_apc/pull/1217
