### ISSUE TITLE
Installing CREATIVE interactive gesture camera

### ISSUE THREAD

**Issue by kimhc6028** [start-jsk/jsk_apc#1137]
![screenshot from 2016-03-12 16 59 31](https://cloud.githubusercontent.com/assets/15006217/13721885/43776be2-e877-11e5-83ca-e16199b7e958.png)
It works fine with Ubuntu 14.04
Also, it looks like running 2+ cameras on one computer is possible.
@k-okada  Could I have one more camera to test if I can run two cameras on one pc?

**Comment by k-okada** [comment]
nice! Let's took camera on the baxter arm and see if it works.

On Sat, Mar 12, 2016 at 5:32 PM, Kim Heecheol <notifications@github.com>
wrote:

> @k-okada <https://github.com/k-okada> Could I have one more camera to
> test if I can run two cameras on one pc?
>
>
Ok, I'll asking to students again.

--
◉ Kei Okada

**Comment by kimhc6028** [comment]
![screenshot from 2016-03-12 18 11 33](https://cloud.githubusercontent.com/assets/15006217/13722158/67f2e742-e87e-11e5-8dea-77eebef1519b.png)
![screenshot from 2016-03-12 18 12 57](https://cloud.githubusercontent.com/assets/15006217/13722159/7ce77168-e87e-11e5-9bd4-06286d49c412.png)
I think it has higher resolution than kinect2 in range < 1m.

**Comment by wkentaro** [comment]
Please write how to install to the docs.

**Comment by yuyu2172** [comment]
Install this https://github.com/ipa320/softkinetic

**Comment by knorth55** [comment]
@yuyu2172 already installed in theta?

**Comment by knorth55** [comment]
How to install it actually? below is correct?
```
git clone  https://github.com/ipa320/softkinetic
cd softkinetic/softkinetic
catkin bt -iv
```

**Comment by yuyu2172** [comment]
Check instructions on https://github.com/ipa320/softkinetic/tree/indigo_dev/softkinetic_camera.
You need to install DepthSenseSDK.

**Comment by wkentaro** [comment]
oops sorrry @knorth55 .
I mistakenly commented with your account.

**Comment by wkentaro** [comment]
@yuyu2172 could you please update the doc? as https://github.com/start-jsk/jsk_apc#optional

**Comment by knorth55** [comment]
its my mistake, its ok
