### ISSUE TITLE
Make overall stow program for apc

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1138]
Just making simple stow program (not complicated)

**Comment by knorth55** [comment]
@knorth55 is working on this issue

**Comment by wkentaro** [comment]
@knorth55 Please focus on this. We need to do this in version 1.5. https://github.com/start-jsk/jsk_apc/milestones/1.5:%20APC2016%20ver1.0%20(Pick%20+%20Stow)

**Comment by knorth55** [comment]
ok

**Comment by knorth55** [comment]
Make stow motion in #1150, but there is no recognition program.
next, we need to add recognition program.

**Comment by knorth55** [comment]
#1645
