### ISSUE TITLE
圧力センサの選定

### ISSUE THREAD

**Issue by ban-masa** [start-jsk/jsk_apc#1141]
吸引の圧力値を取得したい。
秋月のラインナップでぱっと見て良さそうなもの。
*LPS25H http://akizukidenshi.com/catalog/g/gK-08338/ 
**精度は1hPa程度。サンプリングレートは最高25Hzまで
*ＳＣＰ１０００－Ｄ０１ http://akizukidenshi.com/catalog/g/gM-03468/
**分解能1.5Pa。データシートを軽く読んだ限りでは精度不明だがおそらく1hPa程度。サンプリングレートは最高9Hz。
スイッチサイエンスで買えるもの
*https://www.switch-science.com/catalog/list/110/
**Xadow、BME280、LPS331あたりが候補でしょうか。
この中から適当に選ぶ。

**Comment by k-okada** [comment]
買ってみました．

--
◉ Kei Okada


2016-03-14 15:01 GMT+09:00 Bando Masahiro <notifications@github.com>:

**Comment by ban-masa** [comment]
@pazeshun 圧力センサは https://www.switch-science.com/catalog/2236/ これを使う前提でハンドへの組み込みを設計してもらえますか。

**Comment by pazeshun** [comment]
@ban-masa わかりました。この基板にピンヘッダをはんだ付けして、そこにコードを挿すイメージですか？

**Comment by ban-masa** [comment]
@pazeshun 多分そうなると思います。センサ部分だけ吸引ルートに組み込んでコードで外部のarduinoにつなぐ感じでしょうか。もっとよさげな付け方があればそっちで構いません。

**Comment by ban-masa** [comment]
BME280の性能をチェックしてみました。
サンプリング周期の関係から圧力変化の傾きは取得できなそうですが、吸引off、吸引onかつ物体なし、吸引ofかつ物体把持を区別することは可能でした。
また空気の漏れやすい物体の把持についても、把持しているか否かの区別は可能でした。
1000hPa付近が吸引off、910hPa付近が吸引on、850hPa付近が物体把持時の出力値です。
![bme280_test](https://cloud.githubusercontent.com/assets/14898742/13944940/d2385288-f04c-11e5-8c9b-8db16677b1dd.png)
