### ISSUE TITLE
評価用のJSONの区別について

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1143]
- 同じjsonに対してのスコアや評価をするために変更されない共有するjsonが必要
- interface_generatorは今はjsonを上書きをしてしまうことがある

このため
1. 変更されない共有するjson （一定した評価のため）
2. 変更してもいい共有されないjson （個人のテスト用など）
の2種類のjsonが必要

個人的な考えとしては
1. -> sample_layout_pick_*.json 
2. -> interface_generatorが生成するlayout_pick_*.json
とするのがわかりやすいかなと思いましたが他の意見も聞きたいです。

@wkentaro さんは
json生成プログラムを変更することでjsonの上書きをされないようにすることでjsonを名前で区別する必要はない（？）のではないかという意見です。

詳しくは #1136 

cc. @kimhc6028

**Comment by kimhc6028** [comment]
最初に多数のjsonを作っとけば、個人で変更する必要があるjsonはあまりいらないと思いますが。。もし、手でjsonを変更するならば、interface_generatorは使えないと思うし。（そもそも僕がちゃんと理解してない気もするんですけど）
上書きできないように変えるのは、賛成します。

**Comment by knorth55** [comment]
@kimhc6028 つまりjsonの名前はpick_layout_*.jsonとstow_layout_*.jsonだけってことでOK？

**Comment by kimhc6028** [comment]
sample..や、pick&stow...のどっちかにして、interface_generatorもそういう名前で生成するようにしておく。個人的に「これ試したい」という配置があれば、もとのjson fileをコピーしてtemp_何とかの名前をつけて配置を変えて実験してみて、もしそれが長期的に実験してみる価値があると思えばsample or pick&stow ...+1.jsonで保存して、もしそうじゃなければすぐ消すような規則はどうですか。

**Comment by knorth55** [comment]
了解です
