### ISSUE TITLE
新作グリッパーにはさむタイプのグリッパーを追加するべきか

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1151]
今年の物品リストを見て、現在製作中のグリッパーではつかみにくいものが多すぎるのではないかと思い始めた。具体的には、
- ダンベル、ハサミ、ブラシ類（グリッパーの当たり所によっては空気抜けする）
- テープ（水平に置かれると上から吸い付くのは困難。横からなら吸い付けるが、背が低く、そこまでグリッパーを持ってくるのが難しいかも）
- 水（重い）

取れる確率を上げる方法の一つとして、手先にはさむタイプのグリッパーを追加するというのが考えられるが、今まではとりあえずつけない方針で設計を行っていた。直動関節式のグリッパーを後付けできるようにはなっているが、それでは上記の物品を把持するのは難しいように思われる。設計を変更し、手先にはさむタイプのグリッパーを追加するべきだろうか

**Comment by pazeshun** [comment]
設計変更のメリット
- 物品を把持する方法ができる。完全なお手上げ状態にならない。

デメリット
- 現時点で構造を思い描けないため、設計変更に時間がかかることが予想される。
- とりあえず現在のグリッパーを作ったとしても、後から変更することになるので、材料とプログラムの無駄といえるかもしれない

私としては、とりあえず今のグリッパーを1個作り、それを試してもらいながら設計変更を進めていこうと思っているのですが、どうでしょうか。

**Comment by k-okada** [comment]
基本的には，今あるものですすめながら，よりうまく行く方法を常に考えつつ変更を加えていく，以外にはないとおもいます．よく言われることは「パラレルに進める」ということで上の作戦でいいと思います．
基本的には吸引＋グリッパ
（両手で一個づつでもいい気もしてくる）なシステムになるのと，ある程度対象物のカテゴリーに応じて作戦が出てくるような形になるきがしまが，上のように課題の分類ができていれば，それを解決するもの，としてグリッパーのハードウェアと，その戦略を判断する認識部と合わせていくので，よい研究テーマになっている様に見えるので，このリストを作ってくれた人に感謝したらいい気がします．


--
◉ Kei Okada


2016-03-20 12:20 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by pazeshun** [comment]
家にあった物品と、持ち帰ったグリッパー先端部分を使って実験を行いました。掃除機の吸引力がJSKのものとは異なったり、吸い付きすぎると吸引力が弱まる機能がついていたりするので、JSKの場合でも同じ結果になるとは言えませんが、以下の知見を得ました。
- ボールは、あまりにグリッパー中心からずれていると、グリッパーの縁にあたって逃げて行ってしまうが、多少のずれであればグリッパーに引き寄せられ、吸い付ける。吸い付きは申し分なし。はさむタイプのグリッパーでグリッパー中心にボールを持ってこれると、取れる確率が上がりそう。
- ハサミは、支点付近の比較的面積が広い部分にグリッパー中心を持ってこなければ、吸い付くことができない。吸い付けても、空気が盛大に漏れており、吸引力は弱い。軽いので持てている状況。はさむタイプのグリッパーがあったとしても、ハサミは薄いために把持は非常に困難。[Googleで使ってたロボットハンド](http://jp.techcrunch.com/2016/03/09/20160308what-could-go-wrong/)のようなもので上からつかめればいいが、APCだと棚が邪魔で困難。ハサミはかなり難しそう。
- 歯ブラシは、物体の位置にグリッパーを持ってくることができればとれる。吸い付きも十分。背丈が低く細いので認識は難しいかもしれない。また、はさむタイプのグリッパーではそもそもひっかけるのが難しいかも。
- テープは、やはり水平に置かれた場合は上から吸い付くことはできない。横からなら確実に吸い付ける。吸い付きも十分。
- 水は、やはり重さがネック。立たせてある場合は、ボトルの下の方を吸ってしまうと、持ち上げようとしたときに吸引がはがれる。真ん中付近か、それより上側にグリッパーを持ってくるべき。適切な位置を吸えれば、回してもはがれない。寝かせてある場合は、真ん中あたりを吸えば持ち上げられる。

全てにおいて、グリッパーの位置が大きなポイントになってくると思われます。水やテープ、ボールをつかむ場合においては、目標の物体の位置を制限するという意味でもつかむタイプのグリッパーが有効であると認められますが、歯ブラシやハサミは、そもそも認識を頑張らないとどうしようもなさそうです。

**Comment by pazeshun** [comment]
以上の結果から、グリッパーがどういったものになるにせよ、物品が棚にある時点である程度何がどこにあるかをわかっている必要があると思われます。
@knorth55 , @kimhc6028 , @yuyu2172 はどう思われますか。

**Comment by kimhc6028** [comment]
今の吸引で取れなさそうなものはダンベル、水、鉛筆箱、ハサミぐらいですかね。他は去年と同じくらいの難易度かなと思いますが。
この中で、吸引だと物理的に取れないものはダンベルと鉛筆箱だと思いますが、この２つのためにグリッパを再設計するのはリスクが高くないかなと思います。個人的には、その２つ以外には、吸引を使って行けなくてグリッパを使っては行けるものはないんじゃないかなと思います。今の方法で進んだらどうですか。
binの中での物体認識プロセスを追加して（できるのかは自身ないですが）、物体ごとに違う掴む戦略を使ったら（例えば、水だと、一旦倒してから掴むとか、ハサミなら真ん中を掴むとか）どうでしょうか

**Comment by pazeshun** [comment]
反応ありがとうございます。
先生、認識班ともに今の計画のままの吸引オンリーのグリッパーでとりあえずは進めるべきというご意見でしたので、このまま進めようと思います。
並行して、はさむタイプのグリッパーをうまく組み込めないかどうか、検討していきます。

先生が指摘された、両手で吸引とはさむタイプのグリッパーを分ける案についてですが、両端のbinに逆手で手を伸ばすと、グリッパー先端が棚の奥行の半分も届かなかった気がするので、なるべく避けたいと思っています。

できることならはさむタイプのグリッパーを組み込みたいので、このIssueはOpenのままにしておきます。

**Comment by pazeshun** [comment]
この問題は、私の中で優先順位が極めて低くなったので、いったんissueを閉じます。
また重要になってきたら開きなおします。
