### ISSUE TITLE
baxterの棚との干渉を防ぐ

### ISSUE THREAD

**Issue by ban-masa** [start-jsk/jsk_apc#1191]
棚の奥のほうにアプローチする際に、baxterのアームの吸引ホースとの接続部分などが棚に衝突することがある。アームと棚との衝突を回避する手法を考える必要がある。

**Comment by pazeshun** [comment]
棚の奥にある物品へのアプローチについては、 af05c2f7 で、アプローチした際に手カメラと棚が衝突してしまうほど奥にある物品は把持をあきらめるようになっている。
現状、グリッパについている大きな突起物は手カメラと吸引ホース接続部であり、手カメラの方がグリッパ先端に近いので、とりあえずは衝突回避ができているといえる。
