### ISSUE TITLE
3/22 ハンド部分の今後の方針

### ISSUE THREAD

**Issue by ban-masa** [start-jsk/jsk_apc#1194]
新しいハンドには圧力センサーとサーボが搭載されるが、その方法について @pazeshun と話し合った。
方針としてはハンドにarduino nanoを取り付けて、そこにサーボ及び圧力センサを接続することとなった。
arduino nanoの設置場所については従来のようにbaxter本体に取り付けることも考えたが、信号線が長くなるとノイズが懸念されるので、ハンド部分に取り付けることにした。
サーボ用の電源としては、5VACアダプターを用いる予定。したがってハンドのarduinoからusbケーブルとACアダプタのケーブルが伸びることになる。
近日中に試作回路を作成する予定。

**Comment by ban-masa** [comment]
試作回路はできたのでfirmware作成中。
圧力センサの値をpublishすることはできた。
servo角度をsubscribeする部分も書いたが、まだ試していない。
https://github.com/ban-masa/jsk_apc/blob/test_2016_baxter_apc/jsk_2016_01_baxter_apc/firmware/arm_manager.ino

**Comment by ban-masa** [comment]
servo角度をsubscribeすることができたのでarduinoのfirmwareは一応の完成。
@pazeshun

**Comment by pazeshun** [comment]
@ban-masa 
ありがとうございます。
できれば、[IDEを使わずにCMake build systemで管理](http://wiki.ros.org/rosserial_arduino/Tutorials/CMake)したいですが、とりあえずグリッパー部分とつなげて全体のシステムに組み込むのが先決ですかね。
4/4にグリッパーを研究室に持っていくので、その時に回路、ファームウェア含めてPCにつなげる状態にしましょう。

**Comment by pazeshun** [comment]
一応、システムとして完成しました。
![1459778081506](https://cloud.githubusercontent.com/assets/14994939/14250263/8d792d72-fab8-11e5-906d-f46b9d6a2481.jpg)
@ban-masa ありがとうございます。
あの後、sheetaからもrosserialが起動できて、サーボの角度を変更したり、圧力センサーの値を見ることができました。
考えられる改善点等は新しいissueにまとめたので、それを元に改善を進めたいです。同時並行で、新グリッパーをmain.launchから使えるようにしていきたいです。

**Comment by pazeshun** [comment]
Please close this
