### ISSUE TITLE
3Dプリンタを用いてカメラを腕に装着

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1196]
CREATIVEカメラを腕に装着するための装置を3Dプリンタで設計する。

@k-okada  設計ソフトSolid Edgeを使いたいのですがどうしたらよいでしょうか？

**Comment by pazeshun** [comment]
@yuyu2172 
装置の設計ですが、僕がやりましょうか？
どうせ、ハンドも作ってますし

**Comment by yuyu2172** [comment]
@pazeshun 
できるようでしたら、お任せします。

**Comment by pazeshun** [comment]
すみません、 @wkentaro のメールを読んでませんでした。
私の作業計画としては、グリッパー部分を3Dプリンター(Dimensionの方)に出力するついでに、カメラの台座を出力するつもりでいたのですが、まだカメラの台座の設計にはとりかかれていないし、もうできてるグリッパーのファームウェアを作るほうが優先である気もするので、後回しになっています。
カメラの台座ですが、すぐに必要ですか？
もしそうなら、僕の作業の優先順位を変えるか、 @yuyu2172 に設計していただくかなのですが。

**Comment by k-okada** [comment]
ソリッドエッジは浅野君に聞いてインストールしておいて下さい．

--
◉ Kei Okada

**Comment by yuyu2172** [comment]
@pazeshun 
わかりました。
それでは僕が担当します。

@k-okada 
わかりました。ありがとうございます。

**Comment by yuyu2172** [comment]
話していて@pazeshun が設計を担当してくれることになりました。

**Comment by pazeshun** [comment]
とりあえず、設計してみました。
![demo](https://cloud.githubusercontent.com/assets/14994939/14057671/06c10abc-f34b-11e5-8378-b964f2b6c67e.png)
月曜日に寸法をもう一度確認してから3Dプリンターに出力し、火曜日に仕上げを行う予定です。

**Comment by pazeshun** [comment]
出力しました。
明日完成します。

**Comment by k-okada** [comment]
カメラ，できたら，とりあえずどういう実験をしようとかあるかな．pickで棚の中の物を取り出す，という以外に
@knorth55, => 棚の中に物を戻す動作．（箱などが棚にぶつかることが分かるか）
@kimhc6028,  => stow
タスクの箱の中を取り出す実験（テストになるような実験環境を４個ぐらい作って写真にとって，それを繰り返し練習出来るようにしたい）
@yuyu2172 => いまの頭のkinectでverifyしている最中に手のカメラでもverify できるか
などをチョット試してみてもらえるといいかな，

--
◉ Kei Okada

**Comment by pazeshun** [comment]
できました。
![1459241506823](https://cloud.githubusercontent.com/assets/14994939/14103129/7f4802d4-f5d9-11e5-8a5f-4d8e4adfa99c.jpg)
このままにしておくので、ケーブルが邪魔な場合は養生テープでとめてください。

**Comment by yuyu2172** [comment]
次はカメラを用いて認識ができるように、手のカメラの座標系の取得をやってます。

**Comment by wkentaro** [comment]
> @yuyu2172 => いまの頭のkinectでverifyしている最中に手のカメラでもverify できるか

ちなみに今はtorsoのカメラでverifyしています．

**Comment by knorth55** [comment]
new issue #1243, close this
