### ISSUE TITLE
Arduino Nano Chinese Cloneの異常加熱

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1197]
表題のとおりですが、いつの間にか異常に熱くなってました。
PCにつないでおいただけなのですが。
燃えるものもあるという話もあるし、デフォルトだとrosserialがつながらない件もあるので、正規品を買ったほうがいいのではないでしょうか。

**Comment by k-okada** [comment]
これなら大丈夫，というやつのリンクを貼っておいて下さい．

--
◉ Kei Okada


2016-03-28 21:10 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by pazeshun** [comment]
http://www.gravitech.us/arna30wiatp.html
これが正規品で、USB-シリアル変換チップもFTDIなので安心です。ただ、ここまで高いとは思ってませんでした。
Cloneの中から大丈夫そうなやつを選んだ方がいいのかも知れません。

**Comment by pazeshun** [comment]
やっぱり、比較検証の方法を残すためにも、買っておいたほうがいいと思います。

**Comment by k-okada** [comment]
amazonか，秋月か，どこかのリンクをはっておいてください．

--
◉ Kei Okada


2016-03-29 19:33 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by pazeshun** [comment]
返事が遅くなってしまいすみません。
Arduinoの内部分裂の話を知らなかったです。
日本における正規品は、
http://akizukidenshi.com/catalog/g/gM-09059/
とか、
https://www.switch-science.com/catalog/2554/
になると思います。
