### ISSUE TITLE
When arm goes far inner of bin a, b, c and cannot solve ik, pull out the arm safely

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1209]
when the arm goes far inner of bin a, b, c (upper bin), it cannot solve ik, and the arm hit bin's wall.

**Comment by k-okada** [comment]
can we reproduce this posture ( or sequence of posture) on euslisp?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Closed via #1337
