### ISSUE TITLE
Buy poles for the Kiva Pod shelf

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1211]
In order to make the experiment done smoothly.

- Can we buy? @k-okada 
- Please assign someone. @knorth55

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/14211255/f3ed8cf4-f867-11e5-8ef2-4d96a275d766.jpeg)
this one.

**Comment by wkentaro** [comment]
ドイトに行きましたが、売っていませんでした。

**Comment by k-okada** [comment]
なんか園芸用のパイプみたいなもので櫓が組めるものでもいいかな

--
◉ Kei Okada

**Comment by k-okada** [comment]
https://www.google.co.jp/search?q=%E5%9C%92%E8%8A%B8+%E6%A3%9A%E3%80%80%E3%83%91%E3%82%A4%E3%83%97&client=ubuntu&espv=2&biw=1745&bih=841&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwi1lZO1tfTLAhVE26YKHaPJDvAQsAQIMw&dpr=1.1
https://www.monotaro.com/p/0687/8593/?gclid=Cj0KEQjwoYi4BRDF_PHHu6rI7NMBEiQAKZ-JuPAJyxTNmE5sN3fVE37DDGbHTTTvofk7vHKXD5WryfsaAmsY8P8HAQ&utm_medium=cpc&utm_source=Adwords&cm_mmc=Adwords-_-cpc-_-PLA-_-06878593&ef_id=VFNMRAAAAftekCKD:20160404070427:s

--
◉ Kei Okada


2016-04-04 16:04 GMT+09:00 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>:

**Comment by k-okada** [comment]
あとは
https://www.google.co.jp/search?q=%E5%9C%92%E8%8A%B8+%E6%A3%9A%E3%80%80%E3%83%91%E3%82%A4%E3%83%97&client=ubuntu&espv=2&biw=1745&bih=841&source=lnms&sa=X&ved=0ahUKEwigwJLCtfTLAhWmL6YKHUd3A6cQ_AUIBigA&dpr=1.1#q=%E6%B0%B4%E9%81%93%E3%80%80%E3%83%9B%E3%83%BC%E3%82%B9%E3%80%80%E6%AD%A2%E3%82%81%E3%82%8B&tbm=shop&spd=3200019094729612348
みたいなので止めるのがCMU流


--
◉ Kei Okada

**Comment by wkentaro** [comment]
結束帯で止めました．
<img src="https://lh3.googleusercontent.com/ioepWyEMH7zJXJmZtYtHFp1a2c6CB_7mrnPzby6szcEPQ8qkcKyygkBRU0y5isvt6bp-s68rj-IqyAhkU4ZbSQh7mEQReREE1ITTFqj3wWOE3xwULbVScGbaHj6UZc5FI0NvXEWD0RUJvrIJtv6g0PpaHWsfuCQRAoyPfI20fnet6sDIfraoe-Da5it-VDQ0y6m4hzF6PuttGtrcZh2Nnmm9dtz-VzmsXTl6LtIr-chzgQsSs0MJygjFIxJWZLqsM4UidL1TBwy-vpQjHFmpdGWx6Eray2m0wdWJuDoGV9fnbP1vAN_Hl86WxOVPfQ87LRB9LA73PxQ7mUi9lFwSIa1FgH_n6Mjp6t4G9DRwLQAJsBo3ayvTbSq7Zx5IMtug4oq7NDU63mc-0QWROJxPiVp2utS7o-zZ7S0gcH0pPhnyS5uHk-hLIGWVk6xIBmbkhktwuYY-dgpEH5O-nMA4HAvyqmPaxNu1tiTKBEww9qMoIng0A_-MicnTzQPjl40-FwGbhZGJ4msrjsCSthDitBcd64YTGIxoQ2aERt52Ndl5LzsLEDagsNmzIS_29v_wrxvalw=w2086-h1564-no" width="50%" />
<img src="https://lh3.googleusercontent.com/M0Rc2O5QSPMuYNpBIBzCbGgvVhudvEr19VR5OO-1TjNpHnHL3DpMZcmuNI8hCuINBtWPtmgqhi329WywCpyYeiz44GODSzlZCgpSeAYaPeV5OdudUqadFrVA_VgeskyQB7kgiGRnjZ0LDGQ9n0kCxIOiyVsAepKhEP-EO1FwqeCp6wZ_Q4_Ln7BASvV91iq5oybH1G0RFHwHQXyLdgmMmpynrqeOA_Nafmq3iudJLXoj1zIrgfh7clnGNLfFljAPKdigt0wE2jkmBAu_NMFnxXZAfTUKY1NvJhOfs5VCJfJSoaXGNIQziG0PIRhqkrYshEtnoLAk8mqCPsJk1ab8DWpz3UoaGGDdK3QnIGUUGPPL0CpACitieRSUB_wSFDcglMlEMehZYyGEb-av-tcHaMJZPkaBTtGhNhuJZbwIdjeQVMGcXyXfenMCsXVU4c7ixCthjLxyWK-ssJgXPFL2EmyfFgXgd8hF79OuyPDPmqr0ZA59edmXyGatbC-50DbMUqgsmjZucZob3GzaqiCzIm-Mc-UhVaQ-TgkosWiqv6FGGbo1g07WaMutApzEyaq6EJVkbg=w2086-h1564-no" width="50%" />
