### ISSUE TITLE
Introduce apc2016 object segmentation process with softkinetic camera

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1218]

**Comment by wkentaro** [comment]
What is this in concrete.

**Comment by knorth55** [comment]
Combine segmentation image processing program and softkinetic camera for 0.2.5 milestone

**Comment by wkentaro** [comment]
So it's better if title is "Introduce object segmentation pipeline by hand camera for overall APC task"?

**Comment by knorth55** [comment]
maybe

**Comment by wkentaro** [comment]
@knorth55  Is that possible for you to complete this by this Saturday?

**Comment by knorth55** [comment]
@wkentaro it depends on #1421

**Comment by wkentaro** [comment]
Closed via the introduced launch file.
