### ISSUE TITLE
新グリッパーの改善点について

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1223]
新グリッパーについて、以下のことを改善したい。上から優先度が高い順に並んでいる。

- [x] arduinoの基板の形状を整え、穴を開ける。→ @pazeshun 機を見てすぐに行う。
- [x] 新しいグリッパーと掃除機のホースをつなぐ根元部分の部品の新作を作り、圧力センサーとarduinoが固定できるようにする。→ @pazeshun 3Dプリンタの材料が届き、プリンタが使えるようになり次第作成。 @k-okada 地下の3Dプリンターの材料はいつ届くのでしょうか？
- [x] サーボモータのトルクをtopicからon/offできるようにする。トルクがoffの際は、サーボモータの角度をtopicに流してもサーボはonにならないようにする。  
(理由) 水平にしたグリッパーに吸い付けた物品を引き出す際、サーボのトルクをoffにしておくと、物品が完全に引き出された際に、自重でサーボ部分が勝手に回転し、結果的に最も吸引がはがれにくい姿勢となった。このようにサーボのon/offを切り替えられると、何かと便利そうだから。  
→ @ban-masa お願いできますか？
- [x] サーボモータの角度やトルクのon/offの状態をtopicに流す。その際、トルクがoffの時でもサーボモータの角度は最後に指令された角度のまま。  
(理由) 現在の状態を知れるtopicがあれば、それをsubscribeしてeuslispで使えるから。  
→ @ban-masa お願いできますか？
- [x] トピック名を考える。具体的には、どのトピックが新旧どちらのArduinoから出ているのかわかるようにしたい。
- [ ] firmwareをArduino IDEを使わずCMake build systemで管理。  
(理由) 他のfirmwareがおそらくそれで管理されているので、できればそろえたい。  
→ 今すぐ必要のないことなので、後回し。 @pazeshun か @ban-masa に余力があれば行う。

Assignee: @start-jsk/jsk_apc-gripper

**Comment by pazeshun** [comment]
Please assign @ban-masa

**Comment by pazeshun** [comment]
最初の改善点を達成しました。
![1459839121458](https://cloud.githubusercontent.com/assets/14994939/14273690/66715d6e-fb47-11e5-9b00-e339d772ec36.jpg)

**Comment by pazeshun** [comment]
3Dプリンタの材料が届いたので、出力に入りました。

**Comment by pazeshun** [comment]
Please assignt @pazeshun

**Comment by pazeshun** [comment]
あ、assigneeって一人しかなれないんですか。
すみません、わかってませんでした。
assign外してもらえますか？

**Comment by ban-masa** [comment]
@pazeshun トルクのon/offおよびそのpublishにfirmware上で対応しました。まだ実際に試してはいません。
https://github.com/ban-masa/jsk_apc/commit/01b996ba5bdcec19119398b43d7c79da58e9427f

**Comment by pazeshun** [comment]
@ban-masa ありがとうございます。

**Comment by pazeshun** [comment]
根元部分の部品の新作ができ、圧力センサーとarduinoが固定できるようになりました。
![1460020686721](https://cloud.githubusercontent.com/assets/14994939/14346571/d20b6ac2-fced-11e5-9f59-04b2a60f3f85.jpg)
baxterに取り付け、ケーブル等を取り付けてみたところ、以下のように、USBケーブルが管と接触し、arduinoを挿したままでは抜き差しが困難になりました。
![1460020675968](https://cloud.githubusercontent.com/assets/14994939/14346637/0b21a312-fcee-11e5-97ec-ada1a00fb32b.jpg)
電源ケーブルも管の外側にはみ出てしまっているので、もしかすると基板の形を考え直した方がいいかもしれません。

**Comment by pazeshun** [comment]
@ban-masa 
firmwareにおけるサーボ角のsubscribeおよびpublishについてなのですが、単位は度よりもラジアンのほうが、他の関節角との親和性が高いのでいいかもしれません。グリッパーがまっすぐの時を0radとして、角度の正負はひとつ前の関節とそろえるといいのではないでしょうか？

あと、Arduinoから出すトピック名についてなのですが、新旧Arduinoで区別したいという意見がありました。現在、/gripper_grabbed/limb/right/stateは旧Arduinoと同じですし、他のトピックはすべて/vacuum_gripper/limb/right以下にあるという点も同じなので、変えた方がよいかもしれません。

注文が多くて申し訳ないです。

**Comment by pazeshun** [comment]
gripper_grabbed/limb/right/state→gripper_front/limb/right/pressure/grabbed/state
vacuum_gripper/limb/right/pressure→gripper_front/limb/right/pressure/state
vacuum_gripper/limb/right/servo_state_info→gripper_front/limb/right/servo/torque/state
vacuum_gripper/limb/right/servo_angle_info→gripper_front/limb/right/servo/angle/state
vacuum_gripper/limb/right/servo_angle→gripper_front/limb/right/servo/angle
vacuum_gripper/limb/right/servo_state→gripper_front/limb/right/servo/torque
とかどうでしょう？

**Comment by ban-masa** [comment]
@pazeshun topic名については了解しました。ただ関節角については少なくともangle-vectorは度で表記されているようなので度のままのほうがよいのではないかと思うのですがどうでしょうか。

**Comment by pazeshun** [comment]
@ban-masa 
なるほど。baxterのROS nodeにおいては、角度は全てラジアンで扱われている気がするので、euslisp上で変換が行われているということみたいですね。ROSレベルでは揃えたほうがいい気もしましたが、euslisp上で度からラジアンに変換→Arduino上でラジアンから度に再変換というのは効率が悪いので、確かによくないですね。
度のままでいいと思います。

回転の方向を他関節と揃えることと、中心を0度にするということだけ、よろしくお願いします。

**Comment by ban-masa** [comment]
@pazeshun topic名および中心を０度にするという対応を行いました。回転方向ですが一つ前の関節は回転軸の向きが一致していないので２つ前の関節の回転方向に合わせました。あとbaudrateは115200にしてあります。
https://github.com/ban-masa/jsk_apc/blob/devel/arduino/jsk_2016_01_baxter_apc/firmware/arm_manager.ino

**Comment by k-okada** [comment]
urdfやtfと将来的に繋げることを考えるとdegreeにしておいて，eusで扱うときに変換するのがいいかな．ムダにはみえるけど．

--
◉ Kei Okada


2016-04-08 15:40 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by pazeshun** [comment]
@k-okada 
えっと、ラジアンにしておいて、eusで扱うときにdegreeに直すってことですか？

**Comment by pazeshun** [comment]
@ban-masa 
このファームウェアってもう書き込んであるんでしたっけ？もしそうなら、 #1242 のbaudrateを変更して、mergeしてもらおうと思うのですが。

**Comment by pazeshun** [comment]
[arm_manager.ino](https://github.com/ban-masa/jsk_apc/blob/devel/arduino/jsk_2016_01_baxter_apc/firmware/arm_manager.ino)という名前はわかりにくいので、gripper_front_manager_right.inoとかに名前を変更するといいのではないでしょうか。

僕は、firmwareがArduinoスケッチのままでもいいと思っているので、Pull Requestを送るべきではないでしょうか。

**Comment by ban-masa** [comment]
@pazeshun baudrateは115200でいいですよね？角度をラジアンにする件と、ファイル名の件は了解しました。

**Comment by pazeshun** [comment]
@ban-masa 
baudrateは115200で大丈夫です。
お願いします。

**Comment by ban-masa** [comment]
@pazeshun firmwareをmergeしてもらいました

**Comment by pazeshun** [comment]
目標を達成しました。基板再設計とfirmwareをCMake Build systemで管理する件については、左手分を作るときに考えます。
