### ISSUE TITLE
新グリッパーのmain.launchへの組み込み

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1224]
新グリッパーがmain.launchから使えるようにする。
具体的な方法がまだあいまいなので、決まり次第実行する。

Assignee: @start-jsk/jsk_apc-gripper

**Comment by pazeshun** [comment]
Please assign @ban-masa

**Comment by pazeshun** [comment]
Please assign @pazeshun

**Comment by pazeshun** [comment]
Please unassign @pazeshun.
Sorry for confusing.

**Comment by pazeshun** [comment]
@k-okada 
現在、新グリッパーの可動機構を動かした際にEuslisp上でのend-coordsの位置も変更されるようなプログラムを考えています。とりあえずは、robot-interfaceクラスの関節数等は変更せず、グリッパーの角度を変更するたびにend-coordsの位置を変更するものを考えていますが、逆運動学においてグリッパー部分の関節を使えない上、計算誤差の蓄積が心配です。
できればrobot-interfaceクラスの変更を行いたいところなのですが、変更の仕方とかがよくわかりません。pr2eusのrobot-interface.lまでさかのぼったのですが、end-coordsの定義場所がよくわかりませんでした。何か資料等あれば、お教えいただけると幸いです。

**Comment by pazeshun** [comment]
```lisp
(setq end-coords (send robot :rarm :end-coords))
(setq l1 (send end-coords :parent))
(send l1 :dissoc end-coords)
(setq b2 (make-cube 40 40 200))  ;;gripper部分のうち、Baxterのアームに固定された部分
(send b2 :locate (send end-coords :transform-vector #f(0 0 100)))
;;ここでb2の姿勢をend-coordsに合わせたいが、方法がわからない
(send l2 (instance bodyset-link :init (make-cascoords) :bodies (list b2) :name 'l2))
(setq b3 (make-cube 40 40 100))  ;;gripper部分のうち、サーボモータより先の部分
(send b3 :locate (send end-coords :transform-vector #f(0 0 250)))
;;ここでb3の姿勢をend-coordsに合わせたいが、方法がわからない
(send l3 (instance bodyset-link :init (make-cascoords) :bodies (list b3) :name 'l3))
(send l1 :assoc l2)
(send l2 :assoc l3)
(send end-coords :newcoords (make-coords :pos #f(0 0 300)))
(send l3 :assoc end-coords)
(setq j1 (instance rotational-joint :init :name 'j1 :parent-link l2 :child-link l3 :axis :y :min -90 :max 90))
(pushback (send robot :links) (list l2 l3))
(pushback (send robot :joint-list) (list j1))
```
のような流れで可能なのでしょうか？

**Comment by k-okada** [comment]
end-coords は
https://github.com/jsk-ros-pkg/jsk_robot/pull/587
でyamlで指定してurdf->eus変換時に作っています．

で，今回はurdfには無い関節を作ったということなので，
簡単にはその関節の部分のモデルをeusでつくって，
現状のbaxterロボットに追加して，end-coordsを一旦parentからdissocして
また，assocしなおす，というのがいい気がします．

まずは，作ったグリッパのモデルをmake-cube とか joint とか bodyset-linkをつかって作ってみましょう．（講義でやったよね？）




--
◉ Kei Okada


2016-04-09 13:35 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by k-okada** [comment]
はい．send b2 :move-to l1 :world で移動できるかな

--
◉ Kei Okada

**Comment by pazeshun** [comment]
なるほど。つまり、baxter-interfaceクラスのinitと、baxter-robotクラスのinitそれぞれにおいて、
```lisp
(setq end-coords (send robot :rarm :end-coords))
(setq l1 (send end-coords :parent))
(send l1 :dissoc end-coords)
(setq b2 (make-cube 40 40 200))  ;;gripper部分のうち、Baxterのアームに固定された部分
(send b2 :move-to l1 :world)  ;;まず姿勢をl1とend-coordsに合わせる
(send b2 :locate (send end-coords :transform-vector #f(0 0 100)))  ;;位置を合わせる
(send l2 (instance bodyset-link :init (make-cascoords) :bodies (list b2) :name 'l2))
(setq b3 (make-cube 40 40 100))  ;;gripper部分のうち、サーボモータより先の部分
(send b3 :move-to l1 :world)  ;;まず姿勢をl1とend-coordsに合わせる
(send b3 :locate (send end-coords :transform-vector #f(0 0 250)))  ;;位置を合わせる
(send l3 (instance bodyset-link :init (make-cascoords) :bodies (list b3) :name 'l3))
(send l1 :assoc l2)
(send l2 :assoc l3)
(send end-coords :newcoords (make-coords :pos #f(0 0 300)))
(send l3 :assoc end-coords)
(setq j1 (instance rotational-joint :init :name 'j1 :parent-link l2 :child-link l3 :axis :y :min -90 :max 90))
(pushback (send robot :links) (list l2 l3))
(pushback (send robot :joint-list) (list j1))
```
みたいにジョイントとリンクを追加すれば良いということでしょうか

**Comment by pazeshun** [comment]
`send b2 :move-to l1 :world`だと、座標も移動しちゃいますよね？できれば、姿勢だけコピーできると嬉しいのですが・・・。

**Comment by pazeshun** [comment]
理解しました。

**Comment by pazeshun** [comment]
つまり、baxter-interfaceクラス(*ri*のクラス)のinitと、baxter-robotクラス(*baxter*のクラス)のinitのそれぞれにおいて、
```lisp
(setq end-coords (send robot :rarm :end-coords))
(setq l1 (send end-coords :parent))
(send l1 :dissoc end-coords)
(setq b2 (make-cube 40 40 200))  ;;gripper部分のうち、Baxterのアームに固定された部分
(send end-coords :newcoords (make-coords :pos #f(0 0 100)))  ;;end-coordsをb2の中心予定位置にセット
(send b2 :move-to end-coords :world)  ;;end-coordsと同じ位置姿勢にb2をセット
(send l2 (instance bodyset-link :init (make-cascoords) :bodies (list b2) :name 'l2))
(setq b3 (make-cube 40 40 100))  ;;gripper部分のうち、サーボモータより先の部分
(send end-coords :newcoords (make-coords :pos #f(0 0 150)))  ;;end-coordsをb3の中心予定位置にセット
(send b3 :move-to end-coords :world)  ;;end-coordsと同じ位置姿勢にb3をセット
(send l3 (instance bodyset-link :init (make-cascoords) :bodies (list b3) :name 'l3))
(send l1 :assoc l2)
(send l2 :assoc l3)
(send end-coords :newcoords (make-coords :pos #f(0 0 50)))
(send l3 :assoc end-coords)
(setq j1 (instance rotational-joint :init :name 'j1 :parent-link l2 :child-link l3 :axis :y :min -90 :max 90))
(pushback (send robot :links) (list l2 l3))
(pushback (send robot :joint-list) (list j1))
```
のような流れで新たなリンクと関節をセットしてやればよいということでしょうか。

**Comment by k-okada** [comment]
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/baxter.l#L8
みたいに，baxter-robotを継承したロボットを作って
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc/baxter-interface.l#L27
でロボットのクラス名をわたしてあげればいいともいます
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-interface.l#L17
でbaxter-robotとあるけど，これがbaxer-robotになるか，jsk_2015_05_baxter_apc::baxter-robotになるかチョットわからないんだけど（eusのnamespaceは今ひとつ整理されていない気がする）
だめだったら，keyword引数で変えられるようにbaxtereus/baxter-interfaceを直してあげるのかな．

**Comment by pazeshun** [comment]
今気づいたのですが、このグリッパー部分のジョイントの状態は/robot/joint_statesに流れないです。それでも大丈夫なのでしょうか。状態自体はROSのtopicに流れているのですが、/robot/joint_statesとはレートも違うので、できれば別処理したいのですが。

**Comment by pazeshun** [comment]
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-interface.l#L17
のbaxter-robotというのは、require文から判断すると、https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter.lにあるbaxter-robotであると思います。

**Comment by pazeshun** [comment]
joint trajectory actionにもグリッパー部分は入ってないし、逆運動学に使うのはかなり雲行きが怪しくなってきたように思います。
先ほどのプログラムから、
```lisp
(pushback (send robot :links) (list l2 l3))
(pushback (send robot :joint-list) (list j1))
```
を抜いて、l2, l3, j1をslot変数として保持できるようにすれば、:angle-vector で動かされる関節にはj1は入らないが、j1を動かすとend-coordsの位置が変わる、みたいなことができるのでしょうか

**Comment by pazeshun** [comment]
あ、ダメっぽいですね。リンクが辿れなくなっちゃうんですね

**Comment by pazeshun** [comment]
jsk_2016_01_baxter_apc::baxter-interfaceクラス(*ri*のクラス)と、jsk_2016_01_baxter_apc::baxter-robotクラス(*baxter*のクラス)のslot変数としてl2, l3, j1, _end-coordsを保持し、それぞれのinitで、
```lisp
(setq end-coords (send robot :rarm :end-coords))
(setq b2 (make-cube 40 40 200))  ;;gripper部分のうち、Baxterのアームに固定された部分
(send end-coords :locate #f(0 0 100))  ;;end-coordsをb2の中心予定位置にセット
(send b2 :move-to end-coords :world)  ;;end-coordsと同じ位置姿勢にb2をセット
(send l2 (instance bodyset-link :init (make-cascoords) :bodies (list b2) :name 'l2))
(setq b3 (make-cube 40 40 100))  ;;gripper部分のうち、サーボモータより先の部分
(send end-coords :locate #f(0 0 150))  ;;end-coordsをb3の中心予定位置にセット
(send b3 :move-to end-coords :world)  ;;end-coordsと同じ位置姿勢にb3をセット
(send l3 (instance bodyset-link :init (make-cascoords) :bodies (list b3) :name 'l3))
(send end-coords :locate #f(0 0 50))  ;;end-coordsを最終的な位置にセット
(setq l1 (send end-coords :parent))
(setq _end-coords  (make-cascoords))
(send _end-coords :move-to end-coords :world)  ;;end-coordsと同じ位置に、グリッパーのサーボと連動する_end-coordsを作成
(send l1 :assoc l2)
(send l2 :assoc l3)
(send l3 :assoc _end-coords)  ;;_end-coordsの方をassoc
(setq j1 (instance rotational-joint :init :name 'j1 :parent-link l2 :child-link l3 :axis :y :min -90 :max 90))
```
としておき、グリッパー部分のサーボを動かすときは、
```lisp
(send j1 :joint-angle 90)
(send (send robot :rarm :end-coords) :move-to _end-coords :world)
```
とかすれば、逆運動学等はそのままに、サーボを動かすとend-coordsが動くという動作を実現できると思います。

**Comment by k-okada** [comment]
> 今気づいたのですが、このグリッパー部分のジョイントの状態は/robot/joint_statesに流れないです。それでも大丈夫なのでしょうか。状態自体はROSのtopicに流れているのですが、/robot/joint_statesとはレートも違うので、できれば別処理したいのですが。

これは，/gripper/joint_states みたいなものに流しておけば良くて，あとはURDFに該当する関節をいれると
robot_state_publisherが tf を出してくれます．

**Comment by k-okada** [comment]
とりあえずjoint_trajectory_action やjoint_statesを忘れて，baxterのeusモデル上やりたいことはなんだろう

- end-coordsはグリッパ関節の角度に合わせて移動して欲しい
- :anlge-vector した時にはグリッパ関節は含まあれないで欲しい
- send *baxter* :rarm :gripper :joint-angle 20 でグリッパ関節が動いて欲しい

とかかな．

**Comment by pazeshun** [comment]
だいたいそのとおりです。
最後の一つのメソッド名等はまた考えなければならないのかもしれませんが。
とりあえず、それらを実現するためのプログラムとして、最後に上げたものを作ってみました。

**Comment by pazeshun** [comment]
> これは，/gripper/joint_states みたいなものに流しておけば良くて，あとはURDFに該当する関節をいれると
> robot_state_publisherが tf を出してくれます．

こういう情報って、どこかに資料としてあるのでしょうか？勉強不足で知りませんでした。Baxterだと、全体のjoint_statesは/robot/joint_statesに流れてると思うのですが、/robot以下に置かなくて大丈夫なのでしょうか。

**Comment by pazeshun** [comment]
@wkentaro に助言をいただき、方針が定まりました。

1. まず新グリッパーを含めたURDFファイル(xacro)を作る(どうせ認識系で必要になるから)
2. URDFからEusモデルに出力(これで`*baxter*`の方は完成)
3. gripper用のjoint trajectory action serverを作成。また、gripperの関節角をjoint_statesに流すプログラムの作成
3. `*ri*`について、gripper用のjoint trajectory action serverを登録
早く動かすことにこだわらず、結果的な時間短縮を目指します。

**Comment by pazeshun** [comment]
3を @ban-masa に担当してもらう間に、 @pazeshun が1と2をやるみたいな順序でやります。

**Comment by ban-masa** [comment]
@pazeshun 
https://github.com/ban-masa/jsk_apc/tree/devel/gripper_server/jsk_2016_01_baxter_apc/src
joint trajectory action serverとjoint_states_publisherを書きましたが、どうやってテストすればいいでしょうか。

**Comment by ban-masa** [comment]
#1292

**Comment by pazeshun** [comment]
#1286

**Comment by pazeshun** [comment]
次のPRでLispプログラムを編集し、 #1286 #1292 で動かなくなったLispプログラムを修正します。

**Comment by k-okada** [comment]
現状でもeusが動くようにしておきたいので，この状態でrosbag record /robot/joint_states
とかして，eusへの入力データを取っみて下さい．デバッグします．

--
◉ Kei Okada

**Comment by pazeshun** [comment]
@ban-masa
よろしくお願いいたします

**Comment by pazeshun** [comment]
@ban-masa
gripperのjoint trajectory actionのことを完全に忘れていましたが、いつでもいいので、それを追加したPRを作成してくれませんか？
それがないと、いざeuslispからgripperを動かそうとなった時に困るので。

**Comment by ban-masa** [comment]
@pazeshun #1292 にaction serverを追加したものという認識で合ってますか？

**Comment by pazeshun** [comment]
@ban-masa 
PR分けてもいいですが、めんどくさいのでそれでいいと思います。

**Comment by ban-masa** [comment]
@pazeshun 自分が今切ってるbranch的に分けたほうが楽なので、そっちでもいいですか？

**Comment by pazeshun** [comment]
了解です。おねがいします。

**Comment by ban-masa** [comment]
#1296

**Comment by pazeshun** [comment]
#1308 で新作グリッパーをEuslispから動かせるようになりました。
とりあえず、組み込みそのものはできたということで、このissueを閉じます。
今後は、個別の問題ごとにissueを立てて対処します。
