### ISSUE TITLE
Graspability Definition for APC2015 objects

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1225]
Define Graspability : Level 1-4

Graspability|Description
------|------
**4**|Unable to grasp 
**3**|Difficult to grasp <br> Need complex grasp planning
**2**|A little Difficult to grasp <br> Need idea to grasp but not complex
**1**|Easy to grasp

cc. @pazeshun

**Comment by wkentaro** [comment]
creating data in process https://github.com/wkentaro/20160405_vacuum2015_graspability

**Comment by pazeshun** [comment]
ok. I'll make the data.

**Comment by knorth55** [comment]
#1227

**Comment by wkentaro** [comment]
Is this done?

**Comment by pazeshun** [comment]
I think this is done for objects of 2015, but not done for objects of 2016.
I will open new issue for objects of 2016, so it's ok to close this issue.

**Comment by wkentaro** [comment]
I see.
