### ISSUE TITLE
CREATIVE cameraの固定台の再設計

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1243]
#1196 のようにCREATIVE cameraを腕に取り付けていたが、位置が後ろだと腕の前リンクにカメラのコードが干渉し、
![1460026776906](https://cloud.githubusercontent.com/assets/14994939/14349079/7194982c-fcfb-11e5-9b97-61adc3be27c6.jpg)
位置が前だと掃除機のホースとカメラが干渉することが明らかになった。現在は、グリッパー側にカメラを仮止めしている。
![1460026766204](https://cloud.githubusercontent.com/assets/14994939/14349103/a41f2a82-fcfb-11e5-97ec-fce8dd4ba266.jpg)
この位置にカメラを固定するならば、グリッパーと一体型のカメラ固定台を作るとよいので、そのようにグリッパーを再設計する。

**Comment by pazeshun** [comment]
Please assign @pazeshun

**Comment by pazeshun** [comment]
このissueは0.4のmilestoneとは関係ないので、milestoneを変更しました。

**Comment by wkentaro** [comment]
milestoneリストを更新したので、どれか割り振ってください。
1.0: 30pt
2.0: 50pt
3.0: 80pt
4.0: 100pt
5.0: 120pt

**Comment by pazeshun** [comment]
今設計中です。一週間後をめどに左手側で新しいグリッパーを装着できるように作業しています。

**Comment by pazeshun** [comment]
できました。
![dsc_0370](https://cloud.githubusercontent.com/assets/14994939/15892804/e77b9e6e-2db6-11e6-8af5-0e669cfcddba.JPG)
カメラとの固定は、カメラに付属しているネジを使って行っていますが、カメラの筐体にきってあるメネジの強度が不安なので、両面テープも使う予定です。
また、取り付け作業中に落下させてしまった際、以下のように破損しました。
![dsc_0369](https://cloud.githubusercontent.com/assets/14994939/15892879/4c064a1e-2db7-11e6-8817-dd5e6768b5d7.JPG)
とりあえず瞬間接着剤で補修しました。補修したものでbaxterへの導入を進めつつ、設計を見直して強度を高めます。
このissueの目的は達成したので、閉じます。
