### ISSUE TITLE
新作グリッパーの手先サーボ加熱の防止

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1297]
これから新作グリッパーの手先サーボを使用するにあたり、トルクONのまま長時間無理な角度を保ち続けると、サーボが過熱して壊れるのではないかと気づいた。これをfirmwareか周辺プログラムかで防止したい。

Please assign @ban-masa

**Comment by pazeshun** [comment]
#1224 を実現するにあたり、必須かもしれません。

**Comment by ban-masa** [comment]
firmware側で一定時間以上無理な角度を取れないようにするとかでしょうか。ただarduinoが勝手にservoのトルクをoffにしてしまうのもそれはそれであまり良くないような気がします。

**Comment by pazeshun** [comment]
勝手にトルクoffにするけど、角度指令が来たらトルクonにするとかでしょうか・・・
何らかの形では入れるべきだとは思うのですが、いい案が思いつきません。

**Comment by pazeshun** [comment]
@ban-masa 
#1327 用のノードプログラムを考えていて、このissueを解決するための機能もそのノードに組み込めばよいのではないかと気が付きました。
つまり、`gripper_front/limb/right/servo/angle`topicをそのノードもsubscribeしておき、`robot/state`でrobotがenableになっている状態で一定時間以上角度指令がこなかったら、`gripper_front/limb/right/servo/torque`にfalseを流してサーボのトルクを切るという風なノードを作ればよいということです。もちろん、`robot/state`でrobotがdisableになっているときは、`gripper_front/enable`にfalseを流してArduinoの働きを止めます。
これなら、Arduinoのfirmwareは最小の改修ですみ、拡張性が豊かになるように思うのですが、どうでしょうか。

**Comment by pazeshun** [comment]
#1331

**Comment by ban-masa** [comment]
その場合、このissueに関連してはarduinoのfirmwareには手を加える必要がないという認識で合ってますか？

**Comment by pazeshun** [comment]
はい、そうです

**Comment by pazeshun** [comment]
#1331 で解決できることを実機で確認しました。
