### ISSUE TITLE
把持したオブジェクトを検知できない

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1320]
```
[ INFO] [1461232552.751566268]: [main] :larm, :verify_object
[ INFO] [1461232552.751634314]: [main] arm: :larm graspingp: t
[ INFO] [1461232554.417892264]: [main] :rarm, :verify_object
[ INFO] [1461232554.417989916]: [main] arm: :rarm graspingp: t
[ INFO] [1461232568.198510906]: [main] arm: :larm, detect no object in hand with vision
[ INFO] [1461232568.374041057]: [main] :larm, :pick_object
[ INFO] [1461232568.378236550]: [main] Recognizing objects in bin
[ INFO] [1461232569.875262328]: [main] arm: :rarm, detect no object in hand with vision
[ INFO] [1461232570.351793628]: [main] :rarm, :pick_object
[ INFO] [1461232570.363007928]: [main] Recognizing objects in bin
```
このようになり、物体がとれているのに認識できていません。このあと吸引が切れて、グリッパーが再度棚に向かっていきます。

**Comment by wkentaro** [comment]
考えられる原因

* 手先位置の定義が間違っている (robot_self_filterで物体点群が消される)
* kinect2_torsoの位置がずれている
* kinect2_torsoの点群センシング速度が遅い
* kinect2_torsoの点群処理速度が遅い

**Comment by pazeshun** [comment]
左手も反応しないので、1番の可能性は低い気がしていますが、新グリッパーの方のセルフフィルターはダメかもしれないので、確認します

**Comment by pazeshun** [comment]
setup_torso.launchを見ていたところ、新グリッパーではAttentionClipperから正常に作動しないことがわかりました。
正常に作動させるためには認識プログラムに与える引数を色々調整する必要がありそうですが、プログラムの理解と変更に時間がかかりそうなので、認識はとりあえずおいておいて、より多くの物体をつかめるような改善を優先した方がいい気がしてきました。
つまり、gripper班のmilestoneを目標点数にするのではなく、目標物品把持個数にした方がよいのではないかという話です。
皆さんどう思われますか。

**Comment by yuyu2172** [comment]
> つまり、gripper班のmilestoneを目標点数にするのではなく、目標物品把持個数にした方がよいのではないかという話です。
そのとおりだと思います。
物品がなにかと、棚の中での位置姿勢などを変えても掴める場合を増やしてもらえるといいです。

**Comment by knorth55** [comment]
> つまり、gripper班のmilestoneを目標点数にするのではなく、目標物品把持個数にした方がよいのではないかという話です。
それがいいとおもいます

**Comment by k-okada** [comment]
目標はそれだとして，上手く行っていない時のbagファイルを取って，何が悪いか調べる方法を習得するといいですね．
@wkentaro にbagファイルのとり方を聞いてみて下さい．

--
◉ Kei Okada

**Comment by pazeshun** [comment]
皆さんありがとうございます。
詳しいことはマイルストーンに書きますが、マイルストーン変えようと思います。
また、色々いじる前に現在の失敗してる状態でbag fileとってみたいと思います

**Comment by pazeshun** [comment]
#1329

**Comment by knorth55** [comment]
このissueの終了条件は？

**Comment by pazeshun** [comment]
僕のmilestoneには関係しなくなったので、一旦閉じます。
認識系がAttentionClipperからおかしい話は、新しくissue立て直します。
