### ISSUE TITLE
実務的なコミュニケーションツールについて

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1323]
実務的なコミュニケーションや意思疎通のためにツールを一本化したいと思っています。
実務的な話や意思疎通のためなので頻度が多く整理が煩雑になってしまうためメールはあまり良くないと思っています。
個人的にはJSKの皆に見えるようにSlackのチャネルを作るのがいいと思うんですがどうでしょうか？

**Comment by pazeshun** [comment]
大丈夫です。

**Comment by knorth55** [comment]
和田さんと話をしてそういえばgitterがあることを思い出しました
gitterとslackどちらがいいですか？

**Comment by pazeshun** [comment]
gitterもslackも、メールが来てから反応する気がするので、どっちでもかわらない気がしています。

**Comment by knorth55** [comment]
@ban-masa slack登録してください
@yuyu2172 gitter登録してください

とりあえずgitterはオープンすぎてうっとおしいきもするのでslackでいいのではないかと思っています
「起きろ」とか「いつ研究室くる？」とか「今日○○していい？」とかの連絡をしたいツール（つまりjskメンバーにオープンなlineみたいなの）がいいのでそれはslackなのかなと思って
（というかgitterはどういう時に使うのか使いドコロが未だにわかってません）

**Comment by ban-masa** [comment]
slackって招待されないと登録できない気がするんですが違うんでしょうか？

**Comment by pazeshun** [comment]
JSKのメールアドレスを持っていれば、登録することができたような気がします。

**Comment by pazeshun** [comment]
https://github.com/jsk-ros-pkg/jsk_common#restart-travis-from-slack
のリンクあたりから入るといいと思います。

**Comment by ban-masa** [comment]
ありがとうございます。登録しました。

**Comment by wkentaro** [comment]
ではしばらく
https://jsk-robotics.slack.com/messages/jsk_apc/
で。
