### ISSUE TITLE
非常停止時にグリッパーのサーボのトルクが抜けるようにしたい

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1327]
非常停止スイッチを押してもグリッパーのサーボのトルクが抜けないため、実験中にサーボに無理な負荷がかかることがあった。これを改善したい。
[BaxterのAPI](http://sdk.rethinkrobotics.com/wiki/API_Reference)を読むと、`/robot/state`トピックに、robotがenableかそうでないかや非常停止スイッチが押されたかどうかなどの情報が流れているようだ。このtopicをsubscribeして、グリッパーのサーボモータをenableするかどうかを判断し、`gripper_front/enable`のようなtopicにtrue/falseを送るノードを作り、このtopicをArduinoがsubscribeして、falseが送られてきた場合はtrueが送られるまでサーボモータのトルクを切る、という風なことをすれば、非常停止時にグリッパーのサーボのトルクが抜けるのではないだろうか。

Assignee: @start-jsk/jsk_apc-gripper

**Comment by pazeshun** [comment]
#1297 もそうだが、実験中にグリッパーを壊すリスクを下げるためにも早急にプログラムを作りたい。
@ban-masa どうせこれを直さないことには実験しにくいので、新ノードは僕が作ろうかと考えているのですが、 #1297 と合わせてArduinoのfirmwareの改修をお願いしてもいいですか？

**Comment by pazeshun** [comment]
@ban-masa 
#1297 にも書きましたが、`gripper_front/enable`にtrueが来るまでは一切の働きを止める、すなわち、どんな指令が送られてきてもサーボのトルクが切れたまま内部状態が一切変化しないというのはどうでしょうか。

**Comment by pazeshun** [comment]
#1331

**Comment by ban-masa** [comment]
それで対応します

**Comment by pazeshun** [comment]
#1331 と #1335 で解決しました。
