### ISSUE TITLE
Graspability Definition for APC2016 objects

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1354]
Like #1225 
It isn't in my milestone for now, but what I should do in the near future.

**Comment by knorth55** [comment]
Define Graspability : Level 1-4

Graspability|Description
------|------
**4**|Unable to grasp 
**3**|Difficult to grasp <br> Need complex grasp planning
**2**|A little Difficult to grasp <br> Need idea to grasp but not complex
**1**|Easy to grasp

**Comment by pazeshun** [comment]
@knorth55 Thank you

**Comment by wkentaro** [comment]
This is necessary for version 1.0. Please work on this @pazeshun .

**Comment by pazeshun** [comment]
@wkentaro I'll do this in this week
