### ISSUE TITLE
Calibrating extrinstic parameter of two arm cameras

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1373]
These two look good.

http://wiki.ros.org/industrial_extrinsic_cal
http://wiki.ros.org/visp_camera_calibration/Tutorials/CalibrationExternalCamera

**Comment by knorth55** [comment]
you think calibration now is not good?

**Comment by yuyu2172** [comment]
Does the package calibrate external parameters?

**Comment by yuyu2172** [comment]
Does it calibrate extrinsic parameters?

**Comment by knorth55** [comment]
i don't know much about extrinsic parameter. 
how do you load and use the parameters after the calibration?

**Comment by yuyu2172** [comment]
Use them to precisely model position and pose of cameras.

**Comment by wkentaro** [comment]
Is this still necessary?

**Comment by wkentaro** [comment]
I updated the milestone.
