### ISSUE TITLE
[jsk_2016_01_baxter_apc] Binによってオフセットを変える

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1383]
https://drive.google.com/file/d/0B2trSrh55DvLMGNYcTVkOXZROE0/view
などで、現在はBin c用に合わせてあるオフセットのせいで、グリッパーとBinがぶつかってしまうケースがある。これを治したい。

**Comment by knorth55** [comment]
これはrecognition-bin-boxesでとっている座標がすれているということ？

**Comment by pazeshun** [comment]
@knorth55 
違います。`:ik->bin-entrance`などに与えるオフセットがBin cに最適化されてしまっているので、他のBinにアプローチした時に不都合が生じるということです。
ログをみてもらうとわかりやすいかもしれません。（まだmergeされてませんが）

**Comment by knorth55** [comment]
ログを読みました
binは全て同じ形（正確にはb,e,h,kだけ少しy軸に広い）なのですがそれのoffsetがbin cではよくて他のbinではダメというのはrecognize-bin-boxesの位置がおかしいということではないのですか？
それともikを解く際の経由地点が問題？

**Comment by pazeshun** [comment]
棚の実物は、binによって形が結構違う気がしてて、特に、今まで実験してたBin cはz軸方向に広く、下の方のBinはz軸方向に狭いと思っています。それが原因で、binの中心から何mm下にend-coordsを配置するかというオフセットが一定だと、Binにひっかかると考えていました。
recognize-bin-boxesで得られる結果をまだちゃんとみてなくて、もし各Binのz軸方向の大きさが一定になっているなら大きな問題です。

**Comment by pazeshun** [comment]
試してみました。
```
2.irteusgl$ send *ri* :recognize-bin-boxes
nil
3.irteusgl$ send *ri* :get-val '_bin-boxes
#<hash-table #X168ea590 12/20>
4.irteusgl$ setq bin (send *ri* :get-val '_bin-boxes)
#<hash-table #X168ea590 12/20>
5.irteusgl$ send (gethash :c bin) :dimensions :z
0.2
6.irteusgl$ send (gethash :f bin) :dimensions :z
0.18
7.irteusgl$ send (gethash :i bin) :dimensions :z
0.18
8.irteusgl$ send (gethash :l bin) :dimensions :z
0.2
```
ちゃんと、Binによってz軸方向の大きさが変わっているので、これとグリッパーの寸法に基づいてオフセットを決めればよい気がします。

**Comment by knorth55** [comment]
なるほど、2cmの誤差は大きい感じ？
方針としてはoffsetを固定値から毎回棚の高さとグリッパーの寸法から計算する感じ？

**Comment by pazeshun** [comment]
手首が回転した際に、グリッパーがBinの側面に引っかからないよう、グリッパーを下げすぎてしまっていて、2cmも余裕なかったです。現在は、手首が回転するときは、Binの座標系のx軸を中心としてIKの目標座標系を回転させているので、オフセットが重要になります。

現在の方針としては、とりあえずオフセットをBinの高さとグリッパーの寸法から計算したらうまく動くことをまず確認したいです。それが最も簡単な解決策なので。
その後で、IKの目標座標系を回転によって決めるのではなく、Binの寸法、グリッパーの寸法、Binの位置から計算して決めてみて、うまく行くかどうか試したいと思っています。
後者がうまくいけば、自由度が上がってよりいい気がするので、こちらでPR作るかもしれないです。

**Comment by knorth55** [comment]
了解です

**Comment by pazeshun** [comment]
Closed via #1425
