### ISSUE TITLE
[jsk_2016_baxter_apc] 0.2.5 Milestone Deadline has passed

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1384]
@yuyu2172 @wkentaro 
we should edit deadline to realizable one, when do you prefer?
I prefer this friday, May 6th.
how do you think?

cc. @pazeshun @ban-masa

**Comment by wkentaro** [comment]
I thought I'm not responsibility about the project APC2016, so I can't decide about it.
I have other my own project..

**Comment by knorth55** [comment]
ok thank you

**Comment by yuyu2172** [comment]
I think it is reasonable to set deadline on Friday.

I am going to list functionalities that we need to add. Please comment on these.
necessary:
+ run segmentation on a Softkinetic camera
+ segmentation starts when arm position is ready
+ main.l waits until segmentation finishes
+ use output of SegmentationInBin to tell main.l where to go.

possibly required: 
make segmentation faster. Currently, it takes 30 seconds to

**Comment by knorth55** [comment]
> run segmentation on a Softkinetic camera
> use output of SegmentationInBin to tell main.l where to go

can you try to do these two tasks above? I'm totally agree its necessity.
    
> segmentation starts when arm position is ready

i think segmentation node can run every time, i mean we don't need to start it.
i want to try this

> main.l waits until segmentation finishes

totally agreed, i will do this.

**Comment by knorth55** [comment]
ok, so deadline is this Friday!
