### ISSUE TITLE
[jsk_2016_baxter_apc] 0.2.6 Milestone Deadline has passed

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1385]
@pazeshun @ban-masa 
Deadline has passed!!
We should change it to realizable one.

cc. @yuyu2172 @knorth55

**Comment by pazeshun** [comment]
忘れてました。ありがとうございます。
現在の進捗状況を見ると、 #1382 と #1383 を解決することで右手で届く全Binの中にある物品に対して安定したアプローチができるようになり、そこから物品が実際につかめるかどうかの検証に入る、ということで、実はMilestoneの前段階の状態です。
#1382 と #1383 は今週には解決する（解決しないといけない）ので、そこからは最も物品のPoint Cloudが取れるBinに対してのみ実験を行い、物品のつかみ方を確認します。
5/11までには終わると思っているので、それを期限にしたいと思っています。

**Comment by ban-masa** [comment]
それでいいと思います
