### ISSUE TITLE
IK solution using rotation-axis with degree range

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1386]
```
(send robot :inverse-kinematics 
                    :rotation-axis x 
                    :rotation-axis-range-min 0
                    :rotation-axis-range-max 90)
```

i want to solve inverse-kinematics with x-axis free, but x-axis have range to move.
For example above, axis-x is not totally free, but axis-x can take value in range of 0 - 90 degree.

according to #1380 

cc. @pazeshun

**Comment by knorth55** [comment]
#1380

**Comment by pazeshun** [comment]
@knorth55 
Thank you.


> axis-x is not totally free, but axis-x can take value in range of 0 - 90 degree.

Is this rotation around both y-axis and z-axis?

**Comment by knorth55** [comment]
my image, y-axis and z-axis do not rotate in this case, only x-axis do.

**Comment by wkentaro** [comment]
the joint limit is set in xacro, isn't it? @pazeshun
so :rotaxion-axis :x works, no?

**Comment by pazeshun** [comment]
@wkentaro 
すみませんが日本語で回答します。
新作グリッパーの座標系は、グリッパー関節を90度に曲げた時に旧作グリッパーと平行になるようにしてあります。よって、グリッパー関節を伸ばした場合は、グリッパーのz軸がワールド座標系のx軸と平行になるというのが、最も自然な姿勢です( #1394 の図を見るとわかりやすいかもしれません)。
`:rotation-axis :x`ですと、x軸周りの回転を許可するということですが、その場合、z軸はx軸に垂直な平面上に拘束されます。これですと、結局新作グリッパーの関節は曲がらざるを得なくなり、旧作グリッパーに比べ不利になってしまうということです。

**Comment by wkentaro** [comment]
なるほど。ちなみにこれは、endcoordsの座標系が直感とは違っているということでしょうか。
使いづらいなら自然な方に合わせた方がいいかと思ったのですが、どうでしょうか。

2016年5月3日火曜日、pazeshun<notifications@github.com>さんは書きました:

> @wkentaro <https://github.com/wkentaro>
> すみませんが日本語で回答します。
> 新作グリッパーの座標系は、グリッパー関節を90度に曲げた時に旧作グリッパーと平行になるようにしてあります。よって、グリッパー関節を伸ばした場合は、グリッパーのz軸がワールド座標系のx軸と平行になるというのが、最も自然な姿勢です(
> #1394 <https://github.com/start-jsk/jsk_apc/pull/1394>
> の図を見るとわかりやすいかもしれません)。
> :rotation-axis :x
> ですと、x軸周りの回転を許可するということですが、その場合、z軸はx軸に垂直な平面上に拘束されます。これですと、結局新作グリッパーの関節は曲がらざるを得なくなり、旧作グリッパーに比べ不利になってしまうということです。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1386#issuecomment-216412094>
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
また、いまの状態でも:rotasion-axis :zで旧ロボットモデルのときとほぼ同じ結果を得られるということでしょうか。

**Comment by pazeshun** [comment]
@wkentaro 
人によって考え方は違うとは思いますが、僕は旧グリッパーと新グリッパーの互換性を重要視しています。
新グリッパーが機能的に最も旧グリッパーに近付くのは、グリッパー関節が90度の時です。このときのend-coordsを旧グリッパーに合わせるのが妥当であろうと、僕は考えました。これを変えるとなると、逆運動学の際の目標座標系の変更など、付随する変更が大きすぎるので、無理に変える必要はないと思っています。

すみません、二つ目のコメントの意図がつかめていませんが、:rotation-axis :zにすると、z軸回りの回転は許すということで、左手右手ともに可動域が広がると思いますが、右手のグリッパーはやはり曲がった状態になるとおまうので、相変わらず左手より悪い結果が生まれると思います。

**Comment by wkentaro** [comment]
なるほど。確かに互換性の方がいまの所重要そうですね。

二つ目の方ですが、:rotation-axis で8個目の関節の可動域を使う方法は現状ではないということでしょうか。
rotation-axis :yだとワールド座標系のyの回転を許して上手くいったりはしない？

2016年5月3日火曜日、pazeshun<notifications@github.com>さんは書きました:

> @wkentaro <https://github.com/wkentaro>
> 人によって考え方は違うとは思いますが、僕は旧グリッパーと新グリッパーの互換性を重要視しています。
>
> 新グリッパーが機能的に最も旧グリッパーに近付くのは、グリッパー関節が90度の時です。このときのend-coordsを旧グリッパーに合わせるのが妥当であろうと、僕は考えました。これを変えるとなると、逆運動学の際の目標座標系の変更など、付随する変更が大きすぎるので、無理に変える必要はないと思っています。
>
> すみません、二つ目のコメントの意図がつかめていませんが、:rotation-axis
> :zにすると、z軸回りの回転は許すということで、左手右手ともに可動域が広がると思いますが、右手のグリッパーはやはり曲がった状態になるとおまうので、相変わらず左手より悪い結果が生まれると思います。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1386#issuecomment-216459255>
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by pazeshun** [comment]
> rotation-axis :yだとワールド座標系のyの回転を許して上手くいったりはしない？

これはうまくいくかもしれません。 @knorth55 はどう考えますか？

**Comment by knorth55** [comment]
すみません、`:rotation-axis :x`というのは例示で回転軸については深く考えていませんでした
baxterの今の状況だと`:rotation-axis :y`なのですが変な方向から来ないようにy軸にも(0-90)のような制限を与えたいという話を自分はしていました

**Comment by knorth55** [comment]
@wkentaro how can we do this? i heard you know how to do this.

**Comment by wkentaro** [comment]
Maybe 
```
:inverse-kinematics goal :rthre (deg2rad 60)
```

**Comment by knorth55** [comment]
thx

**Comment by wkentaro** [comment]
And also, you can use null space like this:
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/examples/random-view-hand-pose.l#L45-L49

**Comment by k-okada** [comment]
You can use
https://github.com/euslisp/jskeus/blob/master/irteus/demo/virtual-joints.l


On Monday, 11 July 2016, Kentaro Wada <notifications@github.com> wrote:

> And also, you can use null space like this:
>
> https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/examples/random-view-hand-pose.l#L45-L49
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1386#issuecomment-231698769>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3C6iU95x6YhuakFJw6doD5LfJc1hks5qUhtngaJpZM4IUQBJ>
> .
>


-- 
--
◉ Kei Okada

**Comment by knorth55** [comment]
@wkentaro  does this sample code use null-space optimization? `(> 1 (norm ~~~~))` is just an relaxation of constraint?

**Comment by knorth55** [comment]
@k-okada thank you. add virtual joint, define joint rotation constraint condition and solve inverse-kinematics, it seems useful.
