### ISSUE TITLE
[jsk_2016_01_baxter_apc] message_filters callback problems

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1396]
The problem is that `message_filters` get into callback for several time after starting launch file, but it doesn't get into callback any more.
(actually it gets into callback, but really few frequency like once in 10 minutes)
I debugged it  and found out that `TransformListener` causes this problem.

In the case using both `TransformListener` and `message_filters`, `TransformListener` make its own `Subscriber` in inside process, which conflicts with `message_filters`
A guy in the reference below modify `message_filters`, but this is the last idea i want to choose.
C++ has `tf::MessageFilter`, and jsk users use `tf_listener_singleton` but i could not find good substitute for python.
Do you have any idea or suggestion for this problem?

@yuyu2172 @wkentaro

https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/node_scripts/rbo_segmentation_in_bin_node.py#L18-L43

*Reference*
http://answers.ros.org/question/43088/time-synchronizer-hangs-after-few-messages/

http://answers.ros.org/question/49069/is-there-a-tfmessagefilter-in-the-tf-python-api/

https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_recognition_utils/src/tf_listener_singleton.cpp

**Comment by wkentaro** [comment]
Did you get why TransformListener causes the problem?

2016年5月3日火曜日、Shingo Kitagawa<notifications@github.com>さんは書きました:

> The problem is that message_filters get into callback for several time
> after starting launch file, but it doesn't get into callback any more.
> (actually it gets into callback, but really few frequency like once in 10
> minutes)
> I debugged it and found out that TransformListener causes this problem.
>
> In the case using both TransformListener and message_filters,
> TransformListener make its own Subscriber in inside process, which
> conflicts with message_filters
> A guy in the reference below modify message_filters, but this is the last
> idea i want to choose.
> C++ has tfMessageFilter, and jsk users use tf_listener_singleton but i
> could not find good substitute for python.
> Do you have any idea or suggestion for this problem?
>
> @yuyu2172 <https://github.com/yuyu2172> @wkentaro
> <https://github.com/wkentaro>
>
>
> https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/node_scripts/rbo_segmentation_in_bin_node.py#L18-L43
>
> *Reference*
>
> http://answers.ros.org/question/211815/approximate-time-synchronizer-problem/
>
>
> http://answers.ros.org/question/49069/is-there-a-tfmessagefilter-in-the-tf-python-api/
>
>
> https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_recognition_utils/src/tf_listener_singleton.cpp
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1396>
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by knorth55** [comment]
sorry, i got wrong url
this website below describe the reason.
TransformListener have spin() in inside process, and i thought that cause the problem.
http://answers.ros.org/question/43088/time-synchronizer-hangs-after-few-messages/

**Comment by knorth55** [comment]
and actually this problem does not occur in the case callback process is not heavy.
when the callback process is heavy and slow, i.e. point cloud processing, it may happen.

**Comment by wkentaro** [comment]
Okay, could you please create a simple launch file with a node which consists of TransformListener and message_filters?
It would be help to debug this problem.

**Comment by wkentaro** [comment]
And please open a issue on [jsk-ros-pkg/jsk_recognition](https://github.com/jsk-ros-pkg/jsk_recognition.git)

**Comment by knorth55** [comment]
okay
@yuyu2172 can you make a PR for rbo node?

**Comment by knorth55** [comment]
@yuyu2172 
一時的な解決策としてlistenerをcallbackで毎回宣言して、tfでwaitForTransformを行うことでできるか試してみます
tf2にはwaitForTranformが内のが問題ですがtf2である必要性ってあるんですか？？

**Comment by yuyu2172** [comment]
@knorth55 
Jsk_apc2016_common no longer depends on tf2. Initially, I needed tf2's methods for preprocessing, but the preprocessing currently uses patched ones declared inside of our project.

It would be ok to change from tf to tf2. 


I will send PR.

**Comment by knorth55** [comment]
今日いろいろデバグをしてみたのですがTransformListenerを別ノードで呼んでも解決しませんでした。

https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/node_scripts/rbo_segmentation_in_bin_node.py#L68-L80

`get_spatial_img`などの重い処理（0.5秒くらいかかる）があると`message_filters`のcallbackに入らないようでその原因はよくわかりません。
今一つのノードが大きいので一つ一つの機能に分割してノードを立てること、ポイントクラウドの処理はC++に書き換えることを検討しています。

**Comment by wkentaro** [comment]
スリープが入っているだけでバグを再発できる簡単なサンプルはありますか？

**Comment by knorth55** [comment]
Gistにサンプルをあげました
https://gist.github.com/knorth55/186e8dc5aeb13019ba84bb243926066d

**Comment by wkentaro** [comment]
これは、画像じゃなくてもおこる？

**Comment by wkentaro** [comment]
RGBD画像処理のときだけ？

**Comment by knorth55** [comment]
このgistはなんの処理もしていません
元のファイルはRGBDの処理をしています

**Comment by wkentaro** [comment]
じゃあ入力がstd_msgs/Stringとかでもいい？いまカメラ無いんだけど..

**Comment by knorth55** [comment]
それはまだ試せてません、いまから試してみます

**Comment by wkentaro** [comment]
もしかしたら、PointCloud2メッセージをdeserializeするところでPythonだと時間がかかったりするのかもと思いました。

**Comment by knorth55** [comment]
`sensor_msgs/Image`でも再現出来ました
https://gist.github.com/knorth55/616b10f0cb452624fdce516c1ee07352
https://gist.github.com/knorth55/279c2de0627d5c87fde163d9bc789536
https://gist.github.com/knorth55/35dce54c7aae3d1e3c9b344d07a6bb91

![stop](https://cloud.githubusercontent.com/assets/9300063/15015978/de0fa7d6-1249-11e6-852c-887c59932f7f.png)

**Comment by wkentaro** [comment]
tfやtransform listenerは関係ないということ？
callbackで時間のかかる処理をしてしばらくするとfpsが極端に下がる？

**Comment by knorth55** [comment]
結局そういうことになりました
いろいろデバグして勘違いしていました
fpsがおちていってとまってしまいます

**Comment by knorth55** [comment]
`sensor_msgs/Image`でtopicがでなくなるのは`queue_size`が無駄にでかいのを10くらいに下げると解決しました。
`queue_size`に関してはいろいろ変えて試してどれもRBOのnodeではダメだったのですがもう一度確認してみます

**Comment by wkentaro** [comment]
以下で再現、解決できたかと思います。(headerのついたstringメッセージをqueue_size 100で3トピックの同期処理)
マージされるのは先だと思うので、しばらくC++を使ってやればいいと思います。

Reproducing code:
- https://github.com/wkentaro/jsk_20160505_test_message_filters

Issues
- https://github.com/ros/ros_comm/issues/800

PRs:
- https://github.com/ros/ros_comm/pull/801
- https://github.com/ros/ros_comm/pull/802

**Comment by wkentaro** [comment]
Closed via https://github.com/start-jsk/jsk_apc/pull/1403
