### ISSUE TITLE
[jsk_2016_01_baxter_apc] #1378 のテストで何も調べられていない

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1405]
#1404 を作っていて気がついたが、`:ik->bin-entrance`メソッドにおいて、オフセットをセットした後の`:inverse-kinematics`に`:revert-if-fail nil`を与えているため、逆運動学が収束していなくても必ずangle-vectorが返って来てしまい、 #1378 で加えたテストが必ず成功してしまうのではないだろうか。
修正する必要がある。

**Comment by pazeshun** [comment]
ik->bin-entranceはrevert-if-failがnilだからこそ成立している部分があり、左手で使われている#f(-300 0 50)とかをオフセットにいれると、revert-if-failがtの時はIKが失敗する時がある。
#1378 でテストしているオフセットだと大丈夫かもしれないが、長期的には不安が残る。

**Comment by pazeshun** [comment]
とりあえず、今はIKが成功するオフセットでテストしておけばいいと思ったので、 #1408 の方針で行こうと思います。

**Comment by knorth55** [comment]
solved?

**Comment by pazeshun** [comment]
これは、僕の中でそこまで優先度が高くないので、とりあえず #1408 がマージされたら終わりでいいと思います。
