### ISSUE TITLE
[jsk_2016_01_baxter_apc] tf delay b/w (right|left)_arm_mount and (right|lest)_upper_shoulder

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1410]
I compared `tf_echo` with two different code, one is from `base` to `right_upper_shoulder`, the other is `base` and `right_arm_mount`.
the result  is image below ,and it have around 8 seconds delay.
this is the reason why it cannot get transform from base to softkinetic camera, and cannot display point cloud on rviz.
left arm also have the same problem.

```bash
$ rosrun tf tf_echo base right_upper_shoulder
$ rosrun tf tf_echo base right_arm_mount
```
![tf_echo](https://cloud.githubusercontent.com/assets/9300063/15090689/e8703114-146a-11e6-9b04-5264f1099c7a.png)

I checked `view_frame` and there is a frequency gap between two frames.

![frames](https://cloud.githubusercontent.com/assets/9300063/15090686/e452d500-146a-11e6-897c-47a100ba7a27.png)

**Comment by knorth55** [comment]
Upper : baxter date
Lower : theta date

this delay is because of baxter and theta time gap

![baxter-delay](https://cloud.githubusercontent.com/assets/9300063/15091019/2014a5b8-1476-11e6-9b85-85fae4905d40.png)

**Comment by k-okada** [comment]
please setup ntp client on the theta

--
◉ Kei Okada

**Comment by pazeshun** [comment]
Today, I found this problem on doura because sheeta's time set to baxter.
I did temporary solution.
So don't forget that when we solve this problem.

**Comment by knorth55** [comment]
temporary solved.

**Comment by k-okada** [comment]
2015-05-11, I have re-configured sheeta and doura, now ntp server is set to baxter
```
└─▪ grep -C 2 ^server /etc/ntp.conf
# on 2011-02-08 (LP: #104525). See http://www.pool.ntp.org/join.html for
# more information.
server baxter
#server 133.11.216.214 prefer
#server ntp.nict.jp

```
