### ISSUE TITLE
[jsk_apc2016_common] no documentation for generating rbo trained segmenter

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1412]
@yuyu2172 
add doc about how to generate rbo trained segmenter.
this is not urgent issue.

**Comment by yuyu2172** [comment]
go to rbo_segmentation/data and run download_data.sh.
If data is downloaded, then run ``python train_segmenter.py``.

**Comment by yuyu2172** [comment]
@knorth55 
thank you!
