### ISSUE TITLE
[jsk_2016_01_baxter_apc] 重いものを取った場合、壁に吸い付いていると判定されることがある

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1429]
例を上げる。
ボンドを取った場合、
```
[ INFO] [1462959044.119212687]: arm::rarm Grasped wall so stop-grasp, diff: 62.6979
```
中身入りのCHEEZ-ITを取った場合、
```
[ INFO] [1462953497.494982178]: arm::rarm Grasped wall so stop-grasp, diff: 67.759
```
クレヨンを取った場合、
```
[ INFO] [1462953391.843425377]: arm::rarm Grasped wall so stop-grasp, diff: 62.1083
```

**Comment by pazeshun** [comment]
原因としては、baxterのアームの追従性が悪く、`:real-sim-end-coords-diff`メソッドの実行時に物品を持ち上げきれていないことが考えられる。
試しに、アームを動かさないでボンドを取ってみたところ、
```
25.E1-irteusgl$ send *ri* :real-sim-end-coords-diff :rarm 
12.1776
```
となり、アームを動かしていない状態では問題ないことがわかった。

**Comment by pazeshun** [comment]
解決策として、

- 物品を持ち上げる動作のあとで少し停止し、baxterのアームの追従を待つ
- diffのしきい値を上げる

が考えられる。
後者の解決策を取ることを検討しており、壁を吸った場合はどのくらいのdiffになるのかを実験してから、しきい値を決めるつもりである。

**Comment by pazeshun** [comment]
新しく、ドライバーセットでも同じ現象が起きたが、ログを見ると、
```
[ INFO] [1462965629.336726639]: arm::rarm Grasped wall so stop-grasp, diff: 27.7322
```
となっている。しきい値は60なので、しきい値判定の際の`:real-sim-end-coords-diff`では60を超えていたのに、表示の際の`:real-sim-end-coords-diff`では60を下回っていることになる。
しきい値判定の時の値と表示される値が一致していないことが明らかになったので、前のコメントにおける前者の解決策のほうが有望ではないかと思い始めた。

**Comment by pazeshun** [comment]
再現しなくなった。
とりあえず、このissueの優先度を下げる。

**Comment by pazeshun** [comment]
クレヨンで再現しました。
```
[ INFO] [1462968710.588855966]: arm::rarm Grasped wall so stop-grasp, diff: 67.7871
```
優先度あげます。

**Comment by pazeshun** [comment]
わざと壁に吸い付けてみました。
```
[ INFO] [1463030998.924748587]: arm::rarm Grasped wall so stop-grasp, diff: 105.86 
```
や、
```
[ INFO] [1463032585.209862798]: arm::rarm Grasped wall so stop-grasp, diff: 110.272
```
といったデータが得られました。しきい値を80に設定して試してみようと思います。

**Comment by wkentaro** [comment]
+1

**Comment by pazeshun** [comment]
左グリッパーもわざと壁に吸い付けてみました。
```
[ INFO] [1463034441.512225809]: arm::larm Grasped wall so stop-grasp, diff: 74.3366
```
左手はしきい値をそのままにしたほうが良さそうです。

**Comment by pazeshun** [comment]
クレヨン箱で以下のようなdiffが出ました。
```
[ INFO] [1463035312.256769600]: arm::rarm Grasped wall so stop-grasp, diff: 82.0889
```
しきい値をこれ以上上げたくないので、waitも入れてみようと思います。

**Comment by pazeshun** [comment]
グリッパーを持ち上げる動作のwait-interpolationのあとで、1秒waitを入れてみたところ、右手左手ともに壁と物品を判別できる状態になりました。
最終的に、加えるべき変更点は以下の二点になりました。
- 右手の方のしきい値のみを80に上げる
- グリッパーを持ち上げる動作のwait-interpolationのあとで、1秒waitして、baxterのアームの追従を待つ

**Comment by pazeshun** [comment]
Closed via #1445
