### ISSUE TITLE
Kiva pod pose estimation

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1438]
I'm trying to use ppf matching with pcl.
http://docs.opencv.org/3.0-beta/modules/surface_matching/doc/surface_matching.html

**Comment by knorth55** [comment]
also we can use this ppf matching for objects pose estimation.

**Comment by k-okada** [comment]
this is another idea if ppf does not work well, for me ppf seems too much
for this target and afraid that works very well on complex shape like
dinosaur but nor working well on simple shape like box.
this problem is to find x-y-theta location of the pod, so if we can measure
ONE horizontal edge of the pod , we can determine the position of the pod.
So for example if we have a robot with force/tactile sensor, we can touch
two point of the pod to find the location
I think Mitsubishi is thinking about this approach ->
http://archives.simplelists.com/pickingchallenge2016/msg/3726231 and we
also used this approach for old HRP2 demo, to determin the poisition of the
table.

--
◉ Kei Okada

**Comment by knorth55** [comment]
i thought the same idea for kiva pod pose estimation, and i want to use force/tactile sensor for the calibration.

**Comment by k-okada** [comment]
if we, we need to check the accuracy of the encoder value, we choose this
approach on HRP2 because we know the good accuracy of encoder value.

--
◉ Kei Okada

**Comment by knorth55** [comment]
I will ask someone working on HRP2 to get detailed information.
thank you

**Comment by knorth55** [comment]
@k-okada 
PassThroughとOrganizedMultiPlaneSegmentationをおこなってみましたが複数平面がいろいろな方向に検出されてしまいました
https://drive.google.com/file/d/0B5DV6gwLHtyJTnhiZHRuVWUzLXc/view?usp=sharing

**Comment by k-okada** [comment]
OrganizedMultiPlaneSegmentation のパラメータはなにがあるかな．

--
◉ Kei Okada

**Comment by knorth55** [comment]
`distance_threshold`を大きくすれば穴があっても平面になるかと思ったのですがそうでもなかったです。
`max_curvature`も大きくしてできるだけ平面をとっています
パラメータは色々な値があるので色々調整してみたのですが僕のやるかぎりでは1つの平面としては認識してくれませんでした。

http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_pcl_ros/nodes/organized_multi_plane_segmentation.html
https://github.com/knorth55/jsk_apc/blob/51a78bd19fc18905cb5343d5baa0b87ebd40dfbd/jsk_2016_01_baxter_apc/launch/kiva_pod_estimation.launch

**Comment by k-okada** [comment]
あ，normal を esitimate しているものだと normal が出ないからダメだと思う．
sac segmentation だったらいけないものか．
http://pointclouds.org/documentation/tutorials/planar_segmentation.php

--
◉ Kei Okada

**Comment by knorth55** [comment]
ありがとうございます、試してみます

**Comment by knorth55** [comment]
ためしてみました。

![kiva_planar_extract](https://cloud.githubusercontent.com/assets/9300063/16198480/0dd4f0ae-3741-11e6-8319-81b318772177.png)
![kiva_planar_extract_y](https://cloud.githubusercontent.com/assets/9300063/16198481/0e0e8be8-3741-11e6-9d86-59ee3ba45e05.png)


https://drive.google.com/file/d/0B5DV6gwLHtyJSm5xOUhCUUdWa3c/view?usp=sharing

**Comment by knorth55** [comment]
SAC Segmentationをおこなっても平面だけをだすことはできなかったのですが棚の全面だけは取り出せたのかなと思っているのですがどうでしょうか

**Comment by k-okada** [comment]
この結果はどう見たらいいのかな？
平面の式見たいなのはstdoutなどにでていないかな

--
◉ Kei Okada

2016/06/20 23:47、Shingo Kitagawa <notifications@github.com> のメッセージ:

**Comment by knorth55** [comment]
この結果はsac segmentationが出しているoutput/inliersです
上がSAC segmentation前で、下が処理後の点群になります。
平面にするために間引いてくれている感じがします
![kiva_voxel_color](https://cloud.githubusercontent.com/assets/9300063/16199142/734760be-3743-11e6-8953-599654ca5660.png)
![kiva_plane_color](https://cloud.githubusercontent.com/assets/9300063/16199143/73484e3e-3743-11e6-9ba9-0553cfa38ed0.png)

SAC segmentationが結果として出している`pcl_msgs/ModelCoefficients`は下になります。
```
% rp echo /kiva_sac_segmentation/model -n1
header:
  seq: 260
  stamp:
    secs: 1466435020
    nsecs: 596236000
  frame_id: kinect2_torso_rgb_optical_frame
values: [0.05378835275769234, -0.028681518509984016, 0.9981403350830078, -0.8114551305770874]
---
```

**Comment by k-okada** [comment]
入力をグレー、出力をflat colorで確認しましょう

狙っているのは棚の前面のピターっと出力張り付いている状態です。なの本当はransacで評価するとモデルの平面から+方向と-方向で評価を変えるのがベストになるんじゃないかな

2016年6月21日火曜日、Shingo Kitagawa<notifications@github.com>さんは書きました:

> この結果はsac segmentationが出しているoutput/inliersです
> 上がSAC segmentation前で、下が処理後の点群になります。
> 平面にするために間引いてくれている感じがします
> [image: kiva_voxel_color]
> <https://cloud.githubusercontent.com/assets/9300063/16199142/734760be-3743-11e6-8953-599654ca5660.png>
> [image: kiva_plane_color]
> <https://cloud.githubusercontent.com/assets/9300063/16199143/73484e3e-3743-11e6-9ba9-0553cfa38ed0.png>
>
> SAC segmentationが結果として出しているpcl_msgs/ModelCoefficientsは下になります。
>
> % rp echo /kiva_sac_segmentation/model -n1
> header:
>   seq: 260
>   stamp:
>     secs: 1466435020
>     nsecs: 596236000
>   frame_id: kinect2_torso_rgb_optical_frame
> values: [0.05378835275769234, -0.028681518509984016, 0.9981403350830078, -0.8114551305770874]
> ---
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1438#issuecomment-227169960>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3I5vOI0X61Lxcls5tp7kzZr3cezMks5qNqxEgaJpZM4IcWu4>
> .
>


-- 
--
◉ Kei Okada

**Comment by knorth55** [comment]
やってみました
前面に貼り付いている感じでうまく取れているようです
![kiva_planar_](https://cloud.githubusercontent.com/assets/9300063/16268537/c9d0661a-38c9-11e6-96b3-360be14b14be.png)
![kiva_planar_right](https://cloud.githubusercontent.com/assets/9300063/16268538/c9f781f0-38c9-11e6-9325-5ac6a23fcf10.png)

**Comment by knorth55** [comment]
![kiva_planar_right_1](https://cloud.githubusercontent.com/assets/9300063/16268599/044f445a-38ca-11e6-8ed6-820d3f4c2701.png)

**Comment by knorth55** [comment]
あとはModelCoefficientsでkiva_podの回転がとれているので位置を推定する（？）

**Comment by knorth55** [comment]
![kiva_planar_box](https://cloud.githubusercontent.com/assets/9300063/16294353/1331dcee-395b-11e6-9a7b-e8f5225d3987.png)
![kiva_planar_box_1](https://cloud.githubusercontent.com/assets/9300063/16294354/1334c06c-395b-11e6-9948-55107284cb98.png)

**Comment by knorth55** [comment]
![kiva_planar_line](https://cloud.githubusercontent.com/assets/9300063/16299862/84fbe39e-3977-11e6-86f3-c52b48883395.png)
![kiva_plane_line_2](https://cloud.githubusercontent.com/assets/9300063/16299863/851dc2ca-3977-11e6-96ab-0bc0f0b06165.png)

**Comment by knorth55** [comment]
temporary closed
