### ISSUE TITLE
Demonstration on 2016-05-13

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1452]
Based on discussion in slack https://jsk-robotics.slack.com/archives/jsk_apc/p1463055257000011

## 0.3: RBO segmentation + APC2015 object picking

@yuyu2172 @knorth55 

- 時間: 14:00 - 14:15

## 0.4: Grasping APC2016 objects with New gripper

@ban-masa @pazeshun 

- 時間: 14:15 - 14:30

**Comment by pazeshun** [comment]
on 2015-05-13 or on 2015-05-14?

**Comment by wkentaro** [comment]
oops
 ~~2016-05-12~~ -> 2016-05-13

**Comment by wkentaro** [comment]
@knorth55 @pazeshun @yuyu2172 @ban-masa
Are you ready for today's demo? Or I do some help in this morning.

**Comment by pazeshun** [comment]
gripper-v2 is ready.
The method of demo and caution are on slack

**Comment by wkentaro** [comment]
> The method of demo and caution are on slack

Why slack?

**Comment by pazeshun** [comment]
Just I wrote it first there.
No important reason

**Comment by wkentaro** [comment]
Moved to https://github.com/start-jsk/jsk_apc/issues/1462 #1457
