### ISSUE TITLE
Visualization of segmentation in bin

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1454]
Currently, there is no tool that visualizes segmentation in bin algorithm.
Visualization is necessary in two ways.
1. debugging 
2. demonstration on the Saturday.

I am considering of adding two visualizations.
1. probabilistic heat map of segmentation (how likely each pixel should be assigned to objects)
2. final outcomes (position and pose of the center of the target object)

**Comment by wkentaro** [comment]
maybe You dont need to create new tools, but just publishes it. 
check nodes in jsk_perception for images, and rviz plugins. 
or ask me.

**Comment by wkentaro** [comment]
Possibly below nodes are useful:

> 1. probabilistic heat map of segmentation (how likely each pixel should be assigned to objects)

- [colorize_float_image](http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_perception/nodes/colorize_float_image.html)

> 2. final outcomes (position and pose of the center of the target object)

- [rviz pose_array plugin](http://wiki.ros.org/rviz/DisplayTypes/PoseArray)
- [image_cluster_indices_decomposer](http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_perception/nodes/image_cluster_indices_decomposer.html)
- [label_image_decomposer](http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_perception/nodes/label_image_decomposer.html)
- [draw_rect_array](http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_perception/nodes/draw_rect_array.html)
- [tile_image](http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_perception/nodes/tile_image.html)

**Comment by yuyu2172** [comment]
Thank you!

**Comment by yuyu2172** [comment]
done
