### ISSUE TITLE
[jsk_2016_01_baxter_apc] Merge gripper-v2 into master

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1455]
Now gripper-v2 branch is ready to be merged.
How about master? It's ready to be merged gripper-v2 into? @knorth55 , @yuyu2172 , @wkentaro 
If It's ready, I'll make PR.

**Comment by wkentaro** [comment]
You can just send PR.

**Comment by pazeshun** [comment]
I wanted to decide in which branch I'll fix #1437 and erase wrist rotating when gripper is in bin.
I don't want to resolve conflicts several times.
Now I think I should do those works in gripper-v2 branch.

**Comment by wkentaro** [comment]
? どういう意味でしょう。

**Comment by pazeshun** [comment]
PR送っても、mergeされない状態でgripper-v2で作業しちゃったりすると、そのPRに変更を取り入れる度にmasterとconflictしたりしてめんどくさそうだなと思っただけです。
もうしばらくgripper-v2で作業しようと思っているので、そこまでこのissueは後回しにします

**Comment by wkentaro** [comment]
> そのPRに変更を取り入れる度にmasterとconflictしたりしてめんどくさそうだなと思っただけです。

どちらでもいいですが、別にconflictしても直さなければ面倒くさくないと思います..

**Comment by pazeshun** [comment]
Now gripper-v2 branch isn't ready because of #1456
