### ISSUE TITLE
Demo on 2016-05-13/14: Segmentation in bin (version 0.3)

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1457]
****

- @yuyu2172 @knorth55 
- Time: 14:00 - 14:15

(update by @wkentaro)
*****

work on this branch.
https://github.com/knorth55/jsk_apc/tree/sib-demo

**Comment by knorth55** [comment]
this is temporary branch for demo on 05-13 and  05-14.
it works only with left arm and use segmentation algorithm with kinect2_torso. 

```bash
$ roslaunch jsk_2016_01_baxter_apc baxter.launch
$ roslaunch jsk_2016_01_baxter_apc setup_torso.launch
$ roslaunch jsk_2016_01_baxter_apc segmentation_in_bin.launch json:=$(rospack find jsk_2015_05_baxter_apc)/json/layout_12.json
$ roslaunch jsk_2016_01_baxter_apc main.launch json:=$(rospack find jsk_2015_05_baxter_apc)/json/layout_12.json
```

**Comment by wkentaro** [comment]
duplicate of #1452 ?

**Comment by wkentaro** [comment]
You want to split 0.3 from0.4?

**Comment by knorth55** [comment]
yes

**Comment by yuyu2172** [comment]
finished #1454 #1464.

**Comment by yuyu2172** [comment]
@knorth55 

I rebased knorth/sib-demo and pushed a branch called sib-may-fes to origin.
The branch is ready to run with following code.

```
$ roslaunch jsk_2016_01_baxter_apc baxter.launch
$ roslaunch jsk_2016_01_baxter_apc setup_torso.launch
$ roslaunch jsk_2016_01_baxter_apc segmentation_in_bin.launch json:=$(rospack find jsk_2015_05_baxter_apc)/json/layout_12.json
```

**Comment by wkentaro** [comment]
@knorth55 Is that possible to pick object based on the recognition result of RBO segmentation?

**Comment by yuyu2172** [comment]
@knorth55 
I am not thinking of merging this branch to master in the future.
What do you think?

**Comment by knorth55** [comment]
on `knorth55/sib-demo`, we can pick with rbo segmentation.
i think it's ok to merge this to master branch.

**Comment by yuyu2172** [comment]
@wkentaro 
We are going to merge `sib-may-fes` to master.

**Comment by knorth55** [comment]
@yuyu2172 thank you so much
