### ISSUE TITLE
Demo on 2016-05-13/14: Grasping APC2016 objects with New gripper (version 0.4)

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1462]
@ban-masa @pazeshun

Time: 14:15 - 14:30

Moved from https://github.com/start-jsk/jsk_apc/issues/1452

**Comment by pazeshun** [comment]
The method of demo:
```sh
# on sheeta
$ roscd jsk_2016_01_baxter_apc
$ git checkout gripper-v2
$ catkin bt
$ roslaunch jsk_2016_01_baxter_apc baxter.launch
$ roslaunch jsk_2016_01_baxter_apc setup_torso.launch
$ ssh doura
$ sudo -s
$ roslaunch jsk_2015_05_baxter_apc setup_head.launch
```
```sh
# on sheeta
$ roslaunch jsk_2016_01_baxter_apc main.launch json:=$(rospack find jsk_2015_05_baxter_apc)/json/layout_12.json
# After this, please select Yes in YesNoButton
```

**Comment by pazeshun** [comment]
For now, we can't verify objects in hand. So robot always drops objects after verifying pose.
Also, we don't fix dangerous movement of left arm.

**Comment by wkentaro** [comment]
why not use right only?
why not remove verification?

2016年5月13日金曜日、pazeshun<notifications@github.com>さんは書きました:

> For now, we can't verify objects in hand. So robot always drops objects
> after verifying pose.
> Also, we don't fix dangerous movement of left arm.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1462#issuecomment-218937394>
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by pazeshun** [comment]
> why not use right only?

I want to demonstrate the difference between right and left gripper.

> why not remove verification?

Sorry, I had no time to prepare.

**Comment by pazeshun** [comment]
I made new branch for tomorrow demo.
https://github.com/pazeshun/jsk_apc/tree/demo-2016-05-13
Changes from gripper-v2 branch:
- Move right arm only
- Remove verification and always place objects

**Comment by pazeshun** [comment]
So the method of demo is below:

**Comment by pazeshun** [comment]
Demo is finished
