### ISSUE TITLE
[jsk_2016_01_baxter_apc] Cannot verify objects

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1480]
I and @knorth55 thought this is due to #1456 , but it isn't.

**Comment by wkentaro** [comment]
This was because of upgraded sklearn. https://github.com/jsk-ros-pkg/jsk_recognition/issues/1669
Will be fixed via https://github.com/jsk-ros-pkg/jsk_recognition/pull/1670.
In sheeta, we downgrated sklearn.

**Comment by pazeshun** [comment]
@yuyu2172 In this situation, can RBO run?

**Comment by yuyu2172** [comment]
If you use kinect2, then you can.
