### ISSUE TITLE
Current in-hand object recognition accuracy is low? BoF -> VGG16

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1486]
I tested with apc_object_recognition_bof.pkl.gz and apc_object_recognition_lgr.pkl.gz with 20% data of

- 2015 RBO dataset
- 2015 berkeley dataset
- 2015 jsk20150428 dataset

The result was **52% (0.5244)** with 25 objects.

Test program is here: https://github.com/wkentaro/vgg16/blob/master/examples/apc2015/test_bof.py

**Comment by wkentaro** [comment]
With VGG16 net **91%**
![](https://github.com/wkentaro/vgg16/blob/master/examples/apc2015/plot.png?raw=true)

**Comment by wkentaro** [comment]
![test_300-324_0 88](https://cloud.githubusercontent.com/assets/4310419/15324119/1e86732c-1c80-11e6-8d32-c89e1f7f4a5e.png)

**Comment by wkentaro** [comment]
Will be fixed via https://github.com/jsk-ros-pkg/jsk_recognition/pull/1688

**Comment by wkentaro** [comment]
Updated recognition result:
100 %
<img src="https://cloud.githubusercontent.com/assets/4310419/15448176/7b72120e-1f95-11e6-9982-abedb05a0aaf.png" width="50%" />

88%
<img src="https://cloud.githubusercontent.com/assets/4310419/15448209/45242ccc-1f96-11e6-93e9-37fbdd0e366d.png" width="50%" />

**Comment by wkentaro** [comment]
On Gakka PC (T440p) CPU mode:

Input: /apply_mask_left_hand/output: 2.3hz
output: /vgg16_object_recognitioin/output: 1.1hz

![image](https://cloud.githubusercontent.com/assets/4310419/15457306/8bffedde-20c2-11e6-9e62-c29134ac56d3.png)

**Comment by yuyu2172** [comment]
How slow is it on sheeta?

**Comment by wkentaro** [comment]
0.0000001 hz

**Comment by yuyu2172** [comment]
I wonder why

**Comment by wkentaro** [comment]
I wonder why, too.

**Comment by wkentaro** [comment]
On doura, it is `0.5 hz`.

```
             topic                 rate    min_delta   max_delta   std_dev 
==========================================================================
/apply_mask_left_hand/output       2.756   0.237       0.903       0.189   
/vgg16_object_recognition/output   0.543   1.838       1.842       0.00
```

**Comment by yuyu2172** [comment]
Oh good.
