### ISSUE TITLE
[jsk_2016_01_baxter_apc] move-arm-body->order-bin is too fast

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1497]
In https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L614 , `:fast` key and `:scale` key isn't found.
It sometimes causes too fast movement.

**Comment by pazeshun** [comment]
@wkentaro 
Why is it? To reduce time?

**Comment by wkentaro** [comment]
no reason.

**Comment by pazeshun** [comment]
Ok, I'll fix it.

**Comment by pazeshun** [comment]
Closed via #1499
