### ISSUE TITLE
milestone 0.3.0 finished?

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1509]
RBOのセグメンテーションのプログラムをmain.launchから回して、その認識結果を用いてpickingができたことを確認したのでmilestone 0.3.0のメインの部分は完成しています。
安定的に30点をとるということに関しては確認をしていないのですが、これは次のmilestone 0.5.0に回したいのですがどうでしょうか？

0.3.0が長引いてしまったので0.4.0とほぼ同時になってしまいました。
ここで安定的に30点をとることに固執するとまだまだ長くなってしまいます。
0.3.0はRBOでmain.launchが回りpickingができていることを確認したので終了したいとおもっています。

**Comment by pazeshun** [comment]
main.launchが回るのであれば、私からは異存ありません。
#1470 と #1479 の発生条件を調べてから、 #1455 の通りPRを作ります。

**Comment by yuyu2172** [comment]
> 安定的に30点をとるということに関しては確認をしていないのですが、これは次のmilestone 0.5.0に回したいのですがどうでしょうか？
I agree. This is better because we can aim to achieve the goal using new grippers.
