### ISSUE TITLE
[jsk_2016_01_baxter_apc] recognition_in_hand always succeed in left hand

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1510]
i tried main.launch, and baxter failed to pick objects.
Although there is no object in hand, object recognition program detect target object and try to place in order bin.

**Comment by pazeshun** [comment]
Which hand do you use?
After debugging #1496 , I always got correct results in right hand.

**Comment by knorth55** [comment]
left hand

**Comment by knorth55** [comment]
do you get timeout when there is no object?
that is the problem.

**Comment by pazeshun** [comment]
In right hand, yes, I got timeout.

**Comment by knorth55** [comment]
according to #1496, the main reason was padding, right?
i will check it.

**Comment by pazeshun** [comment]
> according to #1496, the main reason was padding, right?

I think so, too.

**Comment by knorth55** [comment]
the reason was simple. the rubber gripper moved forward and it get outside of robot self filter.
I fixed the rubber gripper and also made self filter bigger
