### ISSUE TITLE
Make Segmentation In Bin Failproof

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1519]
When SIB fails to produce valid target mask (i.e. publishes an image with all zero), the predicted position is dangerous. For example, in the image below, SIB failed and the target position is outside of the target bin.

![screenshot from 2016-05-23 20 39 28](https://cloud.githubusercontent.com/assets/2062128/15469665/bc709cc0-2126-11e6-91fd-e32ea47f134d.png)

**Comment by wkentaro** [comment]
This should be fixed before the demo on 2016-05-27. Please work on this @yuyu2172 .
I think it does not take time.

**Comment by wkentaro** [comment]
Is this done?

**Comment by yuyu2172** [comment]
done.
Sorry for late reply.
