### ISSUE TITLE
RBO segmentation in bin fails to recognize some objects

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1521]
RBO segmentation in bin returned nothing when predicting glasses from the image below.

![screenshot from 2016-05-23 20 50 18](https://cloud.githubusercontent.com/assets/2062128/15469881/18ca5e60-2128-11e6-9e78-3592afd103ea.png)

**Comment by wkentaro** [comment]
Firstly, we need to do some accuracy testing after training the classifier with APC2016 objects after https://github.com/start-jsk/jsk_apc/issues/1423.
