### ISSUE TITLE
2016-05-27/28 Demo

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1524]
2016-05-27 13:35-14:50 APC Demo
詳しくは稲葉先生からのメールをみてください

**Comment by pazeshun** [comment]
左腕が危険な動きをしないようなwork orderにして、右手は新しいグリッパー、認識プログラムは今年用のものでデモをするという感じでしょうか。

**Comment by wkentaro** [comment]
version 1.0でやるつもりがいいかと思います。

**Comment by wkentaro** [comment]
@knorth55 明日少し相談して準備しましょう。

**Comment by knorth55** [comment]
ver 0.8
- object : apc2015
- gripper : gripper2016
- camera : softkinetic
- recognition : SIB + boost of color hist and SIFT in hand
- trust pressure sensor : true

**Comment by wkentaro** [comment]
ver 0.8

- object : apc2015
- gripper : gripper2016
- camera : softkinetic
- recognition : RBO In-Bin Segmentation + VGG16Net In-Hand Object Recognition
- trust pressure sensor : true

**Comment by wkentaro** [comment]
BTW, currently we trust pressure sensor in actual? @knorth55 @pazeshun 
I thought we are using only point cloud for grasp detection.

**Comment by pazeshun** [comment]
We use pressure sensor to detect whether object is grasped or not when trying to pick it.
I think we can't detect this using point cloud only.

**Comment by pazeshun** [comment]
And we don't trust pressure sensor when verifying.

**Comment by wkentaro** [comment]
I see. Thanks.

ver 0.8

- object : apc2015
- gripper : gripper2016
- camera : softkinetic
- recognition : RBO In-Bin Segmentation + VGG16Net In-Hand Object Recognition
- trust pressure sensor:
  - trials in bin: false (n-trials 1)
  - push object in bin: true
  - outside bin: false (use point cloud)

**Comment by knorth55** [comment]
@yuyu2172  `demo.rviz` looks like this.
![demo_viz](https://cloud.githubusercontent.com/assets/9300063/15616599/d55b0926-247f-11e6-9688-175b87c5a53c.png)

**Comment by k-okada** [comment]
nice, can you display any text under each overlayed images to explain what
it is?

--
◉ Kei Okada

**Comment by knorth55** [comment]
how can i write letters on rviz?
do we have to subscribe some topic?

**Comment by wkentaro** [comment]
You can use jsk_rviz_plugins/OverlayText like [here](https://github.com/start-jsk/jsk_apc/blob/master/jsk_2015_05_baxter_apc/node_scripts/visualize_on_rviz.py#L46-L47).
Or [tile_image.py](https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/node_scripts/tile_image.py#L86) to draw topic name.
Or you can create a new node.

**Comment by wkentaro** [comment]
Is this done?

**Comment by knorth55** [comment]
demo is done.
i will update rviz later
