### ISSUE TITLE
[jsk_2016_01_baxter_apc] Build error due to long file name

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1528]
When I building jsk_2016_01_baxter_apc, I get errors like following
```
CMake Error: Cannot open file for write: /home/pazeshun/apc2016/apc_ws/build/jsk_2016_01_baxter_apc/CMakeFiles/_run_tests_jsk_2016_01_baxter_apc_shell-test__home_pazeshun_apc2016_apc_ws_src_start-jsk_jsk_apc_jsk_2016_01_baxter_apc_scripts_euslint__home_pazeshun_apc2016_apc_ws_src_start-jsk_jsk_apc_jsk_2016_01_baxter_apc_euslisp_examples_picking-with-clustering.l.dir/build.make.tmp
CMake Error: : System Error: File name too long
CMake Error: Could not create /home/pazeshun/apc2016/apc_ws/build/jsk_2016_01_baxter_apc/CMakeFiles/_run_tests_jsk_2016_01_baxter_apc_shell-test__home_pazeshun_apc2016_apc_ws_src_start-jsk_jsk_apc_jsk_2016_01_baxter_apc_scripts_euslint__home_pazeshun_apc2016_apc_ws_src_start-jsk_jsk_apc_jsk_2016_01_baxter_apc_euslisp_examples_picking-with-clustering.l.dir/cmake_clean.cmake
```
It is due to long file name.
When I see default limitation of file name length,
```
$ getconf NAME_MAX .
255
$ getconf PATH_MAX .
4096
```
~~I think these have no problems.~~

**Comment by pazeshun** [comment]
I think `_run_tests_jsk_2016_01_baxter_apc_shell-test__home_pazeshun_apc2016_apc_ws_src_start-jsk_jsk_apc_jsk_2016_01_baxter_apc_scripts_euslint__home_pazeshun_apc2016_apc_ws_src_start-jsk_jsk_apc_jsk_2016_01_baxter_apc_euslisp_examples_picking-with-clustering.l.dir` exceeds `NAME_MAX`

**Comment by pazeshun** [comment]
NAME_MAX is fixed by system, so we can't fix this problem.
I'll move work space to upper directory.

**Comment by pazeshun** [comment]
Fixed.

**Comment by k-okada** [comment]
> NAME_MAX is fixed by system, so we can't fix this problem.

how did you 'fixed by system'

**Comment by pazeshun** [comment]
Fixed by Linux kernel, isn't it?
http://serverfault.com/questions/9546/filename-length-limits-on-linux

**Comment by k-okada** [comment]
did you type any command to fix this problem?

--
◉ Kei Okada

**Comment by pazeshun** [comment]
No, I didn't. I just moved work space to upper directory.
