### ISSUE TITLE
SIB does not publish bounding box of objects

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1538]
Currently, SIB only publishes the pose of the target object.
For planning grasping motion, a bounding box around the object is needed.

TODO: add a node that publishes the bounding box

**Comment by wkentaro** [comment]
This can be fixed soon. (I mean before the demo on 5/27)
Please work on this @knorth55 .

**Comment by wkentaro** [comment]
Is this done?

**Comment by knorth55** [comment]
done
