### ISSUE TITLE
Include segmentation_in_bin.launch in setup_softkinetic.launch: one nodelet manager for one sensor

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1544]
@yuyu2172 
Please do this ASAP. It does not take time.

- include segmentation_in_bin.launch
- launch manager in setup_softkinetic.launch

@knorth55 
The softkinetic nodes are not nodelet? If so, please use nodelet.
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/launch/setup_softkinetic.launch#L6

**Comment by wkentaro** [comment]
This should make it easier to run demo.

**now**
```
rl jsk_2016_01_baxter_apc baxter.launch
rl jsk_2016_01_baxter_apc setup_torso.launch
rl jsk_2016_01_baxter_apc setup_softkinetic.launch
rl jsk_2016_01_baxter_apc segmentation_in_bin.launch
rl jsk_2016_01_baxter_apc main.launch json:=...
```

**after**
```
rl jsk_2016_01_baxter_apc baxter.launch
rl jsk_2016_01_baxter_apc setup_torso.launch
rl jsk_2016_01_baxter_apc setup_softkinetic.launch
rl jsk_2016_01_baxter_apc main.launch json:=...
```

**Comment by knorth55** [comment]
`segmentation_in_bin.launch` require json file, so it is better to be included into `main.launch`, isn't it?

**Comment by knorth55** [comment]
softkinetic node is not nodelet, unfortunatelly

**Comment by wkentaro** [comment]
> segmentation_in_bin.launch require json file, so it is better to be included into main.launch, isn't it?

I'm not sure why that is happen. You split the RBO SIB algorithm to some nodes, didn't you?
Why it requies json file? Is that difficult to communicate json info from nodes in main.launch to ones in segmentation_in_bin.launch?

cc @yuyu2172

**Comment by wkentaro** [comment]
> softkinetic node is not nodelet, unfortunatelly

Ok, we should change it to nodelet if we need it.

**Comment by knorth55** [comment]
> I'm not sure why that is happen. You split the RBO SIB algorithm to some nodes, didn't you?
Why it requies json file? Is that difficult to communicate json info from nodes in main.launch to ones in segmentation_in_bin.launch?

in this part, sib uses json
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/launch/segmentation_in_bin.launch#L22-L27

**Comment by wkentaro** [comment]
That part can be moved to main.launch.
