### ISSUE TITLE
gripper2016 use sign: 1 for not tall objects in bin k

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1561]
In PR #1560.
When i tried to pick object with SIB bounding box, the gripper uses sign: 1, and could not pick not tall object.

Segmentation is working proper, and i checked that the gripper can pick not tall object from other bin with sign: 0.
I think it is unique problem for bin k .

**Comment by knorth55** [comment]
I use `layout_11.json`  with right arm, and i got this issue.

**Comment by pazeshun** [comment]
Please tell me size and position of bounding box of objects in bin k

**Comment by knorth55** [comment]
condition is #1560

**Comment by knorth55** [comment]
it was my mistake and fixed #1560
