### ISSUE TITLE
グリッパーのサーボのギアが欠けやすい

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1563]
今日baxterを動かそうとしたら、グリッパーのサーボ内のギアが欠けて動かなくなっていました。
現在使っているサーボモータは、ギアがプラスチック製なので欠けるのは仕方ないと思うのですが、プログラムで回避できるものならしたいので、どんな動作をしたせいで欠けてしまったのか教えてください。

**Comment by pazeshun** [comment]
@k-okada 金属ギアタイプのサーボの取り扱いが復活していました。
http://akizukidenshi.com/catalog/g/gM-01724/
購入できますでしょうか

**Comment by k-okada** [comment]
かいました．

--
◉ Kei Okada

**Comment by pazeshun** [comment]
@k-okada すみません、このissueには関係ないのですが、グリッパーの構成部品ということで、
http://www.amazon.co.jp/%E6%A5%BD%E3%81%97%E3%81%84%E5%B7%A5%E4%BD%9C%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA-No-172-%E3%83%A6%E3%83%8B%E3%83%90%E3%83%BC%E3%82%B5%E3%83%AB%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88L-210%C3%97160mm-70172/dp/B001VZHRYK/ref=sr_1_2?s=hobby&ie=UTF8&qid=1464331556&sr=1-2&keywords=%E3%83%A6%E3%83%8B%E3%83%90%E3%83%BC%E3%82%B5%E3%83%AB%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88
も買えませんでしょうか。このセット1つで現在のグリッパーが2セットできると思います。
他にも、スペーサーとネジ長40〜45mm程度のM3のネジ、M3のナイロンナット、M2.6のネジが必要なのですが、これらはJSKがよく購入している場所から買いたいと思っています。
あとでご相談させてください。

**Comment by k-okada** [comment]
買いました．

--
◉ Kei Okada


2016-05-27 16:12 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by pazeshun** [comment]
ありがとうございます

**Comment by pazeshun** [comment]
各位、baxterを動かす際は、グリッパーのサーボから先の部分のうち、剛性の高い部分に大きな負荷がかかっていないか確認しながら動かしてください。
@knorth55 故障原因の報告をお願いします。

**Comment by knorth55** [comment]
あまり心当たりが無いです
棚の中からでるときに引っかかったのはあったけどそこまで強く引っかかっていることはなかったです。

**Comment by pazeshun** [comment]
@knorth55 ありがとうございます。
#1560 の動画を見ていて、僕のグリッパー動作生成プログラムにミスがあるかもしれないと思いました。それを検証してみます。あと、 #1560 の動画程度でも、たぶん今のサーボは壊れちゃうので、改善されるまでの間注意していただけるとありがたいです。

**Comment by knorth55** [comment]
@pazeshun 了解です
ちなみに#1560 の動画でグリッパーが上からじゃなく前から、sign-y 0でアプローチしてるのは取っているバウンディングボックスの精度が悪いのが原因かな？

**Comment by pazeshun** [comment]
> sign-y 0でアプローチしてるのは取っているバウンディングボックスの精度が悪いのが原因かな？

精度のせいではなく、カメラの向きのせいで、奥行きが長い物品のバウンディングボックスの高さが大きくでるせいだと思います。

**Comment by pazeshun** [comment]
#1560 により、物品の高さが大きく評価されるようになり、本当は位置が低い物品に対して無理やりグリッパーをまっすぐにしてアプローチする傾向にあります。 #1560 の動画では、 これによって無理やりまっすぐアプローチした上に、 #1586 のためグリッパー関節が曲がり、グリッパーのベースとBinの壁が引っかかっています。これによってBaxterの腕関節が目標角度に到達できず、関節トルクが過剰に大きくなり、次の急な動きにつながっているように見えます。
こういうことはこれからも往々にして起きそうなので、何かしらサーボを壊さない対策をしようとは考えてますが、なかなかいい案が思いつかないです。

**Comment by pazeshun** [comment]
サーボを金属ギアタイプに交換しました。だいぶ強度が上がったと思います。グリッパーがBinにあたった状態で、グリッパーをBinに押し付けて強度テストをしてみましたが、サーボのギアが壊れる前にサーボの制御が負けてくれたので、大丈夫だと期待しています。ただし、衝撃荷重などに対する耐性はテストできていません。
また、グリッパー部分にバネ要素をもたせようと試行錯誤しましたが、なかなか難しかったので、一旦あきらめます。
現状考えられるよりよい解決策は、ラジコンサーボではなくデジタルサーボを使うことで、ちょうどよい大きさ、トルクのデジタルサーボが見つかれば、そっちの方向性を探っていきたいと思います。
デジタルサーボを使って根本的に解決するか、現状で満足するかしたらこのissueを閉じます。

**Comment by k-okada** [comment]
2016-05-29 18:47 GMT+09:00 pazeshun <notifications@github.com>:

> これによってBaxterの腕関節が目標角度に到達できず、関節トルクが過剰に大きくなり、
>

これ，−１とかよんでいるやつなんだけど，baxterのjtaは，本当は目標角度に到達しないと，邪魔されている，とおもって，諦めるんだけど
そうすると重いものを持ったりしていると，止まっちゃうので（そうだったっけ？），無理やり目標角度に到達させている，

１） 其の部分どこだっけ＞ @wkentaro
２）
これを外して本当に問題がでるかもう一回確認したい．そして，対象物におうじてきりかえるとか，練習は−１はOFFにして，本番はONとかする，とか考えたい．


--
◉ Kei Okada

**Comment by wkentaro** [comment]
@k-okada 
> １） 其の部分どこだっけ＞ @wkentaro

https://github.com/start-jsk/jsk_apc/blob/master/jsk_2015_05_baxter_apc/config/baxter_joint_trajectory.yaml
これですかね。

**Comment by pazeshun** [comment]
明日、-1をOFFにして試してみようと思います。
デフォルト値だとどの程度の重さの物体を持ち上げられないのかというのと、Binの床を吸ったときどうなるのかを試してみます。
また、-1にはしないけど、閾値を緩くするとどうなるのか試してみます。

**Comment by pazeshun** [comment]
重いもの関連で、ダンベルを持たせてみたら、吸着はできるのですが、baxterの各関節が負荷に耐えられませんでした。
関節がサーボからなじみ動作に切り替わる負荷の閾値とかあるのかもしれませんが、現時点ではダンベルは持てないです。

**Comment by wkentaro** [comment]
まぁ.. ダンベルを持つのはmilestone5.0になりそうですね..
https://github.com/start-jsk/jsk_apc/milestones/5.0:%20120pt



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=www.kentaro.wada@gmail.com&idSignature=22>

2016-06-10 21:23 GMT+09:00 pazeshun <notifications@github.com>:

> 重いもの関連で、ダンベルを持たせてみたら、吸着はできるのですが、baxterの各関節が負荷に耐えられませんでした。
> 関節がサーボからなじみ動作に切り替わる負荷の閾値とかあるのかもしれませんが、現時点ではダンベルは持てないです。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1563#issuecomment-225168071>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHFk2z3DOMgm9Xwxtcf_6up1klcgxB7ks5qKVddgaJpZM4IoMnQ>
> .
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by k-okada** [comment]
2016-06-10 21:23 GMT+09:00 pazeshun <notifications@github.com>:

> 関節がサーボからなじみ動作に切り替わる負荷の閾値とかあるのかもしれませんが、現時点ではダンベルは持てないです。
>
>
これは力が抜けたような感じになるのかな．おもしろいですね．PR2/Baxterをつかっている人はこれが当たり前で，なぜHRP2/Nextageはそうしないのかな，
ともっているわけですが，逆はなぜ脱力するような危ないものをつかっているんだろう，ということですね．うまい落とし所を見つけたいものです．
@mmurooka, @snozawa

--
◉ Kei Okada

**Comment by mmurooka** [comment]
HRP2はモータ温度を直接計測できる脚関節については，
温度が一定値（現状は50度）を越えたら，サーボOFFする（サーボゲインを落とす）ようにしています．
https://github.com/start-jsk/rtmros_hrp2/pull/302

**Comment by k-okada** [comment]
で，それより重いものを持ち上げるにはどうしたらいいでしょうね．という話でした．

--
◉ Kei Okada

**Comment by pazeshun** [comment]
現在このissueで議論されている問題点を #1711 に移動しました。
金属ギアにしてからギアが欠けたことはないので、とりあえずこのissueは閉じます
