### ISSUE TITLE
Mismatch between Dist/Height images and RGB image

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1576]
![dist_only](https://cloud.githubusercontent.com/assets/2062128/15625837/a7bbfb8a-24f0-11e6-852a-c535ef8de703.jpg)

The image was visualized using #1577.

**Comment by knorth55** [comment]
fixed via https://github.com/knorth55/softkinetic/commit/55061fca79d69b46fe33556938ddc9a80cadbe7b

**Comment by knorth55** [comment]
better segmentation result!
![sib_fix](https://cloud.githubusercontent.com/assets/9300063/15628905/dea61a4c-2548-11e6-81d7-478c08f8352a.png)

**Comment by yuyu2172** [comment]
update

![frame0000](https://cloud.githubusercontent.com/assets/2062128/15649518/14adaf5a-26ad-11e6-9538-2d38ee609405.jpg)

**Comment by wkentaro** [comment]
nice work, both! @knorth55 @yuyu2172 👍
