### ISSUE TITLE
If rbo_segmentation_in_bin_node returns nothing, the robot motion stops

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1587]
Thanks to #1523 , we can prevent unexpected movement of the robot.
But if rbo_segmentation_in_bin_node returns nothing, the robot motion may stop.
The reason of this is on https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L244-270 which shows `:recognize-objects-segmentation-in-bin` doesn't finish until messages come from both of `box-topic` and `com-topic`.

I think we have two solutions:
1. Fix `baxter-interface.l` to use `one-shot-subscribe` and timeout in `:recognize-objects-segmentation-in-bin`
2. Fix `rbo_segmentation_in_bin_node.py`
I think the latter solution is better because `:recognize-objects-in-bin` uses the same program as current `:recognize-objects-segmentation-in-bin` to get messages. I don't know much about `:recognize-objects-in-bin` and topics subscribed by it, but `:recognize-objects-in-bin` returns even though no object is found.
@knorth55 @yuyu2172 What do you think?

**Comment by knorth55** [comment]
!. `one-shot-subscribe` is not good because it subscribe two msg in the same time.

**Comment by knorth55** [comment]
2. is not good
3. i will add timeout method in `main.l`

**Comment by pazeshun** [comment]
@knorth55 It's up to your choice

**Comment by k-okada** [comment]
i think one-shot-subscribe is not a good usecase ,because. we do not have
similar usage on rospy/roscpp

add subscriber and set recognition result global variable
start_stamp = current ros time
while timeout; do
  if start_time < global_variable.header.stamp ;; check if global variable
is updated,
    process_new_message_arrived
done

--
◉ Kei Okada
