### ISSUE TITLE
 Objects near the back of bins get shaded

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1599]
From https://github.com/start-jsk/jsk_apc/issues/1423#issuecomment-222667607
@ban-masa baxterの腕にライトを追加したいのですが、どういうのがいいと思いますか？

**Comment by pazeshun** [comment]
私は、とりあえずグリッパーサーボの電源に直接繋いだLEDをグリッパー付近に取り付けてみるといいのではと思いますが、配線の問題と現状のACアダプタでは電流足りないかも問題があります。

**Comment by k-okada** [comment]
2016-05-31 22:00 GMT+09:00 pazeshun <notifications@github.com>:

>
> 私は、とりあえずグリッパーサーボの電源に直接繋いだLEDをグリッパー付近に取り付けてみるといいのではと思いますが、配線の問題と現状のACアダプタでは電流足りないかも問題があります。
>

電源は後で考えるとして，LEDつけましょう．USB接続のライトみたいなのが欲しければ教えてください．

--
◉ Kei Okada

**Comment by ban-masa** [comment]
ライトが常時点灯しているという前提ならボタン電池式の小さいLEDライトでもいいような気がします。
ACアダプタから給電する場合でもたぶん電流が足りないということはないと思います。

**Comment by pazeshun** [comment]
ライトつけてみました。
![dsc_0334](https://cloud.githubusercontent.com/assets/14994939/15740179/afd739e0-28ee-11e6-96ae-70bce2c63bb2.JPG)
自転車用のライトで、ゴムで巻き付けるタイプのものです。ライト上部を押すと点灯し、押すごとに点灯モードが変化します。何回か押すと消えます。
自転車の管に比べてBaxterのグリッパーの管は太めなので、ちょっと無理してつけてます。ゴムが切れるかもしれませんが、切れたら両面テープでつければいいかと思います。
ちなみに、ライトつけるのとつけないのとで、明るさには以下のような違いが出ます。
ライトをつけないとき：
![dsc_0337](https://cloud.githubusercontent.com/assets/14994939/15740300/49f23250-28ef-11e6-8d95-dcc62b9e2c4d.JPG)
ライトをつけたとき：
![dsc_0338](https://cloud.githubusercontent.com/assets/14994939/15740305/53ea00e4-28ef-11e6-8aa2-23e31df8ba4d.JPG)
@yuyu2172 明るさが足りなかったりしたら言って下さい。

**Comment by knorth55** [comment]
:+1:

**Comment by pazeshun** [comment]
`:move-arm-body->bin-overlook-pose`で、ライトがBinの中をまんべんなく照らすような位置にグリッパーを持ってくるといいのかもしれませんが、カメラの画角が厳しいみたいなので、無理かもしれません。

**Comment by knorth55** [comment]
あまり解像度がないのでできるだけbinに近づきたいのでカメラ優先の位置でお願いします。
試してみた感じはいいとおもいます

**Comment by pazeshun** [comment]
とりあえず、大丈夫そうなのでcloseします。
問題が発生したらまたopenしてください。
