### ISSUE TITLE
APC旅程ぎめ

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1601]
・誰が行くのか
・いつ行っていつ帰るのか
・大体の旅費
を決めたいと思います。

**Comment by pazeshun** [comment]
Robocup 2016が6/29から7/3ということで、6/26に出発し、7/4に帰ってくるというのはどうでしょうか。

**Comment by pazeshun** [comment]
http://air.his-j.com/fb/shop/airproducts.htm?rd=133000000235476&ts=1464760300
適当に調べてみましたが、乗り継ぎ時間が全体的に長いですね

**Comment by knorth55** [comment]
リクエストはbad request がかえってきます

**Comment by knorth55** [comment]
人だけならberlinからleipzigは電車で1時間なので乗り継ぎが悪い場合は電車でいくのも考えてみては？

**Comment by knorth55** [comment]
http://www.berlin-airport.de/en/travellers-sxf/to-and-from/buses-and-trains/local-public-transport/
空港からBerlin Hbfへは30分だそうです

**Comment by knorth55** [comment]
Tokyo -> Berlin
https://www.expedia.co.jp/Flights-Search?mode=search&leg1=from:Tokyo,%20Japan%20%28TYO-All%20Airports%29,to:Berlin,%20Germany%20%28BER-All%20Airports%29,departure:2016/06/26TANYT&trip=roundtrip&leg2=from:Berlin,%20Germany%20%28BER-All%20Airports%29,to:Tokyo,%20Japan%20%28TYO-All%20Airports%29,departure:2016/07/04TANYT&passengers=children:0,adults:2,infantinlap:N&options=cabinclass:economy&origref=www.expedia.co.jp%2FFlight-Search-All

Tokyo -> Leipzig
https://www.expedia.co.jp/Flights-Search?mode=search&leg1=from:Tokyo,%20Japan%20%28TYO-All%20Airports%29,to:Leipzig,%20Germany%20%28LEJ-Leipzig%20-%20Halle%29,departure:2016/06/26TANYT&trip=roundtrip&leg2=from:Leipzig,%20Germany%20%28LEJ-Leipzig%20-%20Halle%29,to:Tokyo,%20Japan%20%28TYO-All%20Airports%29,departure:2016/07/04TANYT&passengers=children:0,adults:2,infantinlap:N&options=cabinclass:economy&origref=www.expedia.co.jp%2FFlight-Search-All

**Comment by pazeshun** [comment]
荷物減らして電車を使うのがいいですかね

**Comment by pazeshun** [comment]
6/29、6/30が準備期間で、7/1にstow task、7/2にpick taskみたいです。
準備期間があるなら、もうちょっとギリギリに行ってもいい気がしてきました。平日に出発したほうが旅費も安いし、便もたくさんあるみたいです。

**Comment by pazeshun** [comment]
6/27に出発して、ベルリンについたあとで電車で移動するのがいいのではないかと現在は考えています

**Comment by knorth55** [comment]
宿泊先もきめてだいたいの金額を計算したいとおもいます
Google driveのスプレッドシートを使いましょう

**Comment by knorth55** [comment]
スプレッドシートを作ったので使ってください
https://drive.google.com/a/jsk.imi.i.u-tokyo.ac.jp/folderview?id=0B5DV6gwLHtyJSVVwdFk4ekxpX2M&usp=sharing

**Comment by pazeshun** [comment]
ありがとうございます
明日飛行機を決めて、ホテルなど考えてみる感じでしょうか。

**Comment by knorth55** [comment]
飛行機の値段はそこまで大きく変わらないと思うのでめぼしいものをリストアップしてもらえますか？
宿泊先に関してはも同様です

**Comment by yuyu2172** [comment]
調べてくれてありがとうございます！

**Comment by pazeshun** [comment]
https://www.expedia.co.jp/Details?action=UnifiedDetailsWidget@showDetails&rfrr=&c=50a2f1b7-34d4-4a9e-9cf2-ee455aeb970b&udpDisplayMode=showhotelbanneronly

**Comment by pazeshun** [comment]
flight detail
![screenshot from 2016-06-03 20 17 44](https://cloud.githubusercontent.com/assets/14994939/15777191/69e4abb8-29c8-11e6-9812-f89ff4897b39.png)

**Comment by pazeshun** [comment]
すいません、リストアップとか忘れてました。
フランクフルトやヘルシンキを経由するのが、ちょっと高めですが乗換え時間短く行けそうです

**Comment by knorth55** [comment]
ベルリン直行便はない？
フランクフルト乗り換えならフランクフルトからライプチヒに飛行機で行ける
ヘルシンキもそうかもしれない

**Comment by knorth55** [comment]
Tegel着のほうが安いから直行便が安いのはないんだとおもいます
berlinのinternational のほうで見てみて直行便の値段もみてみましょう

**Comment by pazeshun** [comment]
ベルリン直行便ないっぽいんですが、どうなんでしょう。
僕も疑問に思って調べたんですが、直行便ないよって情報しか見つかりませんでした。

**Comment by knorth55** [comment]
直行便ないみたいですね、なるほど
乗り換えはヘルシンキが楽で税関も緩いのでヘルシンキがいいとおもいます
フランクフルトはよい噂をききません

**Comment by pazeshun** [comment]
なるほど。
ヘルシンキにすると、上で上げた写真のフライトがエクスペディアの最安値付近で、席もまだ余裕がありそうでした。
とりあえずはこのフライトということで、話を進めていいのではないでしょうか。

**Comment by knorth55** [comment]
そうですね
電車に乗るのでBerlinにつくのはできるだけ早いのがいいと思います

**Comment by pazeshun** [comment]
あ、そうですね、ちょっと時間遅かったですね
もうちょっと早いフライト探してみます。

**Comment by knorth55** [comment]
調べたら17:00くらいにつくのが一番早くてLeipzig Hbfに21:00くらいにつくことになりそうです

**Comment by pazeshun** [comment]
お、ありがとうございます。
ちょっと時間がないんで、宿調べてもらえませんか？
負担押し付けで申し訳ない・・・。

**Comment by knorth55** [comment]
了解です

**Comment by knorth55** [comment]
一応スプレッドシートに候補として検索した旅程をリストしといてください

**Comment by pazeshun** [comment]
スプレッドシートに書きましたが、エクスペディアのリンクが飛行機ごとに作れませんでした。許してください。

**Comment by wkentaro** [comment]
更新しました。

**Comment by ban-masa** [comment]
さっき見たらエクスペディアのサイトから予約できる残りが２枚になっていたので、Finnairの公式サイトから予約しようと思います。該当フライトのリンクは貼れませんでしたが、スクショを貼っておきます。これで問題ないでしょうか？
![finnair](https://cloud.githubusercontent.com/assets/14898742/15919573/9d0495f6-2e4d-11e6-821a-8ca98dbbc862.png)

**Comment by ban-masa** [comment]
@k-okada 
k-northのホテル予約メールで言及していた飛行機というのはこの飛行機のことで合ってますか？
