### ISSUE TITLE
Parameters of bounding boxes for kiva pod's bins

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1606]
Parameters of bounding boxes for kiva pod's bins are not set correctly.
This is problematic for generating masked images from bins. 

Here is an example where masking is failing.

![3fe544b0-275e-11e6-9fff-7c60d3858dae](https://cloud.githubusercontent.com/assets/2062128/15709459/d0fded76-283f-11e6-8e0e-4f0f6dab7272.png)

**Comment by yuyu2172** [comment]
@knorth55 
This is the memo we took when we measured kiva pod.
![img_0847](https://cloud.githubusercontent.com/assets/2062128/15716092/e6b8991a-285b-11e6-9e4f-d7bafde8d193.JPG)

**Comment by yuyu2172** [comment]
#### TODO (mostly for my personal memo)
introduce additonal tf frame for kiva_pod_base which is going to be used by shelf_recognition.yaml

**Comment by pazeshun** [comment]
@yuyu2172 How did you measure kiva pod?

**Comment by yuyu2172** [comment]
まきじゃく

**Comment by pazeshun** [comment]
手ではかると寸法がずれていくので、Kiva podの正確なモデルがどこかにないか、一度探した方がいいと思います

**Comment by yuyu2172** [comment]
探したんですが，みつかりませんでした．
認識に使うんですけど，完璧でなくても大丈夫です．

**Comment by wkentaro** [comment]
これは治りました？

**Comment by yuyu2172** [comment]
Done. You can see that the model of bounding boxes match with real bins.
![screenshot from 2016-06-14 21 37 30](https://cloud.githubusercontent.com/assets/2062128/16043014/93a8ac2a-3278-11e6-9f86-8f73ef39de61.png)
