### ISSUE TITLE
mention-bot no longer works 

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1621]
because the @mention-bot account is removed. https://github.com/facebook/mention-bot/issues/134

**Comment by wkentaro** [comment]
@k-okada Could u please change the webhook settings?
Please change the target url to this:
http://mention-bot-lora-bot.herokuapp.com/

**Comment by knorth55** [comment]
solved ?

**Comment by wkentaro** [comment]
It seems working. https://github.com/start-jsk/jsk_apc/pull/1634#issuecomment-223887071
