### ISSUE TITLE
Difficult Object List in APC2016

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1623]
### What is this

List up difficult object for each task and its reason.
We need to solve these problem.
### Pick task
- Kleenex Paper Roll
  - Big
  - Long
- Rawlings Baseball
  - Roll away from gripper easily
- Fiskars Scissors Red
  - Thin
  - Air leaks
- Toothbrush
  - Thin
  - Air leaks
- Scotch Duct Tape
  - Difficult to grasp from above
- Water Bottle
  - Heavy
- Dumbbell
  - Heavy (current baxter arms can't hold this.)
- Squeakin Eggs Plush Puppies
  - Air leaks
#### Issue
- [x] Easy to protrude
- [x] big 
- [ ] Difficult to enter in bin
#### List
- Kleenex Paper Roll
  - [x] Big
  - [ ] Difficult to enter in bin
- Rawlings Baseball
  - [ ] Roll away from gripper easily
- Fiskars Scissors Red
  - [ ] Thin
  - Air leaks
- Toothbrush
  - [x] Thin
  - Air leaks
- Scotch Duct Tape
  - [ ] Difficult to grasp from above
- Water Bottle
  - Heavy
- Dumbbell
  - Heavy (current baxter arms can't hold this.)
- Chenille Stems
  - [x] Difficult to enter in bin
- Scotch Bubble Mailer
  - [ ] Difficult to enter in bin
- Dr. Brown Brush
  - [x] Difficult to enter in bin
- Cherokee Easy T shirt
  - [x] Easy to protrude out of bin
- Jane Eyre DVD
  - [x] Easy to protrude out of bin
- Squeakin Eggs Plush Puppies
  - Air leaks

Difficult to enter in bin: we can only put the object in bin with certain rotation

**Comment by knorth55** [comment]
@start-jsk/jsk_apc-team-k please edit and add objects data in this issue.

**Comment by pazeshun** [comment]
I wrote about some difficult objects in #1151 
I'll re-arrange them in this issue.

**Comment by pazeshun** [comment]
Update above list.

**Comment by knorth55** [comment]
Updated list above

**Comment by knorth55** [comment]
updated

**Comment by knorth55** [comment]
updated

**Comment by pazeshun** [comment]
updated

**Comment by knorth55** [comment]
updated

**Comment by pazeshun** [comment]
updated due to #1705

**Comment by knorth55** [comment]
@knorth55 @pazeshun TODO: list up same object and reason for difficult object in ARC2017.

**Comment by wkentaro** [comment]
@knorth55 Did u open a new issue for ARC2017?

**Comment by pazeshun** [comment]
I tested new 40 objects today.
I'll analyze results in new issue.

**Comment by knorth55** [comment]
I will open a new issue for ARC2017!

**Comment by knorth55** [comment]
ARC2017 issue is moved to #2051
