### ISSUE TITLE
wait-interpolation-smooth method never returns

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1624]

**Comment by pazeshun** [comment]
From jsk-ros-pkg/jsk_pr2eus#231
`:wait-interpolation-smooth`を使おうとしたが、いつまで経っても終わらない現象が発生した。デバッグの結果、
```
7.E1-irteusgl$ setq tmp (send *ri* :get-val 'controller-actions) 
(#<controller-action-client #X61688e0 /robot/limb/left/follow_joint_trajectory> #<controller-ac
tion-client #Xaa629b0 /robot/limb/right/follow_joint_trajectory> #<controller-action-client #Xa
96dac0 /gripper_front/limb/right/follow_joint_trajectory> #<controller-action-client #Xb5cb778-
/robot/head/head_action>) 
8.E1-irteusgl$ send-all tmp :time-to-finish 
(-0.119066 -0.114786 0.2 0) 
```
gripperのjoint trajectory actionのtime-to-finishだけ大きかった。
time-to-finishはjtaからのfeedbackを受け取ると更新されるが、現在のgripperのjoint trajectory actionの実装ではjtaのgoalに含まれるポイントでのみ、feedbackをpublishするようになっている。これが原因ではないか。

**Comment by k-okada** [comment]
正解っぽい．g

--
◉ Kei Okada

**Comment by pazeshun** [comment]
原因がわかりました。前の私のコメントは正確ではなく、jtaからのfeedbackのtime_from_startがすべて空になっていたのが致命的な原因でした。
feedbackの周期が遅いのもまずくて、`:wait-interpolation-smooth`に入れられる時間の分解能を下げてしまいます。
これらを #1626 で修正し、 #1626 の状態で`:wait-interpolation-smooth`が使えるようになったことを確認しました。

**Comment by pazeshun** [comment]
Closed via #1626
