### ISSUE TITLE
Baxter使用スケジュール

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1641]
https://docs.google.com/a/jsk.imi.i.u-tokyo.ac.jp/spreadsheets/d/18mv-ukZGwZtpoyRaBJaFXnd62bu9OYpTT4vJcfS_ffQ/edit?usp=sharing

絶対使いたい時間をスプレッドシートに記入してください。優先しましょう。

**Comment by knorth55** [comment]
できるだけ前日までに書いてくれると助かります

**Comment by knorth55** [comment]
@start-jsk/jsk_apc-team-k

**Comment by yuyu2172** [comment]
+10 :+1: :+1:

**Comment by knorth55** [comment]
@start-jsk/jsk_apc-team-k  stowとpickをできるだけ毎日実験をして動画と点数を記録するようにしましょう

**Comment by yuyu2172** [comment]
明日，予約しました

**Comment by pazeshun** [comment]
予約しました

**Comment by knorth55** [comment]
直前期なので2時間制でおねがいします

**Comment by pazeshun** [comment]
なるほど、すみません

**Comment by yuyu2172** [comment]
予約しました
