### ISSUE TITLE
douraのソフトウェアのアップデートについて

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1642]
#1638 で`setup_head.launch`にjsk_apc2016_commonパッケージが必要になり、douraのjsk_apcリポジトリを更新してjsk_apc2016_commonパッケージをビルドしようとしたところ、エラーが出た。
#1638 ではjsk_apc2016_commonがROSのpathに含まれていれば良いので、とりあえず放置したが、douraでrosdep installとcatkin clean、catkin buildを行いたい。
大丈夫でしょうか。

**Comment by k-okada** [comment]
直っていなければ明日の朝対応しましょう

--
◉ Kei Okada

**Comment by wkentaro** [comment]
対応しました。
