### ISSUE TITLE
Add document about usage of jsk_2016_01_baxter_apc

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1649]
We want to access the following information easily.
https://github.com/start-jsk/jsk_apc/pull/1565#issuecomment-222102410
https://github.com/start-jsk/jsk_apc/pull/1638#issuecomment-224263184

**Comment by knorth55** [comment]
これはmainプログラムを回すためのlaunchファイルの使い方ってことでいいですか？

**Comment by pazeshun** [comment]
@knorth55
はい、とりあえずそういうことでお願いします。
後からテスト用プログラムの使い方とか足すかもしれませんが。
