### ISSUE TITLE
extrinsic parameters of softkinetic cameras

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1651]
![screenshot from 2016-06-08 22 40 01](https://cloud.githubusercontent.com/assets/2062128/15896178/1d528a44-2dca-11e6-9887-3625dd951f87.png)

Extrinsic parameters (pose of a camera) of softkinetic cameras are wrong.
You can check that by observing discrepancy between the point clouds and the the model of vaccum hose.

**Comment by yuyu2172** [comment]
another picture
![screenshot from 2016-06-08 22 47 05](https://cloud.githubusercontent.com/assets/2062128/15896373/fa59bb10-2dca-11e6-99ab-c8178e07dd01.png)

**Comment by k-okada** [comment]
1. we need to modify thet tf manually
2. the position of vacuum hose is also made in lab, so you'd better to
check if the robot body (red parts)

--
◉ Kei Okada

**Comment by yuyu2172** [comment]
more

![screenshot from 2016-06-09 00 03 59](https://cloud.githubusercontent.com/assets/2062128/15899143/baf547d6-2dd5-11e6-98df-0041c1bee136.png)
