### ISSUE TITLE
softkinetic 周りをちゃんとする

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1652]
1 depthはdepth_frame, colorはcolor_frame で出して、registration する
2 urdf に書くのではなくて、tfを出すlaunchを作る（べき？） https://github.com/ros-drivers/rgbd_launch/blob/indigo-devel/launch/kinect_frames.launch

**Comment by knorth55** [comment]
depthとはpointcloudですか？
それはrgb frameにtransformしていますけど

**Comment by knorth55** [comment]
というかpoint cloudをrgb frameにしてくださいとだいぶ前に要求されたのですが

**Comment by knorth55** [comment]
urdfに書くのではなくtfにかくとはどういうことでしょうか？

**Comment by knorth55** [comment]
何が問題なのか教えてください

**Comment by k-okada** [comment]
- ちゃんとやるとこれ：https://github.com/OpenKinect/libfreenect2/issues/41
- ｐｃｌで関数があるはず．
- ノードもある気がする

０） offset をなくす + 0.024
１） pointcloudをdepth frameでだす
２） point cloud と，color をみて，camera_frameとdepth_frameの差分を手で合わせる

https://github.com/jsk-ros-pkg/jsk_robot/issues/619#issuecomment-222901102
  rvizでcameraをつかって，imageをsubscribe, camera のなかのpoint cloudを確認し，両者が一致することを確認．
３） あとはhttp://wiki.ros.org/depth_image_proc を駆使する．
カメラ周りのtf 等々は，depth_image_procと合わせて1つのlaunchにするといいかも．

--
◉ Kei Okada

**Comment by knorth55** [comment]
![softkinetic_zure](https://cloud.githubusercontent.com/assets/9300063/15900733/85f5dc0c-2ddb-11e6-8f41-c49765317ee9.png)

**Comment by k-okada** [comment]
https://github.com/knorth55/softkinetic/pull/1
で対応中です．ドライバ的にはこれでOKのはず．あとはこれで上手く画像処理が走るか，です．
思ったよりノイズが多いので，kinect(kinect2/kinect/xtion)での処理を横目で睨みつつ，作業するのがいいともいます．
