### ISSUE TITLE
Try to pick bin with more than 5 objects

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1665]
Now, our robot give up picking objects from bin which contain more than 5 objects.
We should do experiment to check if this number "5" is proper or not.
If we can pick objects from more bin, we have possibility to gain more points.

今の戦略のままで5個以上の棚からものがとれるかを新しい認識プログラムで試していないので試してみたい
試してもし6個でも大丈夫そうなら下記の上限をあげてとれる点数をあげたい

https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/node_scripts/work_order.py#L73

**Comment by knorth55** [comment]
In order to pick target object from all bins, we need new strategy, and it looks challenging.

**Comment by knorth55** [comment]
@pazeshun can you try this experiment for pick task?

**Comment by pazeshun** [comment]
ok, I'll try

**Comment by pazeshun** [comment]
@knorth55 @yuyu2172 Binの中の物品の内、目標以外のオブジェクトの位置は取得できるのでしょうか？目標以外のオブジェクトが邪魔だったら他のBinにどかすというのをやりたいです。

**Comment by yuyu2172** [comment]
@pazeshun 
It is possible.

I would probably instantiate multiple centroid publisher nodes (centroid_pub_1, ..., centroid_pub_NUM_MAX_OBJ).

**Comment by pazeshun** [comment]
@yuyu2172 Thank you. I would appreciate it if you do that as soon as possible.
