### ISSUE TITLE
棚モデルの位置決めについて

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1672]
昨年度は、kiva pod baseの位置をintaractive markerを使って調整し、kinectが出力した点群に棚が重なるようにしていたと思います。(違ったら教えてください。)
しかし、これではik->bin-entranceなどの目標位置もずれてしまいます。
kinect位置よりもbaxterの腕のサーボの方がまだ信頼できる気がするので、ik->bin-entranceでグリッパーがbinの入り口中心に来るように棚のモデルを動かした後で、kinectの位置を調整するべきだと思うのですが、どうでしょうか。

**Comment by knorth55** [comment]
それはつまりKinectのtfが間違っているということですか？
それならKinectを動かす必要はなくてtf_static_publisherを調整すべきという気がします

**Comment by pazeshun** [comment]
すいません、kinectのtfを調整するということを言いたかったので、それでいいと思います。
僕の感覚ではかなりずれている気がするのですが、どうなんでしょうかね…

**Comment by knorth55** [comment]
ずれているかもしれません、あまり最近みていないのでわかりません

**Comment by wkentaro** [comment]
> 僕の感覚ではかなりずれている気がするのですが、どうなんでしょうかね…

https://github.com/start-jsk/jsk_apc/issues/1684 のように、Kinect2_torsoはずれていそうです。

**Comment by k-okada** [comment]
そもそも，Kinectがちゃんとロボットに設置されていないのではないか．と．

**Comment by yuyu2172** [comment]
>そもそも，Kinectがちゃんとロボットに設置されていないのではないか．と

僕もそう思います．PR送ってない内容ですが，一旦調整した数日後にまたずれていました．固定が弱いので，触ってズレてしまった気がします．

**Comment by pazeshun** [comment]
> そもそも，Kinectがちゃんとロボットに設置されていないのではないか．と．

はい、直さなければならないということですね。とりあえず、瞬間接着剤で固定してパテで埋める感じで補修した後、該当部品を再造形します。
@wkentaro torsoのKinectの固定台の元データはどこにありますか？

**Comment by wkentaro** [comment]
卒業生の杉浦さんが持っていますね。




Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=www.kentaro.wada@gmail.com&idSignature=22>

2016-06-13 13:13 GMT+09:00 pazeshun <notifications@github.com>:

> そもそも，Kinectがちゃんとロボットに設置されていないのではないか．と．
>
> はい、直さなければならないということですね。とりあえず、瞬間接着剤で固定してパテで埋める感じで補修した後、該当部品を再造形します。
> @wkentaro <https://github.com/wkentaro> torsoのKinectの固定台の元データはどこにありますか？
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1672#issuecomment-225486021>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHFk4qNGu6VV6zgivNnky1YH9ugMnYoks5qLNkCgaJpZM4IzdbD>
> .
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by pazeshun** [comment]
結局、ik->bin-entranceを使って調整する必要はなくなったのでしょうか

**Comment by knorth55** [comment]
これって何が問題だったんだっけ？ 棚の初期位置？
今年は棚にARマーカでも貼れば解決する？

**Comment by pazeshun** [comment]
今年は棚を支える机にチェッカーボードをつけるとよいのではないでしょうか

**Comment by knorth55** [comment]
まぁそんな感じ、とりあえず棚に一工夫で解決する？なら閉めていいですか
