### ISSUE TITLE
Pick two object in one time from tote

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1675]
- use jsk_perception/solidity_rag_merge (http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_perception/nodes/solidity_rag_merge.html)
- use jsk_pcl/SupervoxelSegmentation (http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_pcl_ros/nodes/supervoxel_segmentation.html)

case: https://drive.google.com/file/d/0B5DV6gwLHtyJV0h6cWZTV242Z1E/view?usp=sharing

**Comment by knorth55** [comment]
use jsk_pcl/supervozelSegmentation
![supervoxel](https://cloud.githubusercontent.com/assets/9300063/16006340/8abffb3a-31a7-11e6-9f80-24f24f155d2e.png)

**Comment by wkentaro** [comment]
Please give me the label image if possible.
