### ISSUE TITLE
Big object get stuck during entering bin

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1676]
- [x] approach from upper side
- [x] give some angle during entering bin

https://drive.google.com/file/d/0B5DV6gwLHtyJOVVtU2plb2t6STQ/view?usp=sharing

**Comment by knorth55** [comment]
with `:offset #f(x 0 50)`, robot can put object in bin.
in video, during removal from bin, robot dropped object.
we need to push them down first, and remove arm from bin  
```
(setq avs-picked->return-bin
            (mapcar
               #'(lambda (x)
                    (send *ri* :ik->bin-entrance arm target-bin
                              :offset (float-vector x 0 50)))
                '(-200 -150 -100 -50 0 150)))
(send *ri* :angle-vector-sequence avs-picked->return-bin :fast nil 0 :scale 5.0)
```
https://drive.google.com/file/d/0B5DV6gwLHtyJUUtaUTdtYmVnUzA/view?usp=sharing

**Comment by pazeshun** [comment]
I think `:offset #f(x 0 50)` cause collision between bin top and gripper.
In video, gripper was caught by bin top when removing arm from bin.
I think it may break gripper.

**Comment by knorth55** [comment]
in case of exiting from bin, we can change offset  to -50 for safer exit because we already put object.
```
                  outside | inside
+50 -----------------------------> entry 
                                      |
                                      v
-50 <------------------------------- exit
                  outside | inside

```

**Comment by knorth55** [comment]
why can not we use for bin :h? 
if so, we only just avoid using bin :h

**Comment by pazeshun** [comment]
Bin hだと、今のオフセットである-50でも、Binの上すれすれで入った気がします。
もしかすると、Bin hの列やBin eの列は全部そうなのかもしれません

**Comment by knorth55** [comment]
2、3段目ということ？

**Comment by pazeshun** [comment]
そういうことです

**Comment by knorth55** [comment]
@pazeshun ちなみに1段目と4段目だと上の作戦は有効だと思いますか？

**Comment by pazeshun** [comment]
@knorth55 はい、とりあえずはそうだと思います。
Binのbounding boxのサイズを使ってオフセットを作るようにすると、場合分けなしでいけるかもしれません。

**Comment by knorth55** [comment]
とりあえず決め打ちでいきたいとおもいます
