### ISSUE TITLE
Data collection & Object recognition for in-hand target verification with APC2016 objects

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1678]
- [x] Construct neural network model
- [x] Collect data
- [x] Train model

## Data collection

- [x] barkely_hide_bones
- [x] cherokee_easy_tee_shirt
- [x] clorox_utility_brush
- [x] cloud_b_plush_bear
- [x] command_hooks
- [x] cool_shot_glue_sticks
- [x] crayola_24_ct
- [x] creativity_chenille_stems
- [x] dasani_water_bottle
- [x] dove_beauty_bar
- [x] dr_browns_bottle_brush
- ~~easter_turtle_sippy_cup **(unable to grasp)**~~
- [x] elmers_washable_no_run_school_glue
- [x] expo_dry_erase_board_eraser
- ~~fiskars_scissors_red **(unable to grasp)**~~
- ~~fitness_gear_3lb_dumbbell **(unable to  grasp)**~~
- ~~folgers_classic_roast_coffee **(unable to grasp)**~~
- [x] i_am_a_bunny_book **(unable to detect)**
- [x] jane_eyre_dvd
- [x] kleenex_paper_towels
- [x] kleenex_tissue_box
- ~~kyjen_squeakin_eggs_plush_puppies **(unable to grasp)**~~
- [x] laugh_out_loud_joke_book
- ~~oral_b_toothbrush_green **(unable to grasp)**~~
- ~~oral_b_toothbrush_red **(unable to grasp)**~~
- [x] peva_shower_curtain_liner
- [x] platinum_pets_dog_bowl
- [x] rawlings_baseball
- ~~rolodex_jumbo_pencil_cup **(unable to grasp)**~~
- [x] safety_first_outlet_plugs
- [x] scotch_bubble_mailer **(unable to detect)**
- ~~scotch_duct_tape **(unable to grasp)**~~
- [x] soft_white_lightbulb
- [x] staples_index_cards
- [x] ticonderoga_12_pencils
- [x] up_glucose_bottle
- ~~womens_knit_gloves **(unable to grasp)**~~
- [x] woods_extension_cord

**Comment by wkentaro** [comment]
[bvgg_rgb_forward.pdf](https://github.com/start-jsk/jsk_apc/files/310739/bvgg_rgb_forward.pdf)

**Comment by knorth55** [comment]
in stow task, the gripper could grasp toothbrush.. 
maybe you need to push the object downward more.

**Comment by wkentaro** [comment]
I tried but the robot was unable to grasp it.
https://drive.google.com/open?id=0B9P1L--7Wd2vZzlEaFBGbEZsVGc

**Comment by wkentaro** [comment]
Data collection is done.

https://drive.google.com/drive/u/1/folders/0B9P1L--7Wd2vZjBrRURkMU1PM0k

**Comment by wkentaro** [comment]
Training the model is done. (91%)
<img src="https://cloud.githubusercontent.com/assets/4310419/16330189/5693f112-3a22-11e6-99f7-e7c8bf03e338.png" width="300px" /> <img src="https://cloud.githubusercontent.com/assets/4310419/16330193/5697afc8-3a22-11e6-9f2a-28a5db6c97e4.png" width="300px" /> <img src="https://cloud.githubusercontent.com/assets/4310419/16330190/5696700e-3a22-11e6-817b-f0078a54268d.png" width="300px" /> <img src="https://cloud.githubusercontent.com/assets/4310419/16330194/5697ccd8-3a22-11e6-9bf4-8a245a0f3662.png" width="300px" />
<img src="https://cloud.githubusercontent.com/assets/4310419/16330192/5697b09a-3a22-11e6-8552-8e5c9f5aeee4.png" width="300px" /><img src="https://cloud.githubusercontent.com/assets/4310419/16330191/56972b8e-3a22-11e6-8155-2487533a3375.png" width="300px" /><img src="https://cloud.githubusercontent.com/assets/4310419/16330195/56b80c96-3a22-11e6-90ac-99d612e3d542.png" width="300px" />

**Comment by wkentaro** [comment]
done. 
Closed via https://github.com/start-jsk/jsk_apc/pull/1795
