### ISSUE TITLE
FCN vs RBO for object segmentation in bin

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1682]
### Description
Maybe deep learning approach can be used for the challenge. We should compare these method.

- [x] Compare the accuracy in RBO dataset (apc2015 objects)

**Comment by yuyu2172** [comment]
Performance of RBO

```
all features acc  0.882333039349       
all features acc_cls  0.718367755875   
all features mean_iu  0.63257308164    
all features fwavcc  0.807220166074    

trained only by color features acc  0.827621821208     
trained only by color features acc_cls  0.556445518568 
trained only by color features mean_iu  0.47670422011  
trained only by color features fwavcc  0.716203314254  
```

**Comment by wkentaro** [comment]
FCN with 'berlin_samples' dataset:
```
color features acc: 0.9818556602
color features acc_cls: 0.626917412521
color features mean_iu: 0.573346666354
color features fwavcc: 0.966528537211
```

**Comment by wkentaro** [comment]
It's done.

**Comment by wkentaro** [comment]
@yuyu2172 Result with more images.

https://drive.google.com/drive/u/1/folders/0B9P1L--7Wd2vcWx6YmhfWHBkXzQ

```
acc: 0.905659723898
acc_cls: 0.752237655256
mean_iu: 0.282867992506
fwavcc: 0.864427856981
```

**Comment by wkentaro** [comment]
![1466803322395175933](https://cloud.githubusercontent.com/assets/4310419/16362057/e9231bc6-3bde-11e6-9ea2-f99879f377c4.png)
![1466803937422796964](https://cloud.githubusercontent.com/assets/4310419/16362052/e91bf990-3bde-11e6-9046-c1ff092b870f.png)
