### ISSUE TITLE
kinect2_torso extrinsic parameter seems wrong  

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1684]
![image](https://cloud.githubusercontent.com/assets/4310419/15993890/a716389a-312e-11e6-9416-8eed17aeb42b.png)

**Comment by pazeshun** [comment]
Is #1672 correct?

**Comment by wkentaro** [comment]
I think so.

**Comment by wkentaro** [comment]
@pazeshun fixed the hardware of attaching kinect2 on the Baxter's torso.
I need to adjust kinect2_torso again.
