### ISSUE TITLE
Unable to detect thin objects at the bottom of tote

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1694]
- [x] get bigger attention clipper, but not get surface of tote
- [ ] plane removal

**Comment by knorth55** [comment]
we can use plane removal with astra camera

**Comment by knorth55** [comment]
![tote_plane](https://cloud.githubusercontent.com/assets/9300063/16134723/c649e986-3459-11e6-875a-c1b3c9ed1d0a.png)

I tried to extract plane with OrganizedMultiPlaneSegmentation, but it cannot detect plane.
I couldn't get why it cannot detect...

**Comment by knorth55** [comment]
https://github.com/knorth55/jsk_apc/blob/plane-extract/jsk_2016_01_baxter_apc/launch/include/segmentation_each_object_in_tote.launch#L62-L74

**Comment by wkentaro** [comment]
> we can use plane removal with astra camera

Why are you using plane removal?
You need to remove the bottom plane of tote?

**Comment by wkentaro** [comment]
You can try plane detection with no objects in tote first.

**Comment by knorth55** [comment]
i thought it is easy way to remove plane at the bottom of tote in order to get only pointcloud of objects.

**Comment by knorth55** [comment]
i tried tote with no object, but it cannot detect plane

**Comment by knorth55** [comment]
now i use attention clipper and it can detect thin objects.
i wanted to use plane removal for robust detection, but now attention clipper is fine.
