### ISSUE TITLE
吸着パッドの付け替え

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1696]
吸着パッドを短いものに付け替えようと思うのですが、後で長い方に戻すかもしれないので、ソフトウェアの変更点は最小限に、かつ一つのPRにまとめたいと思います。
ついては、
- URDFのVisual Linkは変更せず、簡単に変更できるCollision Linkのみを変更する
- Lispのend-coordsの位置を短いパッドの先に合わせる
- https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L52 を変更する

以上3点のみを変更しようと思っているのですが、何か問題あったら、どなたか教えてください。

**Comment by pazeshun** [comment]
なお、使用する吸着パッドが決まったら、URDFのVisual Linkも変更しようと思っていますが、その際に右手(現在gripper-v2)と左手(現在gripper-v3)のモデルを更新して、どちらもgripper-v3.1としようと思っています。

**Comment by k-okada** [comment]
なんcm短くなるかな？
一番手を抜いた方法として，
ik解くときに目標位置をずらす．
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter.l#L40
でtarget-coordsをずらす（
副作用が無いようにcopy-worldcoordsしてからがよい）
OR
baxter-interface.l のpick-objectみたいな関数で最後に手先をcmずらす．

がありそうです．上の提案は，吸着パッドを変えた時の正しい変更方法，ということになるかと思います．

一方で，最後の最後のパラチュン大会になったときの，一箇所のマジックパラメータを直せば挙動が変わる方法もあるとたすかるかもしれません．

今回は提案方法でやってみて，次に変える事があったら，別の方法もやってみましょう．

--
◉ Kei Okada


2016-06-14 13:17 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by pazeshun** [comment]
3cmくらい短くなります。
一応、euslisp上では、 https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L52-57 に使用頻度が高いマジックパラメータがまとめられています。多分変える必要ないだろうと思ったパラメータはまとめていませんが、必要があれば順次追加するつもりです。
今回関係するのは https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L52-53 のみになってます。
私的には、変更する場所が多くなって管理しにくくなるのは避けたいので、baxter.yamlを修正するのがわかりやすいと信じていますが、その後ビルドが必要なことを考えると、もうちょっと簡単に直す方法があってもいいかもしれません。考えてみます。

**Comment by pazeshun** [comment]
なお、現在使用している真空パッドはSPB4シリーズで、新しく買ったパッドのうち長いものがSPB4fシリーズ、短いものがSPB2fシリーズです。
今回は、SPB2fシリーズをつけて試そうと思っています。

**Comment by pazeshun** [comment]
#1697 のあと、 #1699 という問題が発生しましたが、 #1700 で解決しました。
これで、吸着パッドの付け替え自体は成功したと思うので、このissueを閉じます。
