### ISSUE TITLE
新しくPCを購入する

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1698]
APCにもっていくパソコンを新しく購入する．

P50のスペック
[spec.txt](https://github.com/start-jsk/jsk_apc/files/313655/spec.txt)

**Comment by wkentaro** [comment]
明日、P50二台でセットアップしてみようと思うので朝P50を貸してもらえるでしょうか。
@yuyu2172

**Comment by yuyu2172** [comment]
ちょうど明日の午前中に予定が入ってしまっているので無理です．．

**Comment by yuyu2172** [comment]
別のときなら貸せます．

@k-okada 
本番までに条件を満たすノートはみつかるのでしょうか？

**Comment by k-okada** [comment]
いや、研究室にあるもので考えておいてください。
@mmurookaか一時的にヨセフ君にわたっているのをつhdd入れ替えてつかってもよいです

--
◉ Kei Okada

2016/06/17 0:32、Yusuke Niitani <notifications@github.com> のメッセージ:

> @k-okada 
> 本番までに条件を満たすノートはみつかるのでしょうか？

**Comment by k-okada** [comment]
管理簿みると 1/5 が抜けているけど，稲葉先生かな？聞いてみて下さい．
あと，@orikuma さんがp70を持っているはず．つかっている？
--
◉ Kei Okada



2016-06-17 8:22 GMT+09:00 Kei Okada <kei.okada@gmail.com>:
> いや、研究室にあるもので考えておいてください。
> @mmurookaか一時的にヨセフ君にわたっているのをつhdd入れ替えてつかってもよいです
>
> --
> ◉ Kei Okada
>
> 2016/06/17 0:32、Yusuke Niitani <notifications@github.com> のメッセージ:
>
> @k-okada
> 本番までに条件を満たすノートはみつかるのでしょうか？

**Comment by mmurooka** [comment]
> @mmurookaか一時的にヨセフ君にわたっているのをつhdd入れ替えてつかってもよいです

ヨセフさんが持っています．

**Comment by orikuma** [comment]
> あと，@orikuma さんがp70を持っているはず．つかっている？

実験用個人PCとして使っています.

**Comment by wkentaro** [comment]
管理簿の1/5はいまのところ行方不明です。(メールしました)
稲葉先生が別で一台持っているので貸していただけるということです。

**Comment by wkentaro** [comment]
稲葉先生からP50を貸していただきました。
いまP50二台あります。
