### ISSUE TITLE
常に把持判定がtrueになる

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1699]
#1697 で真空グリッパを変更したところ、
```sh
% rostopic echo -n1 /gripper_front/limb/right/pressure/state
data: 1003.38000488
---
% rostopic pub -1 /vacuum_gripper/limb/right std_msgs/Bool -- true
publishing and latching message for 3.0 seconds 
% rostopic echo -n1 /gripper_front/limb/right/pressure/state     # No object is grasped
data: 872.770019531
---
```
というふうになり、気圧の下がり幅が大きくなった。ファームウェアを変更してしきい値https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/firmware/gripper_front_manager_right.ino#L131 を変更する必要がある。
@ban-masa お願いできますか？

**Comment by pazeshun** [comment]
#1700 でLisp側では気圧センサ値で直接把持判定を行うようになったので、ファームウェアをすぐに変更する必要は消滅しましたが、一応変更したいです。

**Comment by wkentaro** [comment]
Closed via #1700 and #1704
