### ISSUE TITLE
新しいカメラ(ASTRA)をグリッパーにとりつける

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1703]
明日、https://github.com/start-jsk/jsk_apc/issues/1650#issuecomment-225594237 でふれた部品が完成するはずなので、その導入に合わせて新しいカメラ(ASTRA)のグリッパーへの取り付け方を考える。
とりあえず、現在装着されているSoftkinetic Cameraを取り外して、新しいカメラを両面テープで仮止めするつもりである。
@knorth55 明日Softkineticを外して大丈夫でしょうか。
他に何か問題がある場合は、お知らせください。

**Comment by knorth55** [comment]
大丈夫です

**Comment by yuyu2172** [comment]
I am ok.

**Comment by pazeshun** [comment]
そういえば、新しいカメラは同じPCに2個接続できるのでしょうか。
@wkentaro 試していただけませんか？

**Comment by wkentaro** [comment]
> そういえば、新しいカメラは同じPCに2個接続できるのでしょうか。
また、新しいカメラ同士で干渉は発生しないのでしょうか。
@wkentaro 試していただけませんか？

@knorth55 @yuyu2172 Can I entrust this?

**Comment by knorth55** [comment]
ok

**Comment by yuyu2172** [comment]
no problem

**Comment by wkentaro** [comment]
![screenshot from 2016-06-15 15 45 27](https://cloud.githubusercontent.com/assets/4310419/16070435/542ce8f2-3310-11e6-9d0e-22a9949f7bb6.png)

It was easy, so I have done it.

**Comment by pazeshun** [comment]
@wkentaro Thank you.
今日中に取り付けます。

**Comment by pazeshun** [comment]
とりあえず仮止めしました。
![dsc_0391](https://cloud.githubusercontent.com/assets/14994939/16074120/05d0500e-3324-11e6-9b14-9655c60ec253.JPG)
この後取り付け方法を考えます。

**Comment by pazeshun** [comment]
今日中に固定具を作成するつもりです

**Comment by pazeshun** [comment]
固定具を作成し、固定しました。
![dsc_0393](https://cloud.githubusercontent.com/assets/14994939/16116512/578e6644-3408-11e6-8263-54c435529fd5.JPG)

**Comment by wkentaro** [comment]
The extrinsic parameters are calibrated in #1710
