### ISSUE TITLE
Difficult to grasp Squeakin Eggs Plush Puppies with new vacuum pad

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1705]
以前のグリッパーでも吸着が弱かったが、把持できないことが多くなった。
新しいパッド内側のひだを全てカットしたり、半分くらいカットしたりして試してみたが、把持しやすさはほぼ変わらなかった。

**Comment by pazeshun** [comment]
これに関連し、現在右手にはひだをカットしていないパッドがついていて、左手にはひだを半分ほどカットしたパッドがついています。
@knorth55 実験していて、右手と左手で物品の取りやすさに明確な差が確認できたら教えてください。

**Comment by wkentaro** [comment]
@pazeshun https://github.com/start-jsk/jsk_apc/pull/1685 でデータを集めるときに調べてみます。

**Comment by pazeshun** [comment]
根本的な原因は、新しい吸着パットに内蔵されている網が抵抗になり、流量を押し下げてしまっていることでした。
網を除去してみると、流量は大きく向上し、Squeakin Eggs Plush Puppiesも前作のグリッパー程度は持てるようになりましたが、騒音が許容不可なレベルです。
一度除去した網を戻すのにはまだ成功していないので、成功したらもっといろいろ実験できるかと思います。
また、流量問題は掃除機にも依存するので、現在の掃除機に最適化しすぎるのもよくないと感じています。

**Comment by pazeshun** [comment]
網を戻すのに成功しました。いろいろ実験してみます。

**Comment by knorth55** [comment]
今日の朝実験したところそのボールはStow Taskでは全く取れなかったです
今までは取れていました
ご報告までに

**Comment by pazeshun** [comment]
新しい220V用掃除機で試したところ、去年のグリッパー程度はつかめるのではないかと思えてきました。

**Comment by wkentaro** [comment]
https://github.com/start-jsk/jsk_apc/issues/1678#issue-159769336
にテーブルトップで自動でつかめなかったものを書いています。

**Comment by pazeshun** [comment]
@wkentaro ありがとうございます。

**Comment by wkentaro** [comment]
また、各物体のGradpabilityを出す必要があればデータを取るときに一緒にやるので言ってください。

**Comment by pazeshun** [comment]
@wkentaro Graspabilityは掃除機に大きく依存する気がしてて、テーブルトップとBinの中とでは違う気もするのですが、もし余力があるのであれば、やっていただけると大変助かります。

**Comment by wkentaro** [comment]
新グリッパの性能評価という意味で、研究発表の際に必要かもと思ったのですが、(卒論や研究発表など)必要無ければ止めておきます。

プランニングでGraspの精度を高める研究方針などあれば、Baselineを作る際に有用かと思いました。

2016年6月19日日曜日、pazeshun<notifications@github.com>さんは書きました:

> @wkentaro <https://github.com/wkentaro>
> Graspabilityは掃除機に大きく依存する気がしてて、テーブルトップとBinの中とでは違う気もするのですが、もし余力があるのであれば、やっていただけると大変助かります。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1705#issuecomment-226980533>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHFk7Z42MZfvfVfAJLrODZeefxmbbFiks5qNNR3gaJpZM4I2C1i>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by pazeshun** [comment]
@wkentaro 色々考えて下さってありがとうございます。
私は、棚の手前や中でどうグリッパーを動かすかというところに力点をおいて考えていたわけですが、そもそも新しいグリッパーで物がつかめるのかということを評価するのをすっかり失念しておりました。
その評価という意味で、テーブルトップでのGraspabilityのデータは欲しくなりました。
本来私がやるべきデータ集めのところ、大変申し訳ないのですが、もし可能でしたらデータ集めをお願いできますでしょうか。

**Comment by wkentaro** [comment]
@pazeshun 了解です。Issueを立てたので、確認してください。
https://github.com/start-jsk/jsk_apc/issues/1751

**Comment by knorth55** [comment]
@pazeshun can we close this issue? or are you going to work on this?
