### ISSUE TITLE
Astra Cameras are identified by device id 

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1707]
Astra camera identifies by device id, not by serial number.
Now, we need to plug left arm first and right arm second.

https://github.com/knorth55/jsk_apc/blob/25f76bff73ecc9ab503f1031c23e066119c71c35/jsk_2016_01_baxter_apc/launch/include/astra_hand.launch#L8

https://github.com/knorth55/jsk_apc/blob/25f76bff73ecc9ab503f1031c23e066119c71c35/jsk_2016_01_baxter_apc/launch/include/astra_hand.launch#L24

**Comment by knorth55** [comment]
i tried to get serial number, but it cannot be detected by lsusb.
`lsusb -v | grep iSerial`

**Comment by k-okada** [comment]
please paste all information you got when two camera is connected

--
◉ Kei Okada

**Comment by knorth55** [comment]
can some do ls lsusb -v on eyelash and paste result here?

**Comment by wkentaro** [comment]
https://gist.github.com/06bd1d22c72dc4c200b9f53a8da5fea2

**Comment by knorth55** [comment]
@k-okada 
information about astra camera is here. 
there is no iSerial information. 
https://gist.github.com/wkentaro/12ee254719ec49650cdedb79ed70efd5#file-lsusb_v-txt-L973-L1159

**Comment by k-okada** [comment]
It is important to know if there is an information which can distinguish
two devices, not if there is an iSerial information, they are very similar,
but very different way of thinking, so you need to we astra camera part
from lsusb and compare them like;
```
$ diff lsusb_v.txt lsusb_v2.txt
1c1
< Bus 001 Device 011: ID 2bc5:0402
---
> Bus 001 Device 012: ID 2bc5:0402
```
And  it is always good to conclude something not to show an envidence why
we can not do this, but to show how we can solve this problem.
If we look at this
http://wiki.ros.org/hokuyo_node#Using_udev_to_Give_Hokuyos_Consistent_Device_Names
they create another program to get ID of hokuyo device and name the
devices. so we could conclude this topic as
'ok let's find the way to write program to get iSerial information from
device'


--
◉ Kei Okada

**Comment by k-okada** [comment]
@wkentaro told me that there is 'Forum' on discussing on this device. Can
you put that link here?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
- https://3dclub.orbbec3d.com/t/linux-sdk-hardware-support/32
- https://3dclub.orbbec3d.com/t/full-openni-2-environment-download/34
- https://3dclub.orbbec3d.com/t/mainstream-openni-support-for-orbbec-cameras/114
- https://3dclub.orbbec3d.com/t/orbbec-astra-on-ros/162

**Comment by pazeshun** [comment]
Maybe we can use the following format if two Astra cameras are connected to different USB bus:
https://github.com/ros-drivers/openni2_launch/blob/indigo-devel/launch/openni2.launch#L12
See also:
https://github.com/ros-drivers/openni2_camera/blob/indigo-devel/src/openni2_driver.cpp#L615-L616
and
https://github.com/ros-drivers/openni2_camera/blob/indigo-devel/src/openni2_driver.cpp#L638-L641

**Comment by wkentaro** [comment]
I asked @knorth55 to do this: https://github.com/start-jsk/jsk_apc/pull/2057#discussion_r114144905

**Comment by wkentaro** [comment]
I can set the serial number shown in below command output.

```
% rosrun openni2_camera list_devices 
[ INFO] [1494737840.549513001]: [${node}] [OpenNI2DeviceListener::onDeviceConnected] Device "2bc5/0402@1/5" found.
[ INFO] [1494737840.549685795]: [${node}] [OpenNI2DeviceListener::onDeviceConnected] Device "2bc5/0402@1/3" found.
Found 2 devices:

Device #0:
Uri: 2bc5/0402@1/3 (Vendor: Orbbec    , Name: Orbbec, Vendor ID: 2bc5, Product ID: 402)

Warning: USB events thread - failed to set priority. This might cause loss of data...
Serial number: 16042710236
Device #1:
Uri: 2bc5/0402@1/5 (Vendor: Orbbec    , Name: Orbbec, Vendor ID: 2bc5, Product ID: 402)

Warning: USB events thread - failed to set priority. This might cause loss of data...
Serial number: 16042710220
```
