### ISSUE TITLE
Try to pick difficult object for several times and fail

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1708]
- shuffle tote after several failures
- [x] choose object randomly (random object index for `:pick-object`)

i tried to shuffle tote, but it seems too heavy to shuffle for baxter...

**Comment by knorth55** [comment]
@k-okada トートをシャッフルする際に右腕と左腕を同時に動かして中の物体を撹拌したいと思っています。
`main.launch`では右腕と左腕は別々のコントローラーでたちあげられているのですが、別々にコントローラが立ち上がっている際に右腕と左腕を同時にうごかすにはどうすればいいのでしょうか？
下記のプログラムのような動作をしたいと思っています

https://github.com/knorth55/jsk_apc/blob/2f3a0d5e47513fe26feb0efb982f6935fcf053ba/jsk_2016_01_baxter_apc/euslisp/examples/shuffle.l

**Comment by knorth55** [comment]
実行動画です
https://drive.google.com/a/jsk.imi.i.u-tokyo.ac.jp/file/d/0B5DV6gwLHtyJVXphU3FWMDgzaWs/view?usp=sharing

**Comment by pazeshun** [comment]
topicやパラメータで通信するのはだめなのでしょうか。
今のmain.lだと、`right_hand/state`パラメータとかで通信してましたよね？

**Comment by k-okada** [comment]
:angle-vector の引数のctypeに:default-controller をセットしたら上手くいかないかな。

https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-interface.l#L231

2016年6月16日木曜日、pazeshun<notifications@github.com>さんは書きました:

> topicやパラメータで通信するのはだめなのでしょうか。
> 今のmain.lだと、right_hand/stateパラメータとかで通信してましたよね？
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1708#issuecomment-226355192>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3KLma5GuJK-8Cl9lPCGDnvXVx37Fks5qMJOcgaJpZM4I2ZvU>
> .
>


-- 
--
◉ Kei Okada

**Comment by pazeshun** [comment]
> :angle-vector の引数のctypeに:default-controller をセットしたら上手くいかないかな。

そもそも右手と左手が別のROSノードにわかれているので、:default-controllerをセットしたところでうまく通信してくれるわけではないと思っているのですが、違うのでしょうか。

**Comment by k-okada** [comment]
hrpsysだと一つのプロセスで全てのangle-vectorを動かし制御しますが，pr2だとlimb毎にコントローラが走っているはずです．
で，robot-interfaceではhrpsysでも右手だけを動かすことができたり，あるいはpr2だけど全身同時に:angle-vectorを送るようにできているはずです．
なので基本的には動くともっています．
もちろん，「基本的には」「動く」の間に，あれとこれとこれとあれをすると，という日本語が含まれているかもしれませんが．

--
◉ Kei Okada


2016-06-16 10:36 GMT+09:00 pazeshun <notifications@github.com>:

**Comment by pazeshun** [comment]
なるほど。

**Comment by knorth55** [comment]
ありがとうございます
やってみようと思います

**Comment by knorth55** [comment]
アームがtoteにあたってtoteをうごかしてしまうという問題があるためtoteをできるだけ動かないよう固定したいと考えています
なのでtote自体をもって揺さぶるのはやめて混ぜる方法をかんがえてみます
