### ISSUE TITLE
Baxterの関節トルクの上限を適切に設定する

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1711]
From #1563 
- Baxterのjtaの-1を切ってみて、適切な閾値を設定できないか
- Baxterの関節サーボが角度固定制御からなじみ制御に移行する閾値を適切に設定できないか

**Comment by pazeshun** [comment]
![screenshot from 2016-11-09 14 32 53](https://cloud.githubusercontent.com/assets/14994939/20128268/490483fc-a68a-11e6-95f3-1d61a3c8102a.png)
![fast_move_s0_angle](https://cloud.githubusercontent.com/assets/14994939/20128250/37cbd4fa-a68a-11e6-8b3e-ba6996b3e9fc.png)
![fast_move_s0_torque](https://cloud.githubusercontent.com/assets/14994939/20128252/37ce4d16-a68a-11e6-87b6-c00bb4805628.png)
![fast_move_s1_angle](https://cloud.githubusercontent.com/assets/14994939/20128251/37ce2b2e-a68a-11e6-9827-d9c425f9bc54.png)
![fast_move_s1_torque](https://cloud.githubusercontent.com/assets/14994939/20128255/37d33b6e-a68a-11e6-8c98-872ff3fd9f95.png)
![slow_move_s0_angle](https://cloud.githubusercontent.com/assets/14994939/20128254/37ced16e-a68a-11e6-8a70-27509c033bf3.png)
![slow_move_s0_torque](https://cloud.githubusercontent.com/assets/14994939/20128253/37ce8790-a68a-11e6-943b-1374d113de8e.png)
![slow_move_s1_angle](https://cloud.githubusercontent.com/assets/14994939/20128256/37ed2fd8-a68a-11e6-930f-de4f1de418cb.png)
![slow_move_s1_torque](https://cloud.githubusercontent.com/assets/14994939/20128257/37edf026-a68a-11e6-96a5-f7ed1b59e1d1.png)

**Comment by pazeshun** [comment]
rqt_plotで簡単な測定を行った状態で、時間軸が揃えられていないので何とも言えない部分がありますが、少なくとも発揮トルクが一定以上になったら切れるという制御ではなさそうです。
http://sdk.rethinkrobotics.com/wiki/Hardware_Specifications#Peak_Torque
を見ると、Peak torqueにはまだ達していない感じです。
ゆっくり力をかけた場合に、あと5Nmトルクを使えるといいなと思っています。

**Comment by knorth55** [comment]
あんまりよくわかってないんだけど閾値を今よりあげるってこと？
その閾値を超えるとなじみ制御になるということ？

**Comment by pazeshun** [comment]
そうだと思っているんですが、
* その閾値が何に対する閾値なのか
* どのレイヤーで設定されているのか
* どのレイヤーから変更することができるのか

が現状わからない状態です。
とりあえず、一番目について実験的に確かめようと思ったのですが、実験の仕方が悪かったのもあって確かめられなかったというのが現状です。

**Comment by pazeshun** [comment]
`/robot/limb/right/joint_command`を監視しましたが、馴染み制御に切り替わるときでも命令が出ていませんでした。

**Comment by pazeshun** [comment]
```
rostopic info /robot/limb/right/joint_command
Type: baxter_core_msgs/JointCommand

Publishers: None

Subscribers: 
 * /realtime_loop (http://baxter:41626/)
```

**Comment by pazeshun** [comment]
https://groups.google.com/a/rethinkrobotics.com/forum/#!topic/brr-users/9BxFGnNMEtY

**Comment by pazeshun** [comment]
上のように、contact safetyという機能が原因でした。
`/robot/limb/<left/right>/suppress_contact_safety`に`std_msgs/Empty`タイプのメッセージを送ることで、この機能を一時的に無効化することができます。
無効化し続けるには、5Hz以上の周期でメッセージを送り続ければいいようです。

**Comment by pazeshun** [comment]
Related to RethinkRobotics/baxter_interface#75

**Comment by pazeshun** [comment]
@wkentaro RethinkRobotics/baxter_interface#75 を使用したいのですが、wkentaro/baxter_interfaceに`baxtereus-devel`とRethinkRobotics/baxter_interface#75を含んだブランチを作っていただけないでしょうか。

**Comment by wkentaro** [comment]
Done: https://github.com/start-jsk/jsk_apc/pull/1950

**Comment by pazeshun** [comment]
![no_contact_safety_effort](https://cloud.githubusercontent.com/assets/14994939/20611548/021255b0-b2f0-11e6-9e19-c94ad89f46b5.png)

**Comment by pazeshun** [comment]
close for now
