### ISSUE TITLE
cannot pick standing flat object 

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1718]
for example books, envelops, gripper cannot pick standing flat objects from tote.
- [ ] approach from other direction

**Comment by knorth55** [comment]
With pinch motion, we can pick the flat object with parallel gripper.

**Comment by wkentaro** [comment]
Will be addressed by https://github.com/start-jsk/jsk_apc/issues/2111

Please fill the list at https://github.com/start-jsk/jsk_apc/issues/2177
