### ISSUE TITLE
新しい掃除機の改造

### ISSUE THREAD

**Issue by ban-masa** [start-jsk/jsk_apc#1723]
日立製の240V対応掃除機の試験動作を行い、十分な吸引力があることが分かったのでこれを制御できるように改造していく。
基本方針は今と同じように掃除機の電源スイッチにトライアックを挟んでON/OFFするというもの。
耐圧の関係で去年のものを流用することはできなさそうなので似たような回路を作成する予定。

**Comment by ban-masa** [comment]
以下のどっちかを使ってみる。
http://akizukidenshi.com/catalog/g/gK-00203/
↑去年の回路。バリスタの種類を変更するだけで240V対応できそう。
http://akizukidenshi.com/catalog/g/gI-05569/
↑モジュール化された素子。耐圧も電流も問題なさそうに見える。

**Comment by pazeshun** [comment]
@ban-masa とりあえずどちらも買ってみるべきですね。
できれば明日中に掃除機周りの試作機を作りたいところです。

**Comment by ban-masa** [comment]
掃除機側のケーブルを引き出し、上記の２つのうち下の方で試してみた。
オン、オフは問題なくできるが放熱板込みでもかなり熱くなる。
放熱板は大きくするとしても、１５分間連続運転できるか不安が残る。
今日試していた奴が上限16Aであるのに対し、今まで使用していた回路のソリッドステートリレーの方が25Aであることを考えると今までのソリッドステートリレーのほうが良いのかもしれない（何気に温度の上限もこっちの方が高い）
どちらにせよ、明日放熱板を大きくして作り直すので、もうひとつの方を試したい。
もしダメでもモジュール化されてる素子の方は実装が簡単なので明日中に改造終了できるはず。

**Comment by ban-masa** [comment]
掃除機にはバイメタルサーモスタットが入っており、一定温度以上で自動的に電源がオフになるとのこと。
今までの掃除機停止も同様の理由によるものと考えられ、自作回路の問題ではなかったようである。

その熱保護に240V対応の掃除機が思っていたよりも早く引っかかっている気がする。
今日実際にグリッパーにつないでテストしていると１０分ほどで止まってしまった。
１５分連続運用が可能かなんとも言えない部分がある。
ただし、今回はホースを単純に連結したためホースの長さが約２倍になっており、流路損失が掃除機への大きな負荷となった可能性がある。
圧力センサの値を見ても吸引しているだけで780hPaまで下がっており、その割には吸引力はそこそこだった。
ホースを短くして実験したいが、そのためには今までのホースを切断する必要がある。
ホース同士の接続を行う場合は熱収縮チューブが使えそうな気がする。
明日ドイトでevolutionと同じ太さの掃除機のホースがないか探すことも視野に入れている。

掃除機に関して選択肢は２つあり、どちらがいいか明日中に見極めてしまいたい。
１．今の掃除機＋変圧器
２．新しい掃除機
また、最悪グリッパーの網を外すことも視野に入れるべきだろう。

**Comment by pazeshun** [comment]
@ban-masa 掃除機は別にして、グリッパーの網は外したくなったら外しましょう。騒音問題はこの際度外視します。
また、もし今の掃除機のホースを切断するのであれば、新しい掃除機のホースに付いているキャップがそのままつけられると思っているのですが、どうでしょうか。
私も明日ドイト行こうと思っているので、行く時は声をかけていただけると嬉しいです。

**Comment by ban-masa** [comment]
@pazeshun 
新しい掃除機のホースのキャップは多分つくと思うのですが、その場合ホースの根本から切断しないといけないのでevolutionが使えなくなってしまいます。ホースの真ん中辺りで切断して熱収縮などでつなげばevolutionに戻すことも可能になります。
最終手段としてバイメタルサーモスタットを外すことも考えてはいますが、やりたくないですね…

**Comment by k-okada** [comment]
家の水道管の工事をみていて思いついた方法で，空気でいけるかわからないですが，
中に塩ビのパイプをつめて，外側を
http://www.haikaiold.com/blog-entry-6679.html
でまくといけるんじゃないかとおもいます．

--
◉ Kei Okada


2016-06-22 23:15 GMT+09:00 Bando Masahiro <notifications@github.com>:

**Comment by ban-masa** [comment]
新しい掃除機に２つとも換装。
分解後の組み立て方の差か、左右の掃除機で特性が少し違う気がする。
今は吸引力調整目盛りで左右の圧力をだいたい合わせている。

**Comment by pazeshun** [comment]
後は回路の配置と、スイッチの取付けですかね。

**Comment by pazeshun** [comment]
終わりました
