### ISSUE TITLE
持っていくものリスト

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1725]
- 工具
  - [x] パテ
  - [x] アロンアルファ (@pazeshun)
  - [x] 万能ハサミ (@pazeshun)
  - [x] はんだごて (@ban-masa)
  - [x] 養生テープ (@pazeshun)
  - [x] ビニールテープ (@pazeshun)
  - [x] ドライバー (@pazeshun)
  - [x] 六角レンチ (@pazeshun)
  - [x] ペンチ、ニッパー (@pazeshun)
  - [x] ハサミ (@pazeshun)
  - [x] Baxter組み立て用の工具(モンキーレンチなど) (@pazeshun)
  - [x] 油性マジック (@pazeshun)
  - [x] 文房具 (@ban-masa)
  - [x] メジャー (@ban-masa)
  - [x] 両面テープ (@pazeshun)
- 材料
  - [x] ユニバーサルプレート、L字ユニバーサル (@pazeshun)
  - [x] APC部品箱(ねじなど) (@pazeshun)
  - [x] 割り箸(グリッパ骨折時の添え木用。ユニバーサルプレートを切ってもいいが、こっちのほうが楽) (@ban-masa)
  - [x] 真空パッド (@pazeshun)
  - [x] コード (@ban-masa)
  - [x] サーボモータ (@pazeshun)
  - [x] ユニバーサル基板 (@ban-masa)
  - [x] はんだ (@pazeshun)
  - [x] はんだ吸い取り線 (@pazeshun)
  - [x] Arduino予備 (@pazeshun)
  - [ ] 圧力センサ予備 (@ban-masa)
  - [x] ホース予備 (@pazeshun)
  - [x] くくりつける紐/ダイニーマ (@pazeshun)
  - [x] 結束タイ (最小サイズのやつ一袋と、今Baxterに使われてる結束タイのうち2番目に大きなもの一袋) (@pazeshun)
  - [x] 手元用のライトとそれ用のボタン電池 (@pazeshun)
- ロボット本体
  - [x] グリッパ本体(+予備) (@wkentaro)
  - [x] ASTRA (@wkentaro)
  - [x] ASTRA予備 (@wkentaro)
  - [x] 掃除機 (@ban-masa)
  - [x] 掃除機駆動回路 (@ban-masa)
  - [x] 去年の掃除機駆動回路 (@pazeshun)
  - [x] Kinect torso+固定具 (@knorth55)
  - [ ] （Kinect head+固定具）
  - [x] Baxter Firmware Update USB (@wkentaro)
  - [x] Keyboard (@knorth55)
- 配線
  - [x] USBハブ (@knorth55)
  - [x] USB延長ケーブル(カメラ用のUSB3.0を忘れずに)( @pazeshun が一本持った) (@knorth55)
  - [x] Arduino用mini USB-USB変換ケーブル( @pazeshun が短いものを一本のみ持った) (@knorth55)
  - [x] サーボ用ACアダプタ、コンセント延長ケーブル (@knorth55)
  - [x] 220V対応電源タップ (@knorth55)
  - [x] 5m 電源延長コード (@knorth55)
  - [x] （電圧変換用トランス） (@pazeshun)
  - [x] Ethernetケーブル (@wkentaro)
  - [x] LANハブ (@wkentaro)
- PC
  - [x] ThinkPad P50 (eyelash) + Battery charger (@wkentaro)
  - [x] ThinkPad P50 (satan) + Battery charger (@knorth55)
  - [x] マウス、~~マウスパッド~~ (@wkentaro)
  - [x] Z97M (boa) (@yuyu2172)
  - [x] Titan X (@wkentaro)
  - [x] Display's display (@yuyu2172)
  - [x] Display's stand (@wkentaro)
- その他
  - [x] GoPro (@wkentaro)
  - [x] iPhone ジンバル (@wkentaro)
  - [x] Calib board (@wkentaro)

**Comment by pazeshun** [comment]
適当に追加してください。
#239 も参考にしましょう。

**Comment by yuyu2172** [comment]
マウス
マウスパッド

**Comment by wkentaro** [comment]
I added PCs.

**Comment by k-okada** [comment]
向こうにあるBaxterのFirmwareは不明なのでUpdateUSB（今本体に刺さっているもの）

**Comment by pazeshun** [comment]
Updated

**Comment by pazeshun** [comment]
@k-okada 
Baxterの手元用のライトの電池の予備が必要なのですが、電池置き場を探しても3個しかありませんでした。1回の電池交換で2個電池を使うので、このままでは足りない気がします。買っていただけないでしょうか。
https://www.amazon.co.jp/Panasonic-%E3%82%B3%E3%82%A4%E3%83%B3%E5%BD%A2%E3%83%AA%E3%83%81%E3%82%A6%E3%83%A0%E9%9B%BB%E6%B1%A0-10%E5%80%8B-%E3%83%90%E3%83%AB%E3%82%AF%E5%93%81-CR2032/dp/B00BUZQ1DE/ref=sr_1_2?ie=UTF8&qid=1466502120&sr=8-2&keywords=cr%EF%BC%92%EF%BC%9032
ライト本体の予備も必要ですが、Amazonだと納期が遅く、値段も高い感じでした。
ヨドバシで買えるなら買いたいです。
http://www.yodobashi.com/%E3%83%A4%E3%82%B6%E3%83%AF-Yazawa-LB106VPK-%E3%82%BB%E3%83%BC%E3%83%95%E3%83%86%E3%82%A3%E3%83%A9%E3%82%A4%E3%83%88%E3%83%93%E3%83%93%E3%83%83%E3%83%88%E3%83%94%E3%83%B3%E3%82%AF/pd/100000001002619875/
買えない場合は、ドイトで買ってきます。
http://jp.misumi-ec.com/vona2/detail/223006464254/?HissuCode=LB106VPK

**Comment by ban-masa** [comment]
finnairのサイトを見たところ事前に、預ける荷物量の有料追加はできるようですがしておくべきでしょうか。

**Comment by k-okada** [comment]
生協にないかな？

--
◉ Kei Okada

2016/06/21 18:56、pazeshun <notifications@github.com> のメッセージ:

**Comment by k-okada** [comment]
一回荷物を見積もってみましょう
前回は3人で行けたので大丈夫に思ってはいるんだけど

--
◉ Kei Okada

2016/06/21 19:08、Bando Masahiro <notifications@github.com> のメッセージ:

**Comment by k-okada** [comment]
ちがうか，ライトを買えということか．電池と一緒に買っておきました

--
◉ Kei Okada


2016-06-21 19:22 GMT+09:00 Kei Okada <kei.okada@gmail.com>:

**Comment by pazeshun** [comment]
@k-okada わかりにくくて申し訳ないです。ありがとうございます。

**Comment by k-okada** [comment]
今週くるamazon、ヨドバシの荷物は伝票さえ保管しておいたら、伝票がなけければ配送票をとっておいて、どんどん開けて下さい
ここで上がっているもの以外にコチガミさんの電源と古田君のマザボきます


2016年6月21日火曜日、pazeshun<notifications@github.com>さんは書きました:

> @k-okada <https://github.com/k-okada> わかりにくくて申し訳ないです。ありがとうございます。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1725#issuecomment-227407652>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3OwOqhlshahcxUzFPKs8WiLROhGkks5qN8SmgaJpZM4I4StJ>
> .
>


-- 
--
◉ Kei Okada

**Comment by knorth55** [comment]
更新しました
今日の朝メールできていましたが会場にはWLANしかないようです。

**Comment by ban-masa** [comment]
圧力センサの予備は数が不足してるので岡田先生の出発に間に合えば持ってこれますし、そうでないと無理という状況です。すみません。

**Comment by pazeshun** [comment]
@ban-masa わかりました。
まあ、壊れる位置にあるわけではないので、大丈夫でしょう。

**Comment by k-okada** [comment]
今回持って行っておけば良かったなというもので、長谷川君の旅行グッズの他に

- 葛根湯
- ウェットティッシュ


On Tuesday, 5 July 2016, Kentaro Wada <notifications@github.com> wrote:

> Closed #1725 <https://github.com/start-jsk/jsk_apc/issues/1725>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/1725#event-712552076>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAeG3Kw7qGrp_Bujb6aluiY7evmBKrwkks5qSel-gaJpZM4I4StJ>
> .
>


-- 
--
◉ Kei Okada
