### ISSUE TITLE
ik->bin entrance :larm :e do dangerous move

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1731]

**Comment by knorth55** [comment]
https://drive.google.com/open?id=0B5DV6gwLHtyJbWlNM0dYenZ3ZUE

**Comment by pazeshun** [comment]
I think `-200` in https://github.com/start-jsk/jsk_apc/blob/stow-task/jsk_2016_01_baxter_apc/euslisp/main-stow.l#L123, https://github.com/start-jsk/jsk_apc/blob/stow-task/jsk_2016_01_baxter_apc/euslisp/main-stow.l#L127, https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/main.l#L202, and https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l#L680 is too big.
I checked this worked for previous vacuum pad, but conditions may be changed like #1721

**Comment by pazeshun** [comment]
I'll check and make PR today.

**Comment by knorth55** [comment]
thzx XD

**Comment by pazeshun** [comment]
`(send *ri* :ik->bin-entrance :larm :e :offset #f(-200 0 -20))`
![screenshot from 2016-06-18 14 41 48](https://cloud.githubusercontent.com/assets/14994939/16169273/e7c8f854-3562-11e6-9e6f-ca311898f09a.png)
`(send *ri* :ik->bin-entrance :larm :e :offset #f(-200 0 50))`
![screenshot from 2016-06-18 14 44 47](https://cloud.githubusercontent.com/assets/14994939/16169285/39cfc24a-3563-11e6-91a4-de0bcb9ecd15.png)
I don't think the collision detector of baxter detect this.

**Comment by pazeshun** [comment]
Also, I found another problem about pose...
`(send *ri* :ik->bin-entrance :rarm :e)`
![screenshot from 2016-06-18 14 32 49](https://cloud.githubusercontent.com/assets/14994939/16169339/b48d60cc-3564-11e6-8f27-704f8036379b.png)
This pose is completely different from before #1721 .

**Comment by pazeshun** [comment]
Left arm collide to Kinect torso when `(send *ri* :move-arm-body->bin :larm :e)`. I think this is root problem of this issue.
I'll fix this.
