### ISSUE TITLE
SIBから出力されるBounding Boxがカメラに平行になる

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1743]
https://github.com/start-jsk/jsk_apc/pull/1560#issuecomment-222342700
https://github.com/start-jsk/jsk_apc/pull/1560#issuecomment-222344151
https://github.com/start-jsk/jsk_apc/pull/1560#issuecomment-222347201
現行のプログラムでは、アプローチの仕方の判定の際に、kiva pod baseと物品のBounding Boxが世界座標系と平行であることを前提としている。kiva pod baseは世界座標系に対し傾いているので、修正が必要ではあるのだが、少なくとも物品のBounding Boxはkiva pod baseと平行に作られないと、うまくアプローチの判定ができないと思われる。
物品のBounding Boxをkiva pod baseに平行に作ることは可能でしょうか。

**Comment by yuyu2172** [comment]
It is possible, but I am not sure if ClusterPointIndicesDecomposer alone can do it.

**Comment by knorth55** [comment]
CPIdecomposerが出しているbounding boxはいつもカメラに対して平行というわけではありません。
クラスタリングの結果の点群が少ないため姿勢を推定できないのではないかとおもいます

**Comment by pazeshun** [comment]
@knorth55 なるほど、知りませんでした。
つまり、Bounding Boxの作られ方は場合によって違うということですね。むしろ動作生成系の方をかなり修正する必要があることがわかりました。
ASTRAだとどうなるのかやってみたいです。

**Comment by pazeshun** [comment]
![screenshot from 2016-06-24 14 49 17](https://cloud.githubusercontent.com/assets/14994939/16329214/f7b945ee-3a1b-11e6-8bbc-9b136902fcad.png)

**Comment by pazeshun** [comment]
上の場合のEus上での物品のcube(Bounding Boxの上下方向最大値、左右方向最大値をとったもの)
![screenshot from 2016-06-24 14 55 25](https://cloud.githubusercontent.com/assets/14994939/16329274/68bc37f6-3a1c-11e6-9412-d2fcf6d18e1a.png)
なお、Binのcubeは以下のようになっている。
![screenshot from 2016-06-24 14 55 54](https://cloud.githubusercontent.com/assets/14994939/16329288/7a087da8-3a1c-11e6-8236-7cb5a254563c.png)
目標物品は服なので、ここまで背が高く評価されるのはよくない。

**Comment by k-okada** [comment]
> SIBから出力されるBounding Boxがカメラに平行になる

PointCloudのframeを変更するノードがjsk_pcl_rosにある気がします．それをかまして，cloudのフレームを/waistとかにすればせば治るはず
@wkentaro

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Will be fixed via https://github.com/jsk-ros-pkg/jsk_recognition/pull/1762

**Comment by wkentaro** [comment]
Please try https://github.com/jsk-ros-pkg/jsk_recognition/pull/1762 @yuyu2172

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/16336399/11b86ed0-3a48-11e6-9ab5-68bd4588d494.png)

**Comment by pazeshun** [comment]
これなら完璧です。

**Comment by pazeshun** [comment]
今日main.launchを回していた限りでは、rviz上での表示は適切でした。
lisp側でできているcubeも適切だったと思います。
