### ISSUE TITLE
Evaluation of new gripper with table top object grasping

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1751]
## TODO
- [x] Data Collection
- [ ] Evaluation
## 実験条件
- 物体のラベルはわかっていない
- 物体はテーブルトップに置かれている
- テーブルのおよその位置はわかっている
- 手先カメラによる物体検出・把持計画を行う(カメラの距離センサの内部・外部パラメータはキャリブレーションされているものとする)
- 物体を斜め45度程度から見下ろすような姿勢で、平面認識によって物体点群のセグメンテーションを行う
- 把持軌道は物体点群の重心位置に対して世界座標系のz方向から下ろす形のみ
## 実験環境

<img src="https://cloud.githubusercontent.com/assets/4310419/16176295/c2800ee6-3645-11e6-826a-6d8737e9894d.png" width="800px" />
## データ形式

```
timestamp,object_name,grasp_success
1466330259.60378667,command_hooks,1
1466330387.503623735,command_hooks,1
1466330259.396935323,oral_b_toothbrush_green,0
1466330286.593173872,oral_b_toothbrush_green,0
1466330314.92586249,oral_b_toothbrush_green,0
1466330341.842221507,oral_b_toothbrush_green,0
1466330369.444693981,oral_b_toothbrush_green,0
1466330396.799466161,oral_b_toothbrush_green,0
1466330423.999258456,oral_b_toothbrush_green,0
```

cc @pazeshun

**Comment by pazeshun** [comment]
@wkentaro ありがとうございます！

**Comment by wkentaro** [comment]
@pazeshun 一応終わりましたが、抜けているものもあります。

- https://drive.google.com/open?id=0B9P1L--7Wd2vYXIxN19FOWs2ZUU
- https://drive.google.com/open?id=0B9P1L--7Wd2vaU15QU4wZjZhdUE

**Comment by pazeshun** [comment]
ありがとうございます

**Comment by knorth55** [comment]
@pazeshun is this finished?

**Comment by pazeshun** [comment]
これは今のところ使用していない実験方式なので、一旦閉じます
