### ISSUE TITLE
圧力センサの閾値の自動キャリブレーション

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1787]

**Comment by ban-masa** [comment]
とりあえずapc-initの時に10秒間ほど掃除機をオンにして吸引時の圧力を取得し、その値 - offsetを閾値にする仕様でどうでしょうか。offsetは 5hPa ~ 10hPaぐらいを考えていますが。

**Comment by pazeshun** [comment]
いいと思います

**Comment by pazeshun** [comment]
Closed via #1793
