### ISSUE TITLE
vgg16 result does not come back

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1810]
mask is ok, but result does not come back...

![mask](https://cloud.githubusercontent.com/assets/9300063/16357974/e58668d6-3b40-11e6-9ccf-3fc0c4f2722e.png)

**Comment by knorth55** [comment]
i pulled master branch of jsk_recognition and did catkin build, but it does not fix

**Comment by wkentaro** [comment]
I'm going to lab in 30 minutes, and will fix this.

**Comment by knorth55** [comment]
fixed via #1829 and https://github.com/jsk-ros-pkg/jsk_recognition/pull/1766
