### ISSUE TITLE
VGG16 net result for 40 objects seems to have bug on running on real time

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1812]
the result is not good.

**Comment by yuyu2172** [comment]
I found a bug(?) today.
VGG did failed to recognize an object, `kleenex_paper_towels`, while verifying.

This is probably the reason why #1823 occured.

**Comment by wkentaro** [comment]
> This is probably the reason why #1823 occured. 

why?

**Comment by yuyu2172** [comment]
My bad. I think two are unrelated.

**Comment by wkentaro** [comment]
I'm going to lab in 30 minutes, and will fix this.
