### ISSUE TITLE
FCN can not segment for some objects even when the setting is simple

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1819]
FCN failed to segment for a brush with this input.
I used the most updated chainermodel. (#1682)

![frame0000](https://cloud.githubusercontent.com/assets/2062128/16362650/7cb23394-3bef-11e6-9103-59c190138da6.jpg)

**Comment by wkentaro** [comment]
Please check

- mean_bgr is subtracted
- image is not so large
- visualized output label image

**Comment by yuyu2172** [comment]
1. mean_bgr is subtracted (already rebased the PR that fixed this)

2. I do not think so. (I did not really get this question)

3. An image below. It failed to separate background and objects. 
![frame0000](https://cloud.githubusercontent.com/assets/2062128/16363211/7deafdfe-3bfe-11e6-8627-3dd8fdbe60fb.jpg)

**Comment by wkentaro** [comment]
Fixed?

**Comment by yuyu2172** [comment]
yes
