### ISSUE TITLE
Baxter drops objects while verifying 

### ISSUE THREAD

**Issue by yuyu2172** [start-jsk/jsk_apc#1823]
Baxter dropped `kleenex_paper_towels` while verifying it.

**Comment by wkentaro** [comment]
Which bin? (I mean which view-hand-pose?)

**Comment by yuyu2172** [comment]
from `bin_D`. 
The arm was `left`.

**Comment by wkentaro** [comment]
I'm going to lab in 30 minutes, and will fix this.

**Comment by yuyu2172** [comment]
:+1:
