### ISSUE TITLE
Merge Stow-task Branch

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#1836]

**Comment by wkentaro** [comment]
Code for Pick task will be merged soon as the PR is proposed here: https://github.com/start-jsk/jsk_apc/pull/1837.
Please rebase origin/master after the merging.

**Comment by knorth55** [comment]
ok

**Comment by wkentaro** [comment]
Merged.

**Comment by wkentaro** [comment]
Closed via #1845
