### ISSUE TITLE
Package name can be changed to be shorter and consistent?

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1883]
- jsk_2015_05_baxter_apc -> jsk_2015_baxter_apc / jsk_apc2015_baxter
- jsk_2016_01_baxter_apc -> jsk_2016_baxter_apc / jsk_apc2016_baxter
- jsk_apc2015_common
- jsk_apc2016_common

I have also hrp2_apc package, so that will be jsk_hrp2_apc?

**Comment by k-okada** [comment]
ideally , jsk_apc should run on any robots, without having robot-specific
program. as for hrp2 , the demo should be run with jsk_apc + rtmros_hrp2 ,
- expected time scale is 2-5 year

--
◉ Kei Okada


2016-09-27 23:57 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
> ideally , jsk_apc should run on any robots, without having robot-specific
program. as for hrp2 , the demo should be run with jsk_apc + rtmros_hrp2 ,
- expected time scale is 2-5 year

So I can't place motion code for hrp2 in this repo?

**Comment by wkentaro** [comment]
@knorth55 @pazeshun any comments?

**Comment by knorth55** [comment]
can be merged to #2027
