### ISSUE TITLE
Renaming euslisp/{PROJECT_NAME} -> euslisp/lib?

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1884]
- [jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc](https://github.com/start-jsk/jsk_apc/tree/master/jsk_2015_05_baxter_apc/euslisp/jsk_2015_05_baxter_apc)
- [jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc](https://github.com/start-jsk/jsk_apc/tree/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc)

We used python style, but we can use simpler naming rule.

**Comment by k-okada** [comment]
euslisp/ is widely used
https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/jsk_perception/euslisp

but i think it's ok to keep this current directly name, as an example of
what happens if someone choose python directory style.

--
◉ Kei Okada


2016-09-27 23:58 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
> but i think it's ok to keep this current directly name, as an example of
what happens if someone choose python directory style.

You see what happens?
I think it is just hard to write code with like 
`(require "package://jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter-interface.l")`,
and that's why I'd like to change it.

**Comment by k-okada** [comment]
> You see what happens?

if we change the directory name, then we'll back to oginal direcoty style
like ->
https://github.com/start-jsk/jsk_apc/tree/0.0.2a/jsk_2014_picking_challenge/euslisp
Then, at  some point, someone will start thinking that why we do not have
nice directory structure like python, and want to change
euslisp/${PROJECT_NAME} style again. like we had a year ago.
But if we keep this directory style and fell that why we need to write such
a long file name, everyday, no one never start thinking that python
structure is better than current one.
Half joke, but half serious.



--
◉ Kei Okada


2016-09-28 14:43 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
> if we change the directory name, then we'll back to oginal direcoty style
like ->
https://github.com/start-jsk/jsk_apc/tree/0.0.2a/jsk_2014_picking_challenge/euslisp

No, we'll change like below, to separate the library and nodes.

- euslisp
  - lib/baxter-interface.l
  - lib/baxter.l
  - main.l
  - main_stow.l

**Comment by wkentaro** [comment]
Originally, the reason why I used the Python style is to use this feature: https://github.com/jsk-ros-pkg/jsk_roseus/pull/379
with this euslisp feature: https://github.com/euslisp/EusLisp/issues/83
But it was not expected the feature is supported, so I decided to rename euslisp/{PACKAGE} to euslisp/lib.

**Comment by wkentaro** [comment]
@pazeshun @knorth55 any comments?

**Comment by pazeshun** [comment]
I have no reason to stick to current naming rules, so it's ok to change.

**Comment by wkentaro** [comment]
Maybe we can change the package construction from 2017 packages.

**Comment by knorth55** [comment]
@wkentaro i'm working on it!
