### ISSUE TITLE
:wait-interpolation-smooth won't finish

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1885]
It never returns.

**Comment by k-okada** [comment]
this should be fixed at ->
https://github.com/start-jsk/jsk_apc/issues/1624#event-681107070
could you check the `time_from_start` of feedback topic?

--
◉ Kei Okada


2016-10-04 12:05 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by pazeshun** [comment]
Oh, sorry. I forgot to check this today.
I'll check this the day after tomorrow. (I won't be in the lab tomorrow)

**Comment by wkentaro** [comment]
It seems fixed in latest jsk_apc, baxtereus, pr2eus.
