### ISSUE TITLE
Intrinsic calibration of astra RGB-D camera

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#1886]
## Concrete Problem

Intrinsic calibration of depth seems insufficient
## TODO
- [ ] Try multiple size checkerboards.

**Comment by wkentaro** [comment]
Closed via #1887

**Comment by knorth55** [comment]
why do you reopen this, and am I still assigned to me?

**Comment by wkentaro** [comment]
The reason why I reopen this is the calibration seems insufficient for depth, and we need to find a new solution (ex. using multiple size checkerboard).

**Comment by wkentaro** [comment]
Now this is tackled by @YutoUchimi at #2122
