### ISSUE TITLE
cron_for_githubで古いｂranchが消えない

### ISSUE THREAD

**Issue by k-okada** [start-jsk/jsk_apc#1916]
んだけど、jsk_apcは動いているように見えるんだけど、なにか変更がひつようだったりしますか？

herokuの右上にある[Open app]というボタンを押すと以下のような表示になるので、なにか変わったのかとも思うんですが、、
```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

手元で走らせると以下のような感じで、branch名もあっていそうなんだけど、消えてくれない
```
$ bundle exec cron-for-github clear --debug --verbose --slug=jsk-ros-pkg/jsk_recognition 
D, [2016-10-22T15:47:24.312886 #23512] DEBUG -- CronForGithub: {"debug"=>true, "verbose"=>true, "namespace"=>"cron_for_github", "slug"=>"jsk-ros-pkg/jsk_recognition"}
I, [2016-10-22T15:47:25.135551 #23512]  INFO -- CronForGithub: ref deleting
I, [2016-10-22T15:47:25.135653 #23512]  INFO -- CronForGithub: {:slug=>"jsk-ros-pkg/jsk_recognition", :ref=>"heads/cron_for_github/cfc69bbb-436d-4787-b5df-431c6fdb869d"}
I, [2016-10-22T15:47:25.976003 #23512]  INFO -- CronForGithub: ref deleted
D, [2016-10-22T15:47:25.976212 #23512] DEBUG -- CronForGithub: CronForGithub
```

**Comment by wkentaro** [comment]
> んだけど、jsk_apcは動いているように見えるんだけど、なにか変更がひつようだったりしますか？

いや、何もしてません。

**Comment by wkentaro** [comment]
いまはブランチ手動で消している感じでしょうか。
<img width="1280" alt="screen shot 2016-10-22 at 9 59 04 pm" src="https://cloud.githubusercontent.com/assets/4310419/19619448/c6aeb674-98a2-11e6-8d63-d97a5126d37a.png">

**Comment by wkentaro** [comment]
ちなみに、テストに失敗したブランチは消えないようになっているかと思います。

**Comment by k-okada** [comment]
GITHUB_ACCESS_TOKEN=XXX bundle exec cron-for-github clear --debug
--verbose --slug=jsk-ros-pkg/jsk_recognition
としないとダメだった．
どっかできえちゃっていたんだな．お騒がせしました．

Close #1916


--
◉ Kei Okada


2016-10-22 15:55 GMT+09:00 Kei Okada <notifications@github.com>:

**Comment by k-okada** [comment]
GITHUB_ACCESS_TOKENがなかったみたい．お騒がせしました．

--
◉ Kei Okada


2016-10-22 22:00 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
良かったです。
