### ISSUE TITLE
:pinch is not good name

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1978]
In current gripper-v5 branch, I categorize grasping styles into three ways: `:pinch`, `:spherical`, and `:cylindrical`.
But based on https://www.eng.yale.edu/grablab/pubs/Odhner_IJRR2014.pdf, I think `:opposed` is better than `:pinch`.
I'll fix this.

**Comment by k-okada** [comment]
you can also check http://ajot.aota.org/Article.aspx?articleid=1889836

鎌倉 矩子、手のかたち手のうごき 、医歯薬出版 (1989/05) is the original book.

--
◉ Kei Okada



2016-12-10 16:48 GMT+09:00 Shun Hasegawa <notifications@github.com>:

**Comment by pazeshun** [comment]
@k-okada Thank you very much for telling me this book.
I have already checked similar book, and concluded that pinch grasp and power grasp are opposite words.
These words are not about hand form, but how strong the grasp is.
So I chose `opposed` for hand form.

**Comment by k-okada** [comment]
I think pinch is using finger tips and power grasp is grasp using palm,
please check again

--
◉ Kei Okada


2016-12-12 17:54 GMT+09:00 Shun Hasegawa <notifications@github.com>:

**Comment by pazeshun** [comment]
> I think pinch is using finger tips and power grasp is grasp using palm

I don't think so. Please see Fig. 1 e on pp. 438 of http://ajot.aota.org/Article.aspx?articleid=1889836

**Comment by k-okada** [comment]
a of Fig 1 is the typical case of power grasp.

--
◉ Kei Okada


2016-12-12 19:25 GMT+09:00 Shun Hasegawa <notifications@github.com>:

**Comment by pazeshun** [comment]
> typical case

I understood. Thank you!

**Comment by pazeshun** [comment]
Closed via #1979
