### ISSUE TITLE
Cannot get rolodex pointcloud

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#1992]
This problem is already known. This issue contains detail of this.
Robot pose, bin contents, raw point clouds and output of FCN:
![screenshot from 2016-12-30 11 12 17](https://cloud.githubusercontent.com/assets/14994939/21558663/f5d7ce90-ce80-11e6-8e68-332822c69749.png)
Depth image of right hand camera(got by `rosrun image_view image_view image:=/right_hand_camera/depth/image _do_dynamic_scaling:=true`):
![screenshot from 2016-12-30 11 12 30](https://cloud.githubusercontent.com/assets/14994939/21558670/0bd710a2-ce81-11e6-990c-1fe9cf78d135.png)

**Comment by wkentaro** [comment]
Nice logging.

## Solutions

1. 2D segmentation on multi camera angles without PointCloud. (MIT did)
2. PointCloud generation with multi camera angles. (Nimbro did)
3. Depth estimation (reconstruction) from RGB. (recently tackled with DNN)

**Comment by wkentaro** [comment]
Moved to https://github.com/start-jsk/jsk_apc/issues/2163
