### ISSUE TITLE
Evaluate Astra Mini S

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2005]
http://shop-orbbec3d-com.3dcartstores.com/Orbbec-Astra-Mini-S_p_41.html のAstra Mini Sを評価したいと思います。

Astra Mini Sの特徴は、その小ささと軽さです。
![dsc_0731](https://cloud.githubusercontent.com/assets/14994939/22498766/ac897694-e89d-11e6-8ec4-8947a2468b4c.JPG)
新グリッパにこれを二つ搭載できるといいなと思っています。

**Comment by pazeshun** [comment]
![screenshot from 2017-02-01 16 13 02](https://cloud.githubusercontent.com/assets/14994939/22498453/e4fdd756-e89b-11e6-9cf0-57cf233c08fc.png)
![screenshot from 2017-02-01 16 15 04](https://cloud.githubusercontent.com/assets/14994939/22498458/e9c13580-e89b-11e6-91a0-851d1b440c18.png)
![screenshot from 2017-02-01 16 15 25](https://cloud.githubusercontent.com/assets/14994939/22498461/ed3b761c-e89b-11e6-9874-523fdf40eb2d.png)
![screenshot from 2017-02-01 16 15 42](https://cloud.githubusercontent.com/assets/14994939/22498463/f030dca4-e89b-11e6-81cd-3f50721b3e2c.png)
![screenshot from 2017-02-01 16 17 18](https://cloud.githubusercontent.com/assets/14994939/22498473/f390bd10-e89b-11e6-8d27-2619c2e27a46.png)
![screenshot from 2017-02-01 16 20 33](https://cloud.githubusercontent.com/assets/14994939/22498474/f6e627a2-e89b-11e6-91fa-da3f0caf75e2.png)

**Comment by pazeshun** [comment]
ちょっと使ってみた感じでは、かなり熱くなるので、何らかの放熱方法（付属の放熱板など）が必須だと感じました。

@knorth55 点群の範囲や綺麗さなど、他のカメラとどのように比較したらいいかわからないので、教えてください。

**Comment by knorth55** [comment]
平面はあまりきれいにとれてない気がするけど（Astra-Sと同じ程度）
pixel size 1で見てみるとぶれてるのがわかる気がする

点群の範囲はdatasheetをみればいいかと
点群のきれいさはノイズがのらないか、物体の後ろに点群が飛んでいかないかとか
現行のAstra-SとSR300とMini Astra-Sでテーブルトップの比較動画をとってくれるとうれしいです

センサ系が同じならAstra-Sと同じような結果になると思うので、今のAstra-Sよりは重さの面では優位になります
ただSR300との比較をきっちりしなきゃダメで、これはぼくもやらなきゃなと思ってはいます（感覚的にはSR300のほうがいいと個人的には思う）

**Comment by knorth55** [comment]
性能を比較してみたところ、Astra SとAstra Mini Sは性能面では同じだと思います。
