### ISSUE TITLE
ARC2017 New Shelf and rack

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2017]
Options
- Buy new Shelf
- Use APC2016 Kiva Pod
- Make our own Shelf

**Comment by knorth55** [comment]
My idea is to buy a new shelf at IKEA or Nitori

**Comment by knorth55** [comment]
Cardboard Shelf: 
https://www.amazon.co.jp/%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E9%9B%91%E8%B2%A8-%E3%82%AF%E3%83%A9%E3%83%95%E3%83%88-%E3%82%B7%E3%82%A7%E3%83%AB%E3%83%95%E3%83%BB%E3%83%A9%E3%83%83%E3%82%AF%E7%94%A8%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E5%8F%8E%E7%B4%8D%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9%E3%80%904%E5%80%8B%E3%82%BB%E3%83%83%E3%83%88%E3%80%91%E3%80%90%E7%B5%84%E7%AB%8B%E4%B8%8D%E8%A6%81%E3%80%91/dp/B005CLHJS8

https://www.amazon.co.jp/%E5%8F%8E%E7%B4%8D%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9-%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB-%E3%82%AF%E3%83%AD%E3%83%BC%E3%82%BC%E3%83%83%E3%83%88-%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B95%E6%9E%9A%E5%85%A5%E3%82%8A-%E3%83%9B%E3%83%AF%E3%82%A4%E3%83%88%C3%97%E3%83%96%E3%83%A9%E3%83%83%E3%82%AF/dp/B00Y80MLF0

**Comment by k-okada** [comment]
IKEAかニトリの候補品はどれかな．

--
◉ Kei Okada


2017-03-14 0:54 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
ざっとみた感じこういうのですかね
ダンボール家具は室岡さんがもっと良いものを前見つけてくれました
cc. @mmurooka

http://m.ikea.com/jp/ja/catalog/products/art/90333957/
http://m.ikea.com/jp/ja/catalog/products/art/50323352/

**Comment by mmurooka** [comment]
ダンボールだと以下のようなものでしょうか．いらなくなったら僕の運搬実験に使えるのかもしれないです．
かっちりした棚を買うならキャスタがついていたほうが輸送が楽な気もするけれど，そういうのが売ってるかわからないのと，
実験中にロボットがぶつかって棚が動くとややこしくなって困るかもしれないですね．
https://www.amazon.co.jp/%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB-%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB-%E6%9C%AC%E6%A3%9A5%E6%AE%B5-W900-%E7%B5%84%E3%81%BF%E7%AB%8B%E3%81%A6%E5%BC%8F-%E5%BC%B7%E5%8C%96%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA/dp/B00CB6EVTW/ref=sr_1_3?ie=UTF8&qid=1489625830&sr=8-3&keywords=%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB+%E6%A3%9A
https://www.amazon.co.jp/%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB%E5%AE%B6%E5%85%B7-%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB3%E6%AE%B5%E3%83%9E%E3%83%AB%E3%83%81%E3%83%A9%E3%83%83%E3%82%AF-%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB-%E3%83%9E%E3%82%AC%E3%82%B8%E3%83%B3%E3%83%A9%E3%83%83%E3%82%AF-%E3%82%B3%E3%83%AC%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%83%A9%E3%83%83%E3%82%AF/dp/B00O8NKX9I/ref=sr_1_10?ie=UTF8&qid=1489625830&sr=8-10&keywords=%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB+%E6%A3%9A
https://matome.naver.jp/odai/2139919195833584001

**Comment by pazeshun** [comment]
Storage Systemのルール上の制約は、

* It must consist of between one and three objects that are physically distinct from the Robot and
that could be reasonably carried by an Amazon Robotics mobile robot. These objects may be bolted
down or otherwise secured in place for the Challenge.
* It must have at least 2 and no more than 10 distinct internal compartments or bins that are clearly
labeled with letters A through J. All items must be stored within these bins.
* The sum of the outer upright bounding box volumes of the object(s) must be no more than 95,000
cubic centimeters. All bins must be contained inside this bounding box. Outer bounding shapes
such as cylinders or pyramids may also be considered.
* It must occupy an area of no more than 5,000 square centimeters, and its length, width, or height
must be no longer than 125 centimeters. It may be placed on top of a table or other supporting
structure.
* It must be static and contain no motors or actuators. It may contain parts such as drawers that
are moved by the robot, provided that these parts start and end the task inside the bounding box
of the Storage System.
* Any sensors contained within the Storage System must be inexpensive, with a total price for all
such sensors of less than $50.
* The same Storage System must be used of the Pick, Stow, and Final Round Tasks.

となっています。

**Comment by pazeshun** [comment]
最も注目すべきは3番目の条件で、95,000cm^3以下の体積のものを使わなければならないということです。
@mmurooka さんがあげてくれた候補の2番目のものは、45cm x 90cm x 30cm = 121500cm^3ということで、制限をオーバーしているように思います。

**Comment by pazeshun** [comment]
4番目の条件を読むと、Storage Systemはテーブルなどの支持構造体においてよく、それらの構造体はStorage Systemには含まれてなさそうです。
しかし、足つきの棚など、支持構造体とStorage Systemが一体となっている場合や、棚のbinの一部のみをStorage Systemとして使用する場合に、どこまでがStorage Systemなのかわからないので、聞いてみます。

**Comment by pazeshun** [comment]
聞いてみました。
> We will draw the border so that what is considered the storage system is as small as could be reasonably defined.  Any material or structure that is immediately in contact with items will certainly be a part of the storage system, then we look for any logical separation to define the end. For example, if you attach legs to a bookcase, then the legs would not count. If you used a tall bookshelf but only two of the bins were used for items, then we would take the outer dimensions of just those bins and not the rest of the bookcase.

ということで、Kiva Podの一部のbinのみを使うとか、段ボール棚の一部を使うとかはできそうです。

**Comment by pazeshun** [comment]
物品サイズは最大で42 x 27 x 14 cmのようなので、棚にしろトートにしろ、開口部からの奥行きは30cm程度でいいのではと思います。高い得点を取ることを目標にするなら、奥行きが深すぎるとあまりいいことなさそうです。

**Comment by pazeshun** [comment]
https://www.amazon.co.jp/%E5%B1%B1%E5%96%84-YAMAZEN-%E3%81%A9%E3%81%93%E3%81%A7%E3%82%82%E5%8F%8E%E7%B4%8D%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9-YTCF3P-BR/dp/B002WJHLSG/ref=sr_1_22?ie=UTF8&qid=1489723323&sr=8-22&keywords=%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E3%80%80%E6%A3%9A
を4個使うと、ぴったり95000cm^3となります。
これを倒して置くというのはどうでしょう。

**Comment by pazeshun** [comment]
https://www.amazon.co.jp/%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB%E5%AE%B6%E5%85%B7-%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB3%E6%AE%B5%E3%83%9E%E3%83%AB%E3%83%81%E3%83%A9%E3%83%83%E3%82%AF-%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB-%E3%83%9E%E3%82%AC%E3%82%B8%E3%83%B3%E3%83%A9%E3%83%83%E3%82%AF-%E3%82%B3%E3%83%AC%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%83%A9%E3%83%83%E3%82%AF/dp/B00O8NKX9I/ref=sr_1_10?ie=UTF8&qid=1489625830&sr=8-10&keywords=%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB+%E6%A3%9A
の上二段のみを使うとか、
https://www.amazon.co.jp/%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB-%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB-%E6%9C%AC%E6%A3%9A5%E6%AE%B5-W900-%E7%B5%84%E3%81%BF%E7%AB%8B%E3%81%A6%E5%BC%8F-%E5%BC%B7%E5%8C%96%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA/dp/B00CB6EVTW/ref=sr_1_2?ie=UTF8&qid=1489723323&sr=8-2&keywords=%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E3%80%80%E6%A3%9A
のbin3つのみを使うとか、
https://www.amazon.co.jp/%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB-%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB-%E3%82%B9%E3%83%AA%E3%83%A0-W700-%E7%B5%84%E3%81%BF%E7%AB%8B%E3%81%A6%E5%BC%8F-%E5%BC%B7%E5%8C%96%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA/dp/B00CB6MM2K/ref=sr_1_11?ie=UTF8&qid=1489723323&sr=8-11&keywords=%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E3%80%80%E6%A3%9A
のbin3つのみを使うなど、
棚の一部を使う作戦もありますが

**Comment by pazeshun** [comment]
おまけ:

https://www.amazon.co.jp/%E5%B1%B1%E5%96%84-YAMAZEN-%E5%8F%8E%E7%B4%8D%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9%E3%82%B9%E3%83%84%E3%83%BC%E3%83%AB-MSS-C29P-DBR/dp/B00J5XYTWS/ref=sr_1_56?ie=UTF8&qid=1489724580&sr=8-56&keywords=%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E3%80%80%E6%A3%9A
x 5 = 81250cm^3

https://www.amazon.co.jp/%E6%AE%B5%E3%83%9C%E3%83%BC%E3%83%AB%E5%AE%B6%E5%85%B7-%E3%82%AD%E3%83%A5%E3%83%BC%E3%83%96%E3%83%A9%E3%83%83%E3%82%AF-%E3%82%B9%E3%82%AF%E3%82%A8%E3%82%A2-%E5%BC%B7%E5%8C%96%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB-%E5%8F%8E%E7%B4%8D/dp/B01GC18TUS/ref=sr_1_21?ie=UTF8&qid=1489723323&sr=8-21&keywords=%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E3%80%80%E6%A3%9A
x 3 = 81000cm^3

https://www.amazon.co.jp/%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E9%9B%91%E8%B2%A8-%E3%82%AF%E3%83%A9%E3%83%95%E3%83%88-%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E3%82%AD%E3%83%A3%E3%83%93%E3%83%8D%E3%83%83%E3%83%88%E3%80%90%E5%AE%8C%E6%88%90%E5%93%81%E3%80%91%E3%80%90%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E3%80%91%E3%80%90%E5%8F%8E%E7%B4%8D%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9%E3%80%91%E3%82%AD%E3%83%A5%E3%83%BC%E3%83%96%E3%83%9C%E3%83%83%E3%82%AF%E3%82%B9-A4%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%AF%BE%E5%BF%9C/dp/B006EDG9IE/ref=sr_1_7?ie=UTF8&qid=1489723323&sr=8-7&keywords=%E3%83%80%E3%83%B3%E3%83%9C%E3%83%BC%E3%83%AB%E3%80%80%E6%A3%9A
x 3 = 94743cm^3

**Comment by pazeshun** [comment]
メモ：
@k-okada から、棚を透明にしたり、鏡を設置したり、光源を設置したりして、認識を助けるような棚を作るというアイディアが出されました。

**Comment by mmurooka** [comment]
こういう棚なら，@pazeshunの挙げている箱を買ったり二号館一階のゴミ捨て場をあさってダンボールを見つけると作れますね．
![vlcsnap-2017-03-21-13h52m44s37](https://cloud.githubusercontent.com/assets/6636600/24133144/fe169d64-0e3d-11e7-957c-3d7c43f73df3.png)

**Comment by knorth55** [comment]
Prototype1: 600x600x260 (cm)

![img_1466](https://cloud.githubusercontent.com/assets/9300063/24329090/efa2e4ca-1236-11e7-82d4-ef07f6527ac8.JPG)
![img_1467](https://cloud.githubusercontent.com/assets/9300063/24329091/efa55c1e-1236-11e7-95e6-06311f9f92ee.JPG)

@wkentaro @pazeshun 
l put this prototype near my desk, so please take a look and give me comments

**Comment by knorth55** [comment]
I realized how small the shelf limitations is.
We can try this task with Fetch, too, or it might be better.

**Comment by pazeshun** [comment]
なるほど。
このような一体型の棚にすると、腕は一本しか使わない(Fetchはそもそも一本腕)感じになりますかね。

**Comment by knorth55** [comment]
larger bin is needed for long items i.e. toilet brush and alminium wrap.

**Comment by k-okada** [comment]
透明にしてみよう

**Comment by pazeshun** [comment]
試しに32個の物体を入れてみました。
![32objects](https://cloud.githubusercontent.com/assets/14994939/24533042/f9ab373e-15ff-11e7-938d-217a50ece178.jpg)
かなり積み重ねないと入らなさそうですね。
物体を取ったときに他物体の山が崩れると棚の外に他物体が飛び出しそうなので、Kiva Podのように入り口の縁に突起をつけるなどの対策が必要そうです。

棚だと難しすぎるかもしれなくて、toteタイプにした方がいいかもしれません。

**Comment by knorth55** [comment]
透明な棚を作ってみたいと思います。
とりあえずプロトタイプなので塩ビ板でいいかなと思います。
https://www.amazon.co.jp/%E5%85%89-%E5%A1%A9%E3%83%93%E6%9D%BF-%E9%80%8F%E6%98%8E-0-5-450-600mm-EB455-1/dp/B00AO17L4S/ref=sr_1_3?ie=UTF8&qid=1491105154&sr=8-3&keywords=amazon%2B%E3%83%97%E3%83%A9%E3%82%B9%E3%83%81%E3%83%83%E3%82%AF%2B%E6%9D%BF&th=1

**Comment by knorth55** [comment]
メモ
棚をどのように配置するか：
- 正面1コ （baxter, fetch, hrp2などが変わらずタスクできる？）
    - 両腕を使えば協調動作ができる（必要あるのか？）
    - 単腕なら簡単だが遅い（？）
- 両腕の前に1コずつ （baxter基準）
    - 両腕を使うが単腕ロボット2つあるのと同じ（協調動作なし）
    - Toteが3種類あるので腕が交差してややこしいかもしれない
-> 分離できるように設計して両方試してみる（？）

棚の向き：
- Kiva podと同じ（出口は横向き）
    - 今まで通りのやりかた
    - テーマとして面白い（？）
- Toteと同じ（出口は上向き）
   - StowとPickが大部分共通化できる
   - 棚からのピッキング -> ばらづみピッキングにテーマ変更（？）
   - Baxterではやりやすい <-> Fetchはやりにくい（？）
-> 議論の必要あり

どのような棚の大きさにするか：
- 大きめのbinを1つと小さめのbinを2つ
    - 上にある写真のイメージ
-> もっと色々アイデアを出してみる必要あり

**Comment by knorth55** [comment]
### Baxter New Pick Env
![baxter_pick_new_env jpg](https://cloud.githubusercontent.com/assets/9300063/24914124/4269a6ba-1f0e-11e7-9f2a-b0d1bf846c50.JPG)

**Comment by knorth55** [comment]
### Transparent Shelf Experiment

There is no effect on point cloud, even if we spot a bright light.
However, when the transparent wall is distorted, point cloud waves.

![tote_with_transparent_cover](https://cloud.githubusercontent.com/assets/9300063/24914164/5e9936fc-1f0e-11e7-9d23-e3c700a51dfa.png)

Video:
https://drive.google.com/open?id=0B5DV6gwLHtyJT1lLYVpmNzhoM3c

**Comment by knorth55** [comment]
Current shelf is too deep. Make a more shallow one.

**Comment by knorth55** [comment]
I will make more shallow shelf.

**Comment by YutoUchimi** [comment]
I took pictures of new racks.
- wooden rack
- metalic rack

Both 2 racks are almost the same height and depth, but metalic rack is a little wider.
If we drill holes in the wooden rack, we can adjust to the tilt of our preference. 

![arc_new_shelf3](https://user-images.githubusercontent.com/22876283/27212491-71567bae-529b-11e7-9eca-b01487c38069.jpg)
![arc_new_shelf2](https://user-images.githubusercontent.com/22876283/27212495-74b3ca86-529b-11e7-9559-497391ab8293.jpg)
![arc_new_shelf1](https://user-images.githubusercontent.com/22876283/27212500-784f514c-529b-11e7-8d3f-e6c95bb8e337.jpg)
![arc_new_shelf4](https://user-images.githubusercontent.com/22876283/27212501-7adbfc80-529b-11e7-910d-a70b639674bd.jpg)

**Comment by knorth55** [comment]
I made new shelf.
New shelf has two small bin and one large bin.
Center one is larger than others.

Center: 500*350*200
Right and Left: 500*300*200
(mm)

![img_1713](https://user-images.githubusercontent.com/9300063/27393588-ad7c4ee0-56e4-11e7-9565-be47d8379eda.JPG)
![img_1714](https://user-images.githubusercontent.com/9300063/27393587-ad69c1e4-56e4-11e7-923b-8ebc0391d8f2.JPG)
![img_1715](https://user-images.githubusercontent.com/9300063/27393586-ad64ff60-56e4-11e7-9aac-bb5de50650a0.JPG)
![img_1717](https://user-images.githubusercontent.com/9300063/27393589-ad940058-56e4-11e7-9c85-c0406241f797.JPG)

**Comment by knorth55** [comment]
The new shelf is done for 3.1.0 release, but it can be another change of shelves in the future.

**Comment by wkentaro** [comment]
Please reopen if it is requested or required.
