### ISSUE TITLE
[Info] ARC2017 rules

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2025]
ARCルールを読んで気になったこと。
* Storage System
  - binの数は2以上10以下
  - アクチュエータを搭載するのはダメ。センサーはつけて良い。
  - センサーの値段の合計は50ドル以下

* Pick
  - 試合開始45分前に試合で使う全物品(32個)と物品情報が与えられる。32個のうち半分は初見の物品。
  - 試合開始15分前に物品は没収される。没収されるまでに物品の写真を撮ったり、物品で練習するのは可。
  - 試合開始10分前（？）にチームの人が棚に物品を詰める、物品の位置は審判によって調整される。
  - だいたいの物体の位置はチームが決められそうだが、8分以内に詰める必要がある。審判からひとつずつ物品を渡され、詰めるスタイル。
  - 試合開始2分前に、オーダーファイルが与えられる。

* Stow
  - ?分前に20個の物体が入ったtoteが与えられ、チームの指示した場所に配置される。
  - tote内の全ての物体をStorageに移す。Storageにtoteから物品を流しこむのはNG。
  - 去年と同じくJSON間違いペナルティーが存在。
  - amnesty toteなる場所があり、そこに入った物体は得点計算時に無視される。JSON間違いによる減点もない

* 考察
  - Pickを有利にするためには、物体をまばらに配置できるよう、binの数と体積を調整するのがよい。
  - Stowを有利にするためには、Storageに大きなbinを一つ作り、そこに全物体を入れるとよい。物体を落とさなければJSONを間違えない。
  - Final Round Taskでは、Stowの後Pickなので、Stowで詰め込み過ぎるとPickで苦戦することが予想される。

物品情報とは、ラベル（ここの物体に固有？）、クラス（本、服、などの抽象くらす）、３Dモデル（きっとメッシュ）、商品説明、画像
オーダーファイルとは、どの段ボール箱に何を入れるか（大ダンボール箱に5個、中に3個、小に2個）

**Comment by wkentaro** [comment]
Please reopen if it is not done yet.
