### ISSUE TITLE
ARC2017 meetings

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2034]
Meeting schedule discussion

**Comment by knorth55** [comment]
@itohdak @Affonso-Gui @YutoUchimi @708yamaguchi 
when can you come to JSK lab? we want to have a meeting on March.

**Comment by YutoUchimi** [comment]
@knorth55 
I can go to JSK lab on March 28th, 29th and 30th.
Also I can go on afternoon of March 26th, but I might be drunk on that day.

**Comment by itohdak** [comment]
@knorth55
I can go on 29th. However, I have to leave there at 3 or 4 o'clock that day.

**Comment by knorth55** [comment]
@YutoUchimi @itohdak @708yamaguchi 
3/26-3/31の間だと基本的に常識的な時間帯であれば北川(@knorth55)か長谷川(@pazeshun)どちらかは73B2にいるので、ふらっと来て少しお話をしましょう。
話すことはそんなに多くないですし4月に入ってもう一度きちんとした話し合いがあると思います。
ただARCが7月なので早めに早めに動いて、4月から本格的に準備をしたいなと思っているのでできれば3月中に一度意思疎通をしたいということです。
