### ISSUE TITLE
Introduce gripper-v5

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2036]
修正必須
* [x] 指が折れたり内部のギアが欠けるのを防ぐ
  * 指の台座とギアを磁石で固定する<-簡易テストでは固定強度の不安が指摘
  * (指に柔軟関節を導入)
  * (Baxter側のソフトウェアで動的なリミットをかける)
* [x] 糸がほどけにくくなるよう、巻き付け回数を上げたり、部品の摩擦係数を上げたりする
  * 吸着パッド関節の糸は、吸着パッド根本にもやい結びして、手先リンクに開けた穴に通す?
  * ~~糸中継器への巻き付けが足りないかもしれない~~
  * 2017/4/10時点で使用している糸だと、もやい結びでは強度が足りない->~~固定方法変える/糸変える~~
    * フロロカーボンの糸だと力がかかった時の伸びが大きい。結び目が安定するまで時間がかかり、それまでは結び目がずれていく
    * POWER PROは表面が滑らかで結び目が滑りやすい
    * [もやい結びの補強版](http://ms-fishing-style.com/knot/bowlineknot)で結び目が滑るのは止まったが、ダイニーマだと糸が伸びていくことが発覚<-キャリブ?トルクベース?<-安定したので様子見
    * ステンレスワイヤロープを使うこともできそう
* [x] 糸がたるんだ時にプーリから外れることがあるのを治す
  * 吸引管根本では、プーリをサーボホーンと同じ半径の円筒にしてしまう?
  * 指用のプーリにサーボに固定したカバーをかぶせる
* [x] 制御基板の位置を変える
* [x] 起動時に直動関節のサーボが入らないことがあるので、治す
  * 発生したりしなかったりでデバッグ困難。入らなかったときに再起動を促すことでとりあえず対処したい
  * 主な原因はボーレートが高すぎたことだった
* [x] 握りこんだ時に指が吸引管にひっかかるのを治す
* [x] 弦巻バネの端を削る
* [x] 評価 (#2018)

修正要望
* [ ] 直動関節の自動キャリブレーションを治したい(タイミングベルトの幅を太くすればよい？)
* [ ] 糸を巻きつける場所の曲率半径が小さすぎて糸が切れやすい場所があるので、治したい
* [ ] 十分に丈夫で劣化しにくい糸を使う
* [ ] 手先がカメラで見えるようにしたい-> #2071 
* [ ] Baxterのグリッパ用電源から電源をとりたい
* [x] Arduino基板と気圧センサの位置を掃除機根本かグリッパ根本にもっていく -> #2111
* [x] Overload ErrorをOFFにし、リミットをサーボ内のものに任せる
  * Overload Errorが発生しなくなった。念の為3本の指のモータのerrorを抑制
* [x] ホースとtubeの間の部品を変更して流路を広げる
* [ ] ホースを短くしてみる

**Comment by wkentaro** [comment]
この左手もつくるとか言ってたけど、新しい棚になったら片手で全部届くとかはない？
それならわざわざ両腕作らなくてもいい気がするんだけど。

**Comment by pazeshun** [comment]
> この左手もつくるとか言ってたけど、新しい棚になったら片手で全部届くとかはない？
> それならわざわざ両腕作らなくてもいい気がするんだけど。

それはありえるかもしれません。ただ、両腕があることでタスクを高速化できるかもしれないので、とりあえずは左手も作る方向で考えてます。

**Comment by pazeshun** [comment]
メモ:
指の回転を減らす(cylindrical graspをなくす)ことで掌を小さくし、棚に手が入りやすくすることもできる

**Comment by knorth55** [comment]
メモ：
接触センサをつけるところの候補
- 吸引パッド（現行のとりかた）
- 指先（指が棚の中まで入るなら）

**Comment by knorth55** [comment]
メモ：
pinch動作でものをとる必要がある？ -> 吸引でとれないもの（鉛筆立て）に対応

**Comment by pazeshun** [comment]
TODOs for gripper-v6 and more
* [ ] グリッパ全体を短くする(直動を短く)
* [ ] 掌の端を削る
* [ ] ホースとtubeの間の部品を変更して流路を広げる
* [ ] ホースを短くしてみる
* [ ] 曲げセンサを試す
* [ ] 接触センサを指につける

**Comment by pazeshun** [comment]
@k-okada 
曲げセンサ割と曲げても大丈夫みたいですね (https://www.youtube.com/watch?v=uBVbvczHNmY)
秋月（の通販）では曲げセンサを取り扱ってなくて、スイッチサイエンスだと以下があります。
https://www.switch-science.com/catalog/508/
https://www.switch-science.com/catalog/126/
今のグリッパの指の大きさを考えると、55mmの方を使いそうです。
秋月の方だと[ピエゾフィルム](http://akizukidenshi.com/catalog/g/gP-05232/)なるものが売ってますが、使い方など不明瞭な点が多いです。
http://www.t-sensor.co.jp/faq/piezo_faq/film/#q6 を見ると、耐圧が低いように見えます。

**Comment by pazeshun** [comment]
Move to #2111
