### ISSUE TITLE
[Recognition] Object classification of new objects (given 45 minutes before the task)

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2037]
## Introduction

ARC2017 has new objects revealed 45 minutes before the challenge.
In that case, it is hard to collect training data and train the network, if we use deep learning approach in particular.
Possibly we can do something innovative to solve this problem.

### Idea1: Class segmentation network

We define *object-class* using existing objects, which is something more abstract than object name: book, cloth, box, transparent, etc.
And just before the challenge, we can define the object-class for newly passed objects.
By doing this, we can detect/segment objects by their object-class, not object-name.

### Idea2: Run multi-gpu

- [ ] Measure how many gpus are required @wkentaro 

Suggested at https://github.com/jsk-ros-pkg/jsk_recognition/pull/2041#issuecomment-293443969

**Comment by wkentaro** [comment]
@yuyu2172 We're planning to release this at 3.2.0, so please try the in-hand recognition with @knorth55  today.

**Comment by yuyu2172** [comment]
@wkentaro 
OK

**Comment by wkentaro** [comment]
It seems that we cannot make it before 3.2.0, so I postpone this part to 3.3.0.

**Comment by wkentaro** [comment]
Resolved by @wkentaro
