### ISSUE TITLE
Pick task: Grasp planning of gripper-v6

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2038]
## Current Pipeline (@2017/3/25):
![grasp_plan_overview](https://cloud.githubusercontent.com/assets/14994939/24321672/7b0c63d0-1195-11e7-8446-6ac4d60de22f.jpg)
* The target object and the bin are described with bounding box

### Idea1
Voxels of the target object -> Primitives -> Grasp planning
Voxels of free space in the bin -> Motion planning

**Comment by wkentaro** [comment]
For me this is done with suction part of gripper by 3.1.0, please reopen or create new issue .
