### ISSUE TITLE
Stow task: Grasp planning of gripper-v6

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2043]
Current method with gripper-v2:
FCN -> Mask -> ExtractIndices -> Euclidean Clustering -> Centroid

This grasp planning is almost same as table top problem.
In that case, deep learning method can be applied.

- Current Method:
    - Pros: Hardware and software is separated.
    - Cons: Low Graspability (?)
- Deep Learning Method: 
    - Pros: High Graspability, Generalized grasping for unknown objects
    - Cons: Hardware Specific (?)

**Comment by knorth55** [comment]
First:
- Grasp Training with parallel gripper
- Grasp Training with vacuum gripper

Second:
- Grasp Training with new gripper, which combines parallel and vacuum method.

**Comment by knorth55** [comment]
Stow task env example.
![img_1677](https://user-images.githubusercontent.com/9300063/26843856-8e4b7d2a-4b2c-11e7-97f8-8eb99511ba1c.JPG)
![img_1678](https://user-images.githubusercontent.com/9300063/26843857-8e4dcc88-4b2c-11e7-91fa-b51e892d33f4.JPG)

**Comment by wkentaro** [comment]
For me this is done with suction part of gripper by 3.1.0, please reopen or create new issue .
