### ISSUE TITLE
Introduce FA-I sensor on grippers

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2047]
Considering of using FA-I tactile sensor for grippers.
https://github.com/start-jsk/jsk_apc/issues/2035#issuecomment-289635159

**Comment by knorth55** [comment]
### Screenshot:
![fai_grippers_rqt_plot](https://cloud.githubusercontent.com/assets/9300063/24795516/8aad665c-1bc4-11e7-86b1-d525782e3d03.png)

### Example

video:

plot:
https://drive.google.com/open?id=0B5DV6gwLHtyJZ21FVzllNGtpQ0k

### Color Example

plot:
https://drive.google.com/open?id=0B5DV6gwLHtyJUzdwVW1VbVlyRGs

**Comment by knorth55** [comment]
## Baxter Implementation

![img_1530](https://cloud.githubusercontent.com/assets/9300063/24810120/2b8a6584-1bfc-11e7-90cb-0d358c5d477f.JPG)

**Comment by YutoUchimi** [comment]
According to https://github.com/RoboticMaterials/FA-I-sensor/issues/8#issuecomment-292546393, the silicon rubber of FA-I sensor is PDMS or Ecoflex.
We can use CAD models linked from http://roboticmaterials.com/rm/support/ if we need.

**Comment by knorth55** [comment]
@YutoUchimi 
thx. Now I'm planning to use parallel gripper with baxter.
Actually the CAD model of RoboticMaterials is not good so that I used drill to expand the screw hole.

**Comment by pazeshun** [comment]
> the CAD model of RoboticMaterials is not good

Maybe this is not correct. 3D printer's accuracy is not always good enough to make good holes

**Comment by knorth55** [comment]
I don't think so. take a look at the gripper. they just use baxter gripper CAD model, but it is not good for product.

**Comment by k-okada** [comment]
@pazeshun let's buy PDMS and Ecoflex.

**Comment by YutoUchimi** [comment]
FA-I sensor can hardly recognize transparent or black object.

Robotic Materials reports sensor characteristics.
http://roboticmaterials.com/rm/product/parallel-gripper-kit-pgbsmall71kit/
![force_distance_color](https://cloud.githubusercontent.com/assets/22876283/24853537/62ce11a0-1e16-11e7-81e6-2a678559bf43.png)

**Comment by 708yamaguchi** [comment]
It depends on pinching motion of the gripper, so we postpone this issue to 3.3.0

**Comment by pazeshun** [comment]
Closed via #2235

**Comment by pazeshun** [comment]
#2241

**Comment by pazeshun** [comment]
Closed via #2246
