### ISSUE TITLE
[Info] Difficult Objects in ARC2017

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2051]

**Comment by pazeshun** [comment]
## Difficult Object List
### What is this

List up difficult object for each task and its reason.
We need to solve these problem.
### Pick task
(From https://github.com/start-jsk/jsk_apc/issues/2018#issuecomment-294545081, https://github.com/start-jsk/jsk_apc/issues/2018#issuecomment-294795224)
- avery_binder
  - Deforms easily
- bath_sponge
  - Air leaks
- burts_bees_baby_wipes
  - Deforms easily (Cap opens)
- colgate_toothbrush_4pk
  - Small
- composition_book
  - Deforms easily
  - Heavy
- duct_tape
  - Hole
- epsom_salts
  - Heavy
- fiskars_scissors
  - Small
- flashlight
  - Small
- hand_weight
  - Heavy

**Comment by wkentaro** [comment]
Moved to https://github.com/start-jsk/jsk_apc/issues/2177 and https://github.com/start-jsk/jsk_apc/issues/2163
