### ISSUE TITLE
Create whole task system: (it must be incomplete)

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2053]
It must be incomplete, but I think sooner is better of creating whole task system.
We have components which can be used in the challenge this year, so could you please do this?

@knorth55 @pazeshun 

We already have below components, and I think it is enough to create a system for challenge this year.
I can't imagine how we should tackle the challenge without seeing result with current our best effort.

- Vaccum gripper
- Object segmentation for ARC2017
- New shelf

**Comment by knorth55** [comment]
Ofcourse.
I can try with env shown in https://github.com/start-jsk/jsk_apc/issues/2017#issuecomment-293280446.
First, i try to do stow task.

**Comment by knorth55** [comment]
Sorry, i made a mistake. I try to do Pick task.

**Comment by knorth55** [comment]
Order json format is incomplete. We need to know more information!

**Comment by wkentaro** [comment]
Is this what ur lookin 4?
https://drive.google.com/open?id=0B9P1L--7Wd2vRTVBRFRqNjU1T2M

**Comment by knorth55** [comment]
Where did you find these files?

**Comment by knorth55** [comment]
Is a json generator program sent from ARC official?

**Comment by wkentaro** [comment]
> Where did you find these files?

It is sent by mail, whose subject is "[ARC] Example pick and stow tasks".

> Is a json generator program sent from ARC official?

As far as I know, no.

**Comment by knorth55** [comment]
> It is sent by mail, whose subject is "[ARC] Example pick and stow tasks".
I searched on gmail but I couldn't find the email...
When did you get the email?

> As far as I know, no.
Thank you. I ask officials to give the program.
(But for meanwhile, i made a simple script to generate json for practice)

**Comment by wkentaro** [comment]
Mar 18, I forwarded.

**Comment by knorth55** [comment]
Done

**Comment by knorth55** [comment]
We still have stow task. I reopened this issue.
