### ISSUE TITLE
@708yamaguchi @YutoUchimi の一週間プロジェクト（１回目）を考える

### ISSUE THREAD

**Issue by k-okada** [start-jsk/jsk_apc#2056]
@708yamaguchi @YutoUchimi 
7/14 中間発表
7/27-31 ARC

- 近接＋接触センサでフィードバックをかけながら物体を把持する　（黒、透明については別途対応する） @708yamaguchi 
--  Fetchの指先にセンサをつけるための３Dプリンタ部品を作る．シリコンをいれて固める
- 人が持っているダンボールの箱を見つけて把持する　（人が来た、人がダンボールを持っている、人がダンボールをこっちに渡そうとしている、といったイベントを検出する） @YutoUchimi 
-- FCNの2017ネットワークにダンボールの箱の画像を追加して学習させる．あるいはyoloでダンボール箱クラスがでるか調べる（ros-indigo-darknet)．これで対象物を検出する
-- TiltLaserを使ったPointCloudでBoundingBoxを出して把持する．まずはPR2で、それができたら、dynamixelでhokuyoを回す
-- ゼミタスクをコンプリートさせる．できるだけセンサ処理でイベントを検出し、動作が繋がるようにする
- 箱を開ける（https://www.youtube.com/watch?v=pdEuFhJit0o）
- 箱に物を綺麗に詰めて、閉じて、テープで止める．
- 料理（ご飯をたく）、片付け、テーブルセッティング．

**Comment by wkentaro** [comment]
@708yamaguchi -> 近接センサ #2111 
@YutoUchimi  -> Stereo + 3Dデータ・セット作成 https://github.com/start-jsk/jsk_apc/issues/2122
