### ISSUE TITLE
Cleanup GitHub labels (put in order)

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2061]
@pazeshun @knorth55 Why don't we cleanup GitHub labels? I think it became too many.

**Comment by knorth55** [comment]
- [ ] bug
- [ ] discussion
- [ ] document
- [ ] duplicate
- [ ] enhancement
- [ ] experiment
- [ ] feature
- [ ] other
- [ ] pkg/jsk_apc2015_common
- [ ] pkg/jsk_apc2016_common
- [ ] pkg/jsk_2015_05_baxter_apc
- [ ] pkg/jsk_2016_01_baxter_apc
- [ ] PR/merge-ok
- [ ] PR/requires-changes
- [ ] PR/wait-for-upstream
- [ ] system/gripper
- [ ] system/pick-task
- [ ] system/recognition
- [ ] system/stow-task
- [ ] test

**Comment by wkentaro** [comment]
Below is my suggestion, what do you think?

- bug
- discussion -> Issue/discussion
- document -> enhancement
- duplicate -> [no label]
- enhancement -> enhancement
- experiment -> Issue/experiment
- feature -> feature
- other -> other
- PR/wait-for-upstream -> PR/wait4upstream
- test -> enhancement

**Comment by wkentaro** [comment]
@pazeshun Please give your thoughts.

**Comment by pazeshun** [comment]
I have no idea.

**Comment by pazeshun** [comment]
I think `test` is needed because testing is independent of real task.

**Comment by wkentaro** [comment]
Now it is fixed.
