### ISSUE TITLE
Question about practical robot model definition

### ISSUE THREAD

**Issue by snozawa** [start-jsk/jsk_apc#2062]
別なところ
https://github.com/start-jsk/rtmros_tutorials/pull/511#issuecomment-295090910
で
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter.l
のおもしろいロボット管理方法を教えていただき、興味がでてきたので質問です。

これはeusのPACKAGEを時期によってかえてることになりますか？
また、ユーザの人はどうやってこれを切り替えたりするんでしょうか？
例えば、`(baxter)`を実行したときに呼ばれるbaxter-robotのクラスはどうやってかえたりしています？

**Comment by pazeshun** [comment]
> これはeusのPACKAGEを時期によってかえてることになりますか？

そうです。


> また、ユーザの人はどうやってこれを切り替えたりするんでしょうか？
> 例えば、(baxter)を実行したときに呼ばれるbaxter-robotのクラスはどうやってかえたりしています？

これは、https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter.l#L3で作られたbaxter-robotクラスが、https://github.com/start-jsk/jsk_apc/blob/master/jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_apc/baxter.l#L4で上書きされています。
eusのPACKAGEはあまり関係無いです。

**Comment by wkentaro** [comment]
@snozawa 
大体、使い方としては、以下のようなことをしていて、eusのパッケージはROSのパッケージと対応させています。
この方が後で同じ名前のクラスをnamespaceを変えて継承などできると考えたためです。
（2015と2016でロボットが変わったため、継承はできていませんが、2017は同じロボットなので継承できると考えています。 @knorth55 が #2057 で取り組んでいるところです。）

```
roseus
> (require "package://jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_ap/baxter.l")
> (setq *baxter* (instance jsk_2016_01_baxter_apc::baxter-robot :init))
> (objects (list *baxter*))

roseus
> (require "package://jsk_2016_01_baxter_apc/euslisp/jsk_2016_01_baxter_ap/baxter-interface.l")
> (jsk_2016_01_baxter_apc::baxter-init)
> (send *baxter* :angle-vector (send *ri* :state :potentio-vector))
> (objects (list *baxter*))
```
