### ISSUE TITLE
Gripper-v2 Broken

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2064]
@pazeshun 
I'm so sorry, but gripper-v2 for right hand is totally broken.
Also, left hand gripper's plate is also broken.

;(

**Comment by knorth55** [comment]
![img_1557](https://cloud.githubusercontent.com/assets/9300063/25295383/3d7e2a14-271e-11e7-8d22-c0f4c038535f.JPG)
![img_1558](https://cloud.githubusercontent.com/assets/9300063/25295392/4210f8fe-271e-11e7-8d19-be514f4bccfb.JPG)

**Comment by pazeshun** [comment]
Oh! I'll fix this

**Comment by knorth55** [comment]
ユニバーサルボードが折れたところ（写真下）は新しいボードに取り替えて完全復旧しました。
3Dプリンタで出した部品が割れたところは（写真上）はテープで巻いて応急処置をしました。

**Comment by pazeshun** [comment]
今サポートを取り除いている最中です

**Comment by knorth55** [comment]
今の応急処置状態のグリッパーで動かしてもいいですか？
あと噂のサポート材とる作業やってみたいです

https://github.com/start-jsk/jsk_apc/pull/2057#issuecomment-297730645

**Comment by pazeshun** [comment]
動かしても大丈夫です。
すでに壊れているので、何かあっても壊れた部分が再度破損するだけなので。
サポート材はほぼとれていると思いますが、仕上げを一緒にやりましょう

**Comment by pazeshun** [comment]
The right gripper is fixed.
