### ISSUE TITLE
Make pick-interface class

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2067]
`jsk_arc2017_baxter/euslisp/pick-main.l` should be formed into `pick-interface`.

`pick-interface` inherits `apc-interface`.

Related: #2057 https://github.com/start-jsk/jsk_apc/pull/2057#issuecomment-298480176

**Comment by wkentaro** [comment]
IMO, this may not necessary, and `apc-interface` in https://github.com/start-jsk/jsk_apc/issues/2068 satisfies our needs.

**Comment by knorth55** [comment]
IMO. it is necessary because we also have stow task.

**Comment by wkentaro** [comment]
Moved to https://github.com/start-jsk/jsk_apc/issues/2068
