### ISSUE TITLE
Install hand camera where it can see grasped objects

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2071]
以前から、グリッパの吸着パッド関節が曲がったときに、グリッパ根元にあるAstraでは手先が見えなくなっていました。
手先が見えるような位置にカメラを持ってくるにはどうすればいいかと考えています。

**Comment by pazeshun** [comment]
試しに、グリッパ側面にAstra Miniをつけてみました。
<img src="https://cloud.githubusercontent.com/assets/14994939/25778966/c36253b4-3347-11e7-9fa7-bcbeb157e223.JPG" width="480px">

storageの上にグリッパを持ってくると、
<img src="https://cloud.githubusercontent.com/assets/14994939/25778993/ac77fb08-3348-11e7-8616-901e3dec5d7d.JPG" height="320px">
以下のような画像が取れます。
<img src="https://cloud.githubusercontent.com/assets/14994939/25779000/f025536e-3348-11e7-86ea-17ad264a0b60.png" width="480px">

グリッパが物品を吸い付けた状態では、
<img src="https://cloud.githubusercontent.com/assets/14994939/25779014/44875a38-3349-11e7-8815-cc7305b6a5ea.JPG" height="320px">
以下のような画像が取れます。
<img src="https://cloud.githubusercontent.com/assets/14994939/25779019/7c8fc9ba-3349-11e7-8a11-233d84a788b4.png" width="480px">
手先に何かがついていることはわかるが、全体像はわからないくらいの状態です。

**Comment by pazeshun** [comment]
グリッパ側面につくカメラ固定台を設計して、発注しました

**Comment by pazeshun** [comment]
板金届きました。
@YutoUchimi gripper-v6の導入と同タイミングで右手のカメラをこのタイプのものに付け替えようと思っています。
その時に手伝ってくれると嬉しいです。

**Comment by YutoUchimi** [comment]
@pazeshun 
了解です。よろしくお願いします。

**Comment by knorth55** [comment]
あまり理解していないんだけど、このカメラがステレオになるわけではないんだよね？

**Comment by knorth55** [comment]
それともカメラは全てこの位置に設置されることになる？
ステレオだと2つのカメラの間の物理的な距離が結構効いてくるから縦に連ねるとうまく見えない可能性もあります
試してみないとわからないけど

**Comment by pazeshun** [comment]
ごめんなさい、明日カメラ固定台を装着した写真を撮って、貼ります

**Comment by knorth55** [comment]
@pazeshun 急がないけど写真貼ってくれると嬉しいです

**Comment by pazeshun** [comment]
すみません、忘れてました。
明日とります

**Comment by wkentaro** [comment]
In my understanding, this will be resolved another way (external camera by @knorth55 ).
Please reopen if this is needed again.
