### ISSUE TITLE
glue stickがうまく取れません。

### ISSUE THREAD

**Issue by 708yamaguchi** [start-jsk/jsk_apc#2081]
https://drive.google.com/open?id=0B-oafUKuYgn_Mk1xLXZDZXM2UTA
rvizの画面は確認していませんが、セグメンテーションがずれているのか、グリッパの姿勢が良くないのかが原因かもしれません。

https://drive.google.com/open?id=0B-oafUKuYgn_MFIxTGxHbjRNa3M
同じことをもう一度してみましたが、今度は何も吸着していないのに、とれたと誤認識してしまいました

**Comment by YutoUchimi** [comment]
glue stickの他に、hanes_socksも試してみたところ、fcnの認識はできているように見えますが、socksより少し上の空間でつかもうとしています。

![segmentation_of_hanes_socks](https://cloud.githubusercontent.com/assets/22876283/25940845/6b9bb66a-3672-11e7-83b4-4b27f9387f30.png)

https://drive.google.com/open?id=0B-oafUKuYgn_eEw2REpWSWpwOUE

**Comment by knorth55** [comment]
The problem is that gripper only approaches from upper side.
The grasping strategy should be more clever as @pazeshun 's bthesis.

**Comment by knorth55** [comment]
Related to https://github.com/start-jsk/jsk_apc/issues/1718

**Comment by wkentaro** [comment]
Please report in https://github.com/start-jsk/jsk_apc/issues/2177
