### ISSUE TITLE
State Machine Controll

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2110]
Related to #2104 

- use smach

**Comment by knorth55** [comment]
I will try it on real robot.
![apc_smach](https://cloud.githubusercontent.com/assets/9300063/26727620/731bdc40-47e2-11e7-82b6-467d137460a0.png)

**Comment by knorth55** [comment]
Updated: 
![arc_state_machine](https://cloud.githubusercontent.com/assets/9300063/26728117/156a7456-47e4-11e7-96c9-4225fd8ef9c4.png)

**Comment by k-okada** [comment]
nice.
one advantage of using smach is that support hierarchical state machine,
please check that.

--
◉ Kei Okada


2017-06-02 22:38 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
I read hierarchical state machine.
http://wiki.ros.org/smach/Tutorials/Create%20a%20hierarchical%20state%20machine
Right arm and left arm process can be nested in one state machine, but the problem is that when right arm is picking a object, left arm have to wait and vice versa.
I'm not familiar with `smach` so I made `state_server.py` which check both arms states, and determine which arm can start picking.

**Comment by knorth55** [comment]
stow task state machine
![arc_stow_state_machine](https://user-images.githubusercontent.com/9300063/26961861-fa8641c2-4d1c-11e7-8064-d337b749c035.png)
