### ISSUE TITLE
Introduce gripper-v6 with pinching motion

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2111]
gripper-v5 + [flex sensor](https://www.switch-science.com/catalog/508/) + [proximity sensor](https://roboticmaterials.com/rm/product/single-sensor-evaluation-kit/) -> gripper-v6

**Comment by pazeshun** [comment]
@pazeshun
* ハードウェア全体を作る
  * [ ] 右手組み立て
  * [ ] 左手部品購入
  * [ ] 左手組み立て
* 曲げセンサを用いたピッキング動作を作る

**Comment by pazeshun** [comment]
@708yamaguchi 
* 近接センサを扱う回路とファームウェアを作る
* Fetchで近接センサを使ってみて、gripper-v6でもできそうな手探り動作を調べる

**Comment by pazeshun** [comment]
今週中に、右腕にgripper-v6を着けた状態でpick_main.launchを動かせるように頑張ります

**Comment by knorth55** [comment]
'This week' you mean until this Saturday?
I think it is too hard.
You should not be too rushed. Feel free to make an achievable goal for you.

**Comment by wkentaro** [comment]
Right hand without pinching motion is done by 3.1.0

**Comment by wkentaro** [comment]
Closed via https://github.com/start-jsk/jsk_apc/pull/2203
