### ISSUE TITLE
:fold-pose-back changes robot model in baxter-interface

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2139]
@knorth55 
https://github.com/start-jsk/jsk_apc/blob/master/jsk_arc2017_baxter/euslisp/lib/baxter-interface.l#L161
で、実機の状態のコピーであるはずのモデルを変更したままにしているのと、`*baxter*`が変更されないのは、バグの元になるかも知れません。

**Comment by pazeshun** [comment]
このメソッドが必要なら、`*ti*`に移すのがいいかもしれないです

**Comment by wkentaro** [comment]
Closed via https://github.com/start-jsk/jsk_apc/pull/2140
