### ISSUE TITLE
Sparkfunの新しい近接センサを使えるようにする

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2143]
@708yamaguchi
今日できなかったので、一旦保留にしましょう。
僕が進めるので、センサと回路のセットを貸してください

**Comment by 708yamaguchi** [comment]
あの後、何とか値が読めるようになりました。
明日5個一気に読めるようにしようと思っています。

**Comment by pazeshun** [comment]
Closed via #2147
