### ISSUE TITLE
KDTree error in stow task

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2157]
When I tested stow task with #2155 , I got the following error in `baxter.launch` after I launched `stow.launch`
```
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
```
This error continued until I killed `stow.launch`
But the robot performed recognition and picking well.

**Comment by knorth55** [comment]
This error occurs when there is no pointcloud input.
This is because we use attention clipper.
When camera look inside tote, the error doesnt happen.
I think it is not a big problem.

**Comment by pazeshun** [comment]
I understand. Thanks!

**Comment by knorth55** [comment]
I think this PR https://github.com/jsk-ros-pkg/jsk_recognition/pull/2120 suppresses this error output.
We need to check with real robot.
