### ISSUE TITLE
State machine suddenly stops in pick task

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2158]
In
https://drive.google.com/open?id=0BxxBA3J-CunGWkJiSS0xOWxWMzg
https://drive.google.com/open?id=0BxxBA3J-CunGR0kwdzJFTEZtY0U
https://drive.google.com/open?id=0BxxBA3J-CunGZ2JHSWVnVXhLcWM
,
motion suddenly stoped even when the robot didn't complete task.
Sorry, but I couldn't get log...

**Comment by knorth55** [comment]
@pazeshun  Please reopen when it happens again.
