### ISSUE TITLE
[Listing] Capability of 3D Object Semantic Segmentation

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2163]
## 3D cloud insensible

- 24: mesh_cup

## 2D segmentation

- [x] 00: __background__
- [ ] 01: avery_binder
- [ ] 02: balloons
- [ ] 03: band_aid_tape
- [ ] 04: bath_sponge
- [ ] 05: black_fashion_gloves
- [ ] 06: burts_bees_baby_wipes
- [x] 07: colgate_toothbrush_4pk
- [x] 08: composition_book
- [x] 09: crayons
- [x] 10: duct_tape
- [x] 11: epsom_salts
- [ ] 12: expo_eraser
- [ ] 13: fiskars_scissors
- [ ] 14: flashlight
- [x] 15: glue_sticks
- [x] 16: hand_weight
- [x] 17: hanes_socks
- [x] 18: hinged_ruled_index_cards
- [ ] 19: ice_cube_tray
- [x] 20: irish_spring_soap
- [x] 21: laugh_out_loud_jokes
- [ ] 22: marbles
- [ ] 23: measuring_spoons
- [ ] 24: mesh_cup
- [ ] 25: mouse_traps
- [ ] 26: pie_plates
- [ ] 27: plastic_wine_glass
- [ ] 28: poland_spring_water
- [x] 29: reynolds_wrap
- [ ] 30: robots_dvd
- [ ] 31: robots_everywhere
- [x] 32: scotch_sponges
- [ ] 33: speed_stick
- [ ] 34: table_cloth
- [x] 35: tennis_ball_container
- [x] 36: ticonderoga_pencils
- [x] 37: tissue_box
- [x] 38: toilet_brush
- [ ] 39: white_facecloth
- [x] 40: windex
- [x] 41: __shelf__

@pazeshun Please fill in when possible.

**Comment by pazeshun** [comment]
I'll add information while testing

**Comment by knorth55** [comment]
## Test on Stow

![image](https://user-images.githubusercontent.com/9300063/27539749-a767e924-5ab8-11e7-933a-e56070f75e32.png)

The red tote is recognized as hanes socks, so please fix this @wkentaro . (commented by @wkentaro )

**Comment by knorth55** [comment]
I did a brief test.
https://drive.google.com/open?id=0B5DV6gwLHtyJaUVEbmhjMlIzaXc

**Comment by wkentaro** [comment]
Thanks.
