### ISSUE TITLE
[Recognition] Richly annotated object segmentation dataset for ARC2017 known objects

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2172]
- [x] Collect raw data (@YutoUchimi) [link](https://drive.google.com/open?id=0B1waEZT19wijeVY5bk45TDdpbFU)
- [x] Implement Kinfu texture model generation (@wkentaro)
- [ ] Generated Kinfu texture model for 40 known objects
- [ ] Annotate Kinfu texture model for collected data

**Comment by wkentaro** [comment]
It seems this is too hard to complete before 3.1.0, so I rescheduled for 3.2.0. Let's finish it in this week. @YutoUchimi

**Comment by knorth55** [comment]
can you paste dataset links?

**Comment by YutoUchimi** [comment]
>  Collect raw data (@YutoUchimi)

dataset_jsk_v3 is here.
https://drive.google.com/open?id=0B1waEZT19wijeVY5bk45TDdpbFU

**Comment by wkentaro** [comment]
@YutoUchimi Please notify me when you finish collecting mesh data for left objects? 

- [x] 36 objects
- [ ] 4 objects (transparent, reflective)

**Comment by YutoUchimi** [comment]
I added mesh data to google drive. (Sorry for not zipping...)
https://drive.google.com/open?id=0B1waEZT19wijMWFxU0NxelRhUjA

Mesh model of marbles is good, and poland_spring_water so-so.
But I could collect mesh model of wine_glass nor mesh_cup successfully, even though I used fused depth image. Probably we have to create eus-model or similar one of those objects.

**Comment by YutoUchimi** [comment]
Oh, I also added mesh models of balloons and bath_sponge. (link is shown above)
We can use them if we need.

**Comment by wkentaro** [comment]
Due to mis-calibration of baxter or camera, it is difficult to use current raw data, so I need to postpone this issue to 3.3.0.
This is addressed by https://github.com/start-jsk/jsk_apc/pull/2217.

**Comment by wkentaro** [comment]
I found current slam-algorithm or camera-calibration is not applicable for this application, and changed the milestone to untargetted.
See below for detailed results:
- Multi-view dataset: https://github.com/start-jsk/jsk_apc/pull/2273
- Slam by Kinfu: https://github.com/start-jsk/jsk_apc/pull/2288
