### ISSUE TITLE
[Listing] Capability of Gripper to Grasp Objects

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2177]
**Spread Sheet**: https://drive.google.com/open?id=1v0OBgbFSV4aG7sSmQi4leB5lTJkE224dzth9n1y3LKo

![image](https://user-images.githubusercontent.com/4310419/28081484-6068812a-66aa-11e7-9630-cbca7aa41911.png)

## List (see spread sheet)

- 00: __background__
- [ ] 01: avery_binder
- [x] 02: balloons
- [ ] 03: band_aid_tape
- [x] 04: bath_sponge
- [x] 05: black_fashion_gloves
- [x] 06: burts_bees_baby_wipes
- [x] 07: colgate_toothbrush_4pk
- [x] 08: composition_book
- [x] 09: crayons
- [ ] 10: duct_tape
- [x] 11: epsom_salts
- [x] 12: expo_eraser
- [ ] 13: fiskars_scissors
- [ ] 14: flashlight
- [ ] 15: glue_sticks https://github.com/start-jsk/jsk_apc/issues/2081
- [ ] 16: hand_weight
- [x] 17: hanes_socks
- [x] 18: hinged_ruled_index_cards
- [ ] 19: ice_cube_tray
- [x] 20: irish_spring_soap
- [x] 21: laugh_out_loud_jokes
- [ ] 22: marbles
- [ ] 23: measuring_spoons
- [ ] 24: mesh_cup
- [ ] 25: mouse_traps
- [ ] 26: pie_plates
- [ ] 27: plastic_wine_glass
- [ ] 28: poland_spring_water
- [ ] 29: reynolds_wrap
- [x] 30: robots_dvd
- [ ] 31: robots_everywhere
- [x] 32: scotch_sponges
- [x] 33: speed_stick
- [ ] 34: table_cloth
- [x] 35: tennis_ball_container
- [x] 36: ticonderoga_pencils
- [x] 37: tissue_box
- [ ] 38: toilet_brush
- [ ] 39: white_facecloth
- [ ] 40: windex
- 41: __shelf__

**Comment by pazeshun** [comment]
What is gripper version?
It seems you tested with gripper-v4, so should I add gripper-v6 information?

**Comment by knorth55** [comment]
@pazeshun 's work
https://github.com/start-jsk/jsk_apc/issues/2018#issuecomment-294795224

**Comment by 708yamaguchi** [comment]
全物品をpinchした動画と、suctionとpinchの難しさの表を
https://drive.google.com/open?id=0B-oafUKuYgn_MFNqeUFtenlHN28
に置きました。
1が簡単で3が難しいです。
suctionのデータは
https://github.com/start-jsk/jsk_apc/issues/2018#issuecomment-294795224
のままです。

**Comment by knorth55** [comment]
>全物品をpinchした動画と、suctionとpinchの難しさの表を

I made a new dir and put a spreadsheet.
https://drive.google.com/open?id=0B5DV6gwLHtyJZVNVNGpDTjRrMUU
https://drive.google.com/open?id=1v0OBgbFSV4aG7sSmQi4leB5lTJkE224dzth9n1y3LKo

**Comment by 708yamaguchi** [comment]
ありがとうございます！

**Comment by knorth55** [comment]
@708yamaguchi can you make a PR to put euslisp code for this test?

**Comment by knorth55** [comment]
NOT DONE: suction test for Wine glass and Windex

**Comment by 708yamaguchi** [comment]
suction and pinchでいくつかの物品を掴んでみました。
https://drive.google.com/open?id=0B-oafUKuYgn_YWVWQzlfcE15U2M

composition bookやrobots everywhereは端を掴むと安定して把持できました。
avery binderも、開く側を掴むと把持できました。

**Comment by 708yamaguchi** [comment]
graspabilityの欄に、grasp methodという列を追加しました。
各物品に対してどの把持方法が最も掴みやすそうか書いています。
これからも更新していく予定です。

**Comment by knorth55** [comment]
>NOT DONE: suction test for Wine glass and Windex

can you try these two suction test and fill the list?
and also can you list up grasp method which can never grasp the object?

**Comment by wkentaro** [comment]
Its done. Please reopen this if not.
