### ISSUE TITLE
[Recognition] Introduce in-hand recognition to task system

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2187]

**Comment by knorth55** [comment]
![frame0004](https://user-images.githubusercontent.com/9300063/27840588-385a3b94-6135-11e7-9c25-5d8fe2a90871.jpg)

**Comment by knorth55** [comment]
I finished to test and add `in_hand_recognition.launch`.
Now I move to implement in-hand recognition to  both task systems.

**Comment by knorth55** [comment]
@wkentaro @yuyu2172 we need to discuss more whether we need in-hand recognition.

**Comment by yuyu2172** [comment]
@knorth55  @wkentaro 

I extended the model for in hand recognition to work for detection.

https://github.com/yuyu2172/arc/blob/master/notebooks/FewShotDetection.ipynb

This model takes an image as input and returns bbox, labels and scores.

**Comment by wkentaro** [comment]
It's done and launched in `grasped_region_classifier.launch`.
