### ISSUE TITLE
MoveIt path constraints for pinching

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2211]
Currently I have no idea about this.
If I have problem in #2203 , I'll report in details.

**Comment by knorth55** [comment]
Can you explain more?

**Comment by pazeshun** [comment]
gripper-v6で挟み込み把持すると、吸着の時のように常に方向を固定できる座標系がなくなってしまうので、どうpathを拘束すればいいのか考えていましたが、拘束なしでやってみたところ、今のところ腕を振り回すことなく動いているので、とりあえず大丈夫です。

**Comment by pazeshun** [comment]
やっぱり、腕を振り回してしまいました。

**Comment by k-okada** [comment]
振り回した時の
- プランナ rrt? birrt? rrt* ?
- コンストレイント
をメモっておいてくれると嬉しいです．また、初期姿勢、目標がわかって、再現できるといいんだけど．


--
◉ Kei Okada


2017-07-05 17:04 GMT+09:00 Shun Hasegawa <notifications@github.com>:

**Comment by knorth55** [comment]
plannerはRRTです
constraints1は特に何も指定していないです。
path-constraintsのorientation-constraintsをうまく設定しなければならないはずです。
物をもったあとできるだけ物体の姿勢を変更せずに運搬することが目的です

**Comment by knorth55** [comment]
we can solve path with `right_gripper_palm_endpoint`, but it requires 50 seconds to execute.

**Comment by knorth55** [comment]
I add FIXME and disable moveit in placing motion. #2251

**Comment by wkentaro** [comment]
Please reopen when you need this again.
