### ISSUE TITLE
place-object and recognize-object almost collide in pick task

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2212]
段ボール箱がロボットの真正面にあるので、place-objectで伸びている腕の下側にrecognize-objectの腕が動こうとして、かすりました。

**Comment by pazeshun** [comment]
かするのが正常ということであれば、無視しようかと思います。

**Comment by pazeshun** [comment]
動かしてる回数が少なく、情報不足で変えるべきかどうか判断できません。
危険な場面に遭遇したら教えてください

**Comment by pazeshun** [comment]
動画を見たら、危険なぶつかり方をしていたので、 #2203 で直します

**Comment by wkentaro** [comment]
Closed via https://github.com/start-jsk/jsk_apc/pull/2203
