### ISSUE TITLE
Calibrate baxter arm joints

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2219]
Possibly this causes error in grasping and segmentation.

**Comment by pazeshun** [comment]
http://sdk.rethinkrobotics.com/wiki/Arm_Calibration
I think this calibrates torque sensor and spring, not joint states.
So I'm not sure this will solve issue.

However, calibration should be done, I think.

**Comment by knorth55** [comment]
First, let's do this calibration in this week.

**Comment by pazeshun** [comment]
Done
