### ISSUE TITLE
Make additional fingers, finger bases and gears

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2220]
In case of breaking grippers
- [x] Print additional fingers, finger bases and gears (fix magnet fitting)
- Mold rubber to fingers
  - [x] Vytaflex
  - [x] Sylgard
- [x] Print additional other parts
- [ ] Compose additional robot palm (x2)

**Comment by wkentaro** [comment]
I think it is done. Please reopen if not.
