### ISSUE TITLE
[Schedule] Baxter Time Schedule

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2248]
Operating time of Baxter is now scheduled on google drive.
Please write down when you want to use.
Max time in line is 2 hours.

https://docs.google.com/a/jsk.imi.i.u-tokyo.ac.jp/spreadsheets/d/17eQm1whC2TqTE-SV5MjmI9mvu4RZxl6Asi1RbWL0rNQ/edit?usp=sharing

**Comment by knorth55** [comment]
明日の16時から18時で予約しました

**Comment by pazeshun** [comment]
今日の18時から20時まで予約しました。

この時に、
・左手を新グリッパに換装
・右手の曲げセンサの修理
を行う予定です。
左手が旧グリッパの方が都合がいい作業が残ってる場合は、教えてくれれば換装を延期します。

**Comment by pazeshun** [comment]
今から12時までBaxter使います

**Comment by wkentaro** [comment]
その後使います。

**Comment by 708yamaguchi** [comment]
11:30~12:30
使います

**Comment by pazeshun** [comment]
その後、13:00~15:00まで使います

**Comment by 708yamaguchi** [comment]
15:00~16:30
使います

**Comment by 708yamaguchi** [comment]
15:00~17:00
使います
