### ISSUE TITLE
[Experiments] Practice of pick and stow tasks

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2267]
Please write log here: https://docs.google.com/spreadsheets/d/1MVjJlFlvHsXIW0C9Mh_SUZBw8WnAELIL9FNWofNd5N8/edit#gid=0, and put data files to link on the data sheet.
It looks like below:
![image](https://user-images.githubusercontent.com/4310419/28150992-f5f48102-67d2-11e7-90d2-6fb4ce8f15e1.png)

**Comment by knorth55** [comment]
@708yamaguchi @YutoUchimi 
Please generate new JSON and try different environment! 
https://github.com/start-jsk/jsk_apc/pull/2270

**Comment by wkentaro** [comment]
Please practice tomorrow, too.
