### ISSUE TITLE
The gripper occludes objects at overlook-pose

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2290]
<img src=https://user-images.githubusercontent.com/4310419/28227091-7629f398-6913-11e7-9750-e71ffcb97e9a.jpg width=50%><img src=https://user-images.githubusercontent.com/4310419/28227092-762b2ad8-6913-11e7-9a4b-6f47c2f4e260.jpg width=50%>

without gripper:

<img src="https://user-images.githubusercontent.com/4310419/28226972-fbc8546e-6912-11e7-9970-e0cbd0748fa8.jpg" width=50%><img src=https://user-images.githubusercontent.com/4310419/28226971-fbc7e0d8-6912-11e7-885c-985cde47d22e.jpg width=50%>

**Comment by pazeshun** [comment]
これは、カメラ位置を上方向にずらせば解決する問題でしょうか。
もしそうなら、ずらせないことはないので、どれくらいずらせばいいのか教えてください

**Comment by pazeshun** [comment]
https://github.com/start-jsk/jsk_apc/issues/1929#issuecomment-262912958 と比較すると、Astra Sの時より見えてない気がしました。
そこで、カメラ固定台を比較して見たところ、Astra Sのものより高さが低くなってしまっていることが判明しました。
![dsc_1082](https://user-images.githubusercontent.com/14994939/28235619-a9d12f66-694c-11e7-9ed1-69d9d4a0c11c.JPG)
アルミ板を追加して、高さを上げることを試みます。

(メモ)カメラを40mm上に上げると、去年の状態以上の視野を確保できそうだが、剛性、重量など心配

**Comment by pazeshun** [comment]
追加部品を作りました。
明日、Baxterを誰も使っていないときに試してみます。

**Comment by pazeshun** [comment]
![screenshot from 2017-07-16 11 28 36](https://user-images.githubusercontent.com/14994939/28244048-54b5a0ba-6a1a-11e7-976d-8c1a02d0bb64.png)

**Comment by wkentaro** [comment]
これで大丈夫じゃないでしょうか。
いちど、overlook-poseのoffsetを変えてみて、結果を貼ってもらえますか。

**Comment by pazeshun** [comment]
左手のカメラ位置も上げました。
次にやるべきことは、左手のカメラの外部パラメータキャリブと、overlook-poseのoffset変更です。

**Comment by pazeshun** [comment]
|/left_hand_camera/left|/left_hand_camera/right|
|---|---|
|![screenshot from 2017-07-22 14 07 51](https://user-images.githubusercontent.com/14994939/28488533-63e22082-6ee7-11e7-81f4-091a200001c1.png)|![screenshot from 2017-07-22 14 07 56](https://user-images.githubusercontent.com/14994939/28488534-6a4ebb24-6ee7-11e7-92ef-ceb917078856.png)|
@YutoUchimi @wkentaro

**Comment by YutoUchimi** [comment]
https://github.com/start-jsk/jsk_apc/pull/2368 でoverlook-poseのoffsetを調整しました。

**Comment by wkentaro** [comment]
nice nice
