### ISSUE TITLE
持っていくものリスト

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2360]
- 工具
  - [ ] パテ (@pazeshun)
  - [ ] アロンアルファ (@pazeshun)
  - [ ] アラルダイト (@pazeshun)
  - [ ] 万能ハサミ (@pazeshun)
  - [x] はんだごて (@pazeshun)
  - [ ] 養生テープ (@pazeshun)
  - [x] 養生テープ (@YutoUchimi)
  - [ ] 紙ガムテープ (@pazeshun)
  - [x] 紙ガムテープ (@YutoUchimi)
  - [ ] 布ガムテープ (@pazeshun)
  - [x] 布ガムテープ (@YutoUchimi)
  - [ ] ビニールテープ (@pazeshun)
  - [x] ドライバー (@pazeshun)
  - [ ] 六角レンチ (@pazeshun)
  - [x] ペンチ、ニッパー (@pazeshun)
  - [x] ハサミ (@pazeshun)
  - [ ] ワイヤストリッパ (@pazeshun)
  - [ ] Baxter組み立て用の工具(モンキーレンチなど) (@pazeshun)
  - [ ] 油性マジック (@pazeshun)
  - [x] 文房具 (@pazeshun)
  - [ ] メジャー (@pazeshun)
  - [x] 両面テープ (@pazeshun)
  - [x] グルーガン (@pazeshun)
  - [x] ハンドドリル (@pazeshun)
  - [x] バンドソー (@pazeshun)
  - [ ] ピンセット (@pazeshun)
- 材料
  - [ ] APC部品箱(ねじなど) (@pazeshun)
  - [ ] 割り箸 (@pazeshun)
  - [ ] コード (@pazeshun)
  - [ ] モータ (@pazeshun)
  - [ ] ユニバーサル基板 (@pazeshun)
  - [ ] はんだ (@pazeshun)
  - [ ] はんだ吸い取り線 (@pazeshun)
  - [ ] Arduino予備 (@pazeshun)
  - [ ] 圧力センサ予備 (@pazeshun)
  - [ ] ホース予備 (@pazeshun)
  - [ ] 釣り糸 (@pazeshun)
  - [ ] ダイニーマ2mm (@pazeshun)
  - [ ] 結束タイ (@pazeshun)
  - [ ] スパイラルチューブ (@pazeshun)
  - [ ] アルミ板 (@pazeshun)
- ロボット本体
  - [ ] Baxter
  - [ ] グリッパ本体 (@pazeshun)
  - [ ] グリッパ予備 (@pazeshun)
  - [ ] DXHUB予備 (@pazeshun)
  - [ ] 曲げセンサ予備 (@pazeshun)
  - [ ] 掃除機 (@pazeshun)
  - [ ] 掃除機駆動回路 (@pazeshun)
  - [ ] 掃除機駆動回路予備 (@pazeshun)
  - [ ] 扇風機 (@knorth55)
  - [ ] 秤 (@pazeshun)
  - [ ] Astra S x2 (@knorth55)
  - [x] ASTRA MINI S (@YutoUchimi)
  - [x] ASTRA MINI S 放熱フィン・シート (@YutoUchimi)
  - [x] ASTRA MINI S予備 (@YutoUchimi)
  - [ ] Baxter Firmware Update USB (@knorth55)
  - [ ] Keyboard (@wkentaro)
  - [ ] 非常停止スイッチ (@knorth55)
- タスク環境
  - [ ] 棚 
  - [ ] 台車 
  - [ ] ラック 
  - [ ] 段ボール箱
  - [ ] トート
- 配線
  - [x] USBハブ (@YutoUchimi)
  - [x] USBハブ予備 (@YutoUchimi)
  - [x] USB延長ケーブル (@YutoUchimi)
  - [x] USB延長ケーブル予備 (@YutoUchimi)
  - [x] 電源付きUSB延長ケーブル (@YutoUchimi)
  - [ ] 電源付きUSB延長ケーブル予備 (@YutoUchimi)
  - [x] ASTRA MINI Sケーブル予備 (@YutoUchimi)
  - [x] Arduino用mini USB-USB変換ケーブル予備 (@YutoUchimi)
  - [x] DXHUB用micro USB-USB変換ケーブル予備 (@YutoUchimi)
  - [ ] グリッパ用ACアダプタ (@pazeshun)
  - [x] 電源タップ (@708yamaguchi)
  - [x] 5m 電源延長コード (@708yamaguchi)
  - [ ] 変圧器 (@knorth55)
  - [x] Ethernetケーブル (@708yamaguchi)
  - [x] Ethernetケーブル予備 (@708yamaguchi)
  - [x] LANハブ (@708yamaguchi)
  - [x] LANハブ予備 (@708yamaguchi)
  - [x] グリッパ用電源(@708yamaguchi)
  - [x] baxter用電源(@708yamaguchi)
  - [x] sheeta用電源(@708yamaguchi)
- PC
  - [ ] ThinkPad P50 x 2 (@yuyu2172, @wkentaroが@iory, @otsuboからかりる?)
  - [ ] マウス (@wkentaro)
  - [ ] Desktop PC (sheeta) (@knorth55)
  - [ ] Desktop PC (hoop) (@wkentaro)
  - [ ] Titan X (@knorth55)
  - [ ] Display's display (@708yamaguchi)
  - [ ] Display's stand (@708yamaguchi)
- その他
  - [x] GoPro (@708yamaguchi)
  - [ ] iPhone ジンバル (@knorth55, @pazeshun )
  - [x] Calib board (@YutoUchimi)
  - [ ] 三脚 (@YutoUchimi)
  - [x] 三脚用スマホアタッチメント (@YutoUchimi)
  - [x] 新幹線チケット (@708yamaguchi)
  - [x] ホテル予約書類 (@708yamaguchi)
  - [x] 誓約書 (@708yamaguchi)

**Comment by pazeshun** [comment]
業者に持って行ってもらう物品も含んでいます。

**Comment by wkentaro** [comment]
Please reopen when you have left objects in the lab. I will bring it.
