### ISSUE TITLE
Pinch standing flat objects near walls

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2365]
壁に立てかけられているバインダーや本を取りたい

**Comment by pazeshun** [comment]
壁沿いの領域では、指を壁に向けるよう、rpyを#f(0 0 0), #f(pi/2 0 0), #f(pi 0 0), #f(-pi/2 0 0)から選択してIKを解く。

**Comment by pazeshun** [comment]
@708yamaguchi こちら、僕がやります

**Comment by pazeshun** [comment]
#2367 でつかみやすくなったと思います。

**Comment by pazeshun** [comment]
重心が高い物体は現在の方法でいいが、重心の低い物体だと直動関節が届かない
→別の方法が必要？

**Comment by wkentaro** [comment]
I think it is done. Please reopen if not.
Or maybe moved to https://github.com/start-jsk/jsk_apc/issues/2258?
