### ISSUE TITLE
Prepare for IK failure

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2366]
Pickingの最中にIKが失敗しても、その点をスキップする or Pickingを中止することで、タスクを続けられるようにする

**Comment by wkentaro** [comment]
Please do this tomorrow.

**Comment by pazeshun** [comment]
先ほど、IKが解けなくてmainが落ちる現象が発生しました。

状況
- pick taskのbin Bで、Baxterから遠い側の壁に接した物体を右手で取ろうとした
- suctionは壁沿い専用のものになったが、物体を外して失敗した
- suctionからpinchへ移行する際にIKが解けなかった

推測される失敗場所
- https://github.com/start-jsk/jsk_apc/blob/master/jsk_arc2017_baxter/euslisp/lib/arc-interface.l#L515

**Comment by pazeshun** [comment]
stowのplace-objectでもIKが解けないことがありました。

状況
- bin Cにplaceした時にIKが解けなかった

推測される失敗場所
- https://github.com/start-jsk/jsk_apc/blob/master/jsk_arc2017_baxter/euslisp/lib/stow-interface.l#L348

**Comment by wkentaro** [comment]
Maybe fixed.
