### ISSUE TITLE
:try-to-pick-objetで腕が真下に下りない時がある

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2379]
特に、tote/shelfのBaxterに近い側の壁付近で発生。
- IKで出てくる姿勢を確認
- 関節角補間だとどのような軌跡を描くのか確認
- end-coords-interpolationを使えるか確認

**Comment by wkentaro** [comment]
Please do this tomorrow.

**Comment by wkentaro** [comment]
Solved by @pazeshun .
