### ISSUE TITLE
Install grippers to baxter

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2502]
Now baxter is fixed. Please tackle this, soon.
Maybe left gripper is broken?

- [ ] Fix left gripper (maybe https://github.com/start-jsk/jsk_apc/issues/2256 and https://github.com/start-jsk/jsk_apc/issues/2209?)
- [x] Install grippers

**Comment by pazeshun** [comment]
I'll do this tomorrow.
Sorry for late.

**Comment by wkentaro** [comment]
Done.
