### ISSUE TITLE
Unknown objects' ItemData

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2505]
Need to ask Joey.

## Pick task

- Band-Aid_Strips: https://www.amazon.com/Band-Aid-Flexible-Fabric-Adhesive-Bandages/dp/B00006IDL6/ref=sr_1_2_a_it?ie=UTF8&qid=1501674456&sr=8-2&keywords=band%2Baid%2Bstrips&th=1
- Brillo_Pads: https://www.amazon.com/Brillo-Basics-Steel-Scrub-8-ct/dp/B01L65FY3U/ref=sr_1_1?ie=UTF8&qid=1501674079&sr=8-1&keywords=brillo+pads+basic
- Darth_Vader_Cup: http://www.ebay.com/itm/STAR-WARS-Classic-REUSABLE-KEEPSAKE-CUPS-2-Birthday-Party-Supplies-Favors-/282578760194?hash=item41cb01b202:g:ikQAAOSw4A5Yq7op
- Elastic_Wrap_Bandage: https://www.walmart.com/ip/Flex-Aid-3-Elastic-Wrap-Bandage-1-Roll/25875621

**Comment by otsubo** [comment]
- Elastic_Wrap_Bandage: https://www.walmart.com/ip/Flex-Aid-3-Elastic-Wrap-Bandage-1-Roll/25875621
- Darth_Vader_Cup: http://www.ebay.com/itm/STAR-WARS-Classic-REUSABLE-KEEPSAKE-CUPS-2-Birthday-Party-Supplies-Favors-/282578760194?hash=item41cb01b202:g:ikQAAOSw4A5Yq7op

**Comment by wkentaro** [comment]
The organizers of ARC won't respond.. I postpone this to 4.2.0.
