### ISSUE TITLE
ホースとケーブルの取回しの修正

### ISSUE THREAD

**Issue by pazeshun** [start-jsk/jsk_apc#2560]

**Comment by pazeshun** [comment]
右手のホースの修正
- Baxterの腕から下がった結束帯の輪にホースを括りつけている結束帯を切る
- 結束帯の輪からグリッパまでのホースの長さを、左手のホースと同じくらいの長さにする
- 結束帯でホースを再度括りつける

**Comment by wkentaro** [comment]
It seems that https://github.com/start-jsk/jsk_apc/pull/2563 solves this problem, so can I close this?

**Comment by pazeshun** [comment]
Please wait until I check today.

**Comment by pazeshun** [comment]
カメラの配線を修正しました。
