### ISSUE TITLE
Should we make Kinetic and Indigo branch?

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2634]
Move from #2633 

@pazeshun suggested and approved this idea.
@wkentaro @YutoUchimi  can you give us any idea?

**Comment by wkentaro** [comment]
If this is for the C++ code, I think we should just use a macro.

**Comment by pazeshun** [comment]
pros:
- Enable to deal with when a depending package becomes different from kinetic to indigo (like #2633 ) 

cons:
- Management is bothering (requiring two PRs etc...)

**Comment by knorth55** [comment]
#2633 solved with macro.
However, we should set our policy.
IMO, I prefer to maintain `master` branch for both `indigo` and `kinetic`.

**Comment by wkentaro** [comment]
Closed via https://github.com/start-jsk/jsk_apc/pull/2633
