### ISSUE TITLE
Automated Build For Docker

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#2691]
@pazeshun Currently, the docker image is not updated since we migrated it to jskrobotics group.
![image](https://user-images.githubusercontent.com/4310419/59697418-b0b98f80-91e5-11e9-8123-e7bdcaf7c857.png)

There are different ways to enable this:

- Link to GitHub (admin of start-jsk) and trigger the build with `git push`
- Add webhook from GitHub to DockerHub: https://docs.docker.com/docker-hub/builds/classic/

Anyway, I don't have both permissions to make this work, so please ask @k-okada .

**Comment by pazeshun** [comment]
Currently I and @k-okada are trying the first option
>     * Link to GitHub (admin of start-jsk) and trigger the build with `git push`
because without linking to GitHub, Dockerfile in this GitHub repository is not transferred to DockerHub repository.
Now we are waiting for build.

**Comment by pazeshun** [comment]
I'll check setting is correct when #2693 is merged.

**Comment by pazeshun** [comment]
>     * Add webhook from GitHub to DockerHub
I added webhook and use it in #2693

**Comment by pazeshun** [comment]
This is fixed by #2694
