### ISSUE TITLE
How to generate my synthetic2d dataset and train in instance-occlsegm demo

### ISSUE THREAD

**Issue by GeJunyan** [start-jsk/jsk_apc#2736]
1.  I cannot download ARC2017ItemDataSyntheticInstanceSegmentationDataset, the url seems down.
    _def download(cls):
        instance_occlsegm_lib.data.download(
            url='https://drive.google.com/uc?id=1OYoLwsRuHKP8is-7JIE2ii5f-VeICjv1',  # NOQA
            md5='5a64bb03613589e5aeab41d8319bb945',
            path=cls.item_data_dir + '.zip',
            postprocess=instance_occlsegm_lib.data.extractall,
        )_
2. Could you provide a tutorial or some corresponding reference for generating our own synthetic dataset with label?
Thanks.
@wkentaro

**Comment by GeJunyan** [comment]
@k-okada

**Comment by wkentaro** [comment]
1. The link seems still work for me. 
2. Here’s where the synthetic data is generated
https://github.com/start-jsk/jsk_apc/blob/2553b557d98c5f258bf4ca44da8c4bfb8b19fd64/demos/instance_occlsegm/instance_occlsegm_lib/datasets/apc/arc2017_v2/item_data_synthetic.py#L65
