### ISSUE TITLE
travis-ci.comへの移行

### ISSUE THREAD

**Issue by knorth55** [start-jsk/jsk_apc#2743]
@k-okada 
jsk_apcがtravis-ci.orgのbuildを通ることがPRをマージするときの条件として設定されているのですが，こちらをtravis-ci.comのbuildに変更していただけないでしょうか？よろしくお願いします．

**Comment by k-okada** [comment]
Done

![Screenshot from 2021-06-06 14-25-49](https://user-images.githubusercontent.com/493276/120913604-27057400-c6d3-11eb-8ad2-3f3eb432cd73.png)

**Comment by knorth55** [comment]
Thank you!!
