### ISSUE TITLE
トルクが足りなそう

### ISSUE THREAD

**Issue by iory** [start-jsk/jsk_apc#745]
@k-okada 
pick-objectの調整をしているのですが、棚の最上段でクレヨンなどの重いものを持たせて持ち上げようとするとz方向に頑張ってもあがらなくなります。
おそらくトルクが足りないのかと思います。

**Comment by k-okada** [comment]
https://github.com/start-jsk/2014-semi/pull/724

みたいに何回かやるとどうなりますか？

--
◉ Kei Okada


2015-05-23 15:43 GMT+09:00 ioryz <notifications@github.com>:

**Comment by iory** [comment]
これでやった結果、腕があがらないということになりました

**Comment by k-okada** [comment]
床に手が付いていると間違えるのかな？
そのまま引き出したらモノはでてくるかな
一番うえにあるクレヨンはend-cooedsはみなければいいのかな

--
◉ Kei Okada

2015/05/23 19:39、ioryz <notifications@github.com> のメッセージ:

**Comment by iory** [comment]
いやクレヨンがたてかけてあって掃除機は横から持ち上げてとろうとするという状況です。

**Comment by k-okada** [comment]
吸引力が十分ならとりだせるかな

2015年5月23日土曜日、ioryz<notifications@github.com>さんは書きました:

> いやクレヨンがたてかけてあって掃除機は横から持ち上げてとろうとするという状況です。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/745#issuecomment-104882231>
> .
>


-- 
--
◉ Kei Okada

**Comment by iory** [comment]
そうですね
一応クレヨンはなんとか取り出せました。
下の方の段だったら普通に上に上がって持ってこれるので、ちょっとした運要素となります

**Comment by aginika** [comment]
結論はなんですか？

**Comment by iory** [comment]
トルクが足りないので今更どうしようもないです

**Comment by iory** [comment]
これで対応できるかもしれないです。
https://github.com/euslisp/jskeus/issues/212

**Comment by wkentaro** [comment]
close for now.
