### ISSUE TITLE
テストプログラム用のbagファイルが欲しい

### ISSUE THREAD

**Issue by k-okada** [start-jsk/jsk_apc#811]
テストプログラムをつくりたいんだけど，
棚の全体が映ったPointCloudのバグファイル，
と，
それぞれの物体をもって確認している時のバグファイル

ないかな．

**Comment by wkentaro** [comment]
PointCloudのバグファイルはありません。
画像などの通しのバグファイルならいくつかあります。

On Thursday, June 11, 2015, Kei Okada <notifications@github.com> wrote:

> テストプログラムをつくりたいんだけど，
> 棚の全体が映ったPointCloudのバグファイル，
> と，
> それぞれの物体をもって確認している時のバグファイル
>
> ないかな．
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/811>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
バグファイルはどういったテストに使いますか？

On Thursday, June 11, 2015, Kentaro Wada <www.kentaro.wada@gmail.com> wrote:

> PointCloudのバグファイルはありません。
> 画像などの通しのバグファイルならいくつかあります。
>
> On Thursday, June 11, 2015, Kei Okada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> テストプログラムをつくりたいんだけど，
>> 棚の全体が映ったPointCloudのバグファイル，
>> と，
>> それぞれの物体をもって確認している時のバグファイル
>>
>> ないかな．
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/start-jsk/2014-semi/issues/811>.
>>
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com <http://www.wkentaro.com>
>
>
>

-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
画像処理のところで
ー セグメンテーション
ー 認識
出できればいいと思います．

--
◉ Kei Okada


2015-06-13 15:35 GMT+09:00 Kentaro Wada <notifications@github.com>:

> バグファイルはどういったテストに使いますか？
>
> On Thursday, June 11, 2015, Kentaro Wada <www.kentaro.wada@gmail.com>
> wrote:
>
> > PointCloudのバグファイルはありません。
> > 画像などの通しのバグファイルならいくつかあります。
> >
> > On Thursday, June 11, 2015, Kei Okada <notifications@github.com

**Comment by wkentaro** [comment]
PointCloudはbagをとっていなかったので、kinectの取付具等が届いてからやる必要があるかもしれないです。（テストはmove_for_verificationの位置も含めてですよね)
位置は関係ないテストであればkinectはあるので出来ますが、、

**Comment by wkentaro** [comment]
Kinect2のキャリブレーションが終了次第、これに取り組みます。 for https://github.com/jsk-ros-pkg/jsk_recognition/issues/1215#issuecomment-147679659

**Comment by wkentaro** [comment]
done at https://github.com/jsk-ros-pkg/jsk_recognition/issues/1215#issuecomment-154363477
