### ISSUE TITLE
Vacuum Gripperのrosserial, arduino不良

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/jsk_apc#885]
`connected but no data`と言われます.
@iory 後で一緒に見てもらってもいいですか？

**Comment by wkentaro** [comment]
起きた原因はまだ特定できていませんが、ノートPCにArduinoを接続したところ問題なくON/OFFできました。

考えられる原因としては、
* Sheeta（もともとつないでいた据え置きPC)のUSBの問題
* Sheetaのrosserial_arduinoとその依存パッケージのバージョン

**Comment by wkentaro** [comment]
USBの問題ではないかと考えdouraへつないで利用するようにしました。

**Comment by wkentaro** [comment]
依存パッケージのバージョンに関して

動かない環境
```
genmsg: 0.5.6              
genpy: 0.5.5               
cpp_common: 0.5.6          
rostime: 0.5.6             
roscpp_traits: 0.5.6       
roscpp_serialization: 0.5.6
message_runtime: 0.4.12    
catkin: 0.6.15             
gencpp: 0.5.3              
genlisp: 0.4.15            
message_generation: 0.2.10 
rosbuild: 1.11.9           
rosconsole: 1.11.14        
std_msgs: 0.5.9            
rosgraph_msgs: 1.11.1      
xmlrpcpp: 1.11.14          
roscpp: 1.11.14            
rosgraph: 1.11.14          
rospack: 2.2.5             
roslib: 1.11.9             
rospy: 1.11.14             
rosserial_msgs: 0.6.4      
diagnostic_msgs: 1.11.8    
```

動く環境
```genmsg: 0.5.6
genpy: 0.5.4
cpp_common: 0.5.6
rostime: 0.5.6
roscpp_traits: 0.5.6
roscpp_serialization: 0.5.6
message_runtime: 0.4.12
catkin: 0.6.14
gencpp: 0.5.3
genlisp: 0.4.15
message_generation: 0.2.10
rosbuild: 1.11.8
rosconsole: 1.11.13
std_msgs: 0.5.9
rosgraph_msgs: 1.11.1
xmlrpcpp: 1.11.13
roscpp: 1.11.13
rosgraph: 1.11.13
rospack: 2.2.5
roslib: 1.11.8
rospy: 1.11.13
rosserial_msgs: 0.6.3
diagnostic_msgs: 1.11.8
```

**Comment by k-okada** [comment]
rosserial のバージョン？

--
◉ Kei Okada

**Comment by wkentaro** [comment]
rosserialのバージョンはどちらも0.6.4なので、ソフトウェアが原因だとすると、依存パッケージだと考えました。

2015年10月8日木曜日、Kei Okada<notifications@github.com>さんは書きました:

> rosserial のバージョン？
>
> --
> ◉ Kei Okada
>
>
> On Wed, Oct 7, 2015 at 10:41 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > 依存パッケージのバージョンに関して
> >
> > 動かない環境
> >
> > genmsg: 0.5.6
> > genpy: 0.5.5
> > cpp_common: 0.5.6
> > rostime: 0.5.6
> > roscpp_traits: 0.5.6
> > roscpp_serialization: 0.5.6
> > message_runtime: 0.4.12
> > catkin: 0.6.15
> > gencpp: 0.5.3
> > genlisp: 0.4.15
> > message_generation: 0.2.10
> > rosbuild: 1.11.9
> > rosconsole: 1.11.14
> > std_msgs: 0.5.9
> > rosgraph_msgs: 1.11.1
> > xmlrpcpp: 1.11.14
> > roscpp: 1.11.14
> > rosgraph: 1.11.14
> > rospack: 2.2.5
> > roslib: 1.11.9
> > rospy: 1.11.14
> > rosserial_msgs: 0.6.4
> > diagnostic_msgs: 1.11.8
> >
> > 動く環境
> > ```genmsg: 0.5.6
> > genpy: 0.5.4
> > cpp_common: 0.5.6
> > rostime: 0.5.6
> > roscpp_traits: 0.5.6
> > roscpp_serialization: 0.5.6
> > message_runtime: 0.4.12
> > catkin: 0.6.14
> > gencpp: 0.5.3
> > genlisp: 0.4.15
> > message_generation: 0.2.10
> > rosbuild: 1.11.8
> > rosconsole: 1.11.13
> > std_msgs: 0.5.9
> > rosgraph_msgs: 1.11.1
> > xmlrpcpp: 1.11.13
> > roscpp: 1.11.13
> > rosgraph: 1.11.13
> > rospack: 2.2.5
> > roslib: 1.11.8
> > rospy: 1.11.13
> > rosserial_msgs: 0.6.3
> > diagnostic_msgs: 1.11.8
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/start-jsk/jsk_apc/issues/885#issuecomment-146199317
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/jsk_apc/issues/885#issuecomment-146448614>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
rosserialのバージョンというのはrosserial_pythonのことです。

2015年10月8日木曜日、Kentaro Wada<www.kentaro.wada@gmail.com>さんは書きました:

> rosserialのバージョンはどちらも0.6.4なので、ソフトウェアが原因だとすると、依存パッケージだと考えました。
>
> 2015年10月8日木曜日、Kei Okada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
>> rosserial のバージョン？
>>
>> --
>> ◉ Kei Okada
>>
>>
>> On Wed, Oct 7, 2015 at 10:41 PM, Kentaro Wada <notifications@github.com>
>> wrote:
>>
>> > 依存パッケージのバージョンに関して
>> >
>> > 動かない環境
>> >
>> > genmsg: 0.5.6
>> > genpy: 0.5.5
>> > cpp_common: 0.5.6
>> > rostime: 0.5.6
>> > roscpp_traits: 0.5.6
>> > roscpp_serialization: 0.5.6
>> > message_runtime: 0.4.12
>> > catkin: 0.6.15
>> > gencpp: 0.5.3
>> > genlisp: 0.4.15
>> > message_generation: 0.2.10
>> > rosbuild: 1.11.9
>> > rosconsole: 1.11.14
>> > std_msgs: 0.5.9
>> > rosgraph_msgs: 1.11.1
>> > xmlrpcpp: 1.11.14
>> > roscpp: 1.11.14
>> > rosgraph: 1.11.14
>> > rospack: 2.2.5
>> > roslib: 1.11.9
>> > rospy: 1.11.14
>> > rosserial_msgs: 0.6.4
>> > diagnostic_msgs: 1.11.8
>> >
>> > 動く環境
>> > ```genmsg: 0.5.6
>> > genpy: 0.5.4
>> > cpp_common: 0.5.6
>> > rostime: 0.5.6
>> > roscpp_traits: 0.5.6
>> > roscpp_serialization: 0.5.6
>> > message_runtime: 0.4.12
>> > catkin: 0.6.14
>> > gencpp: 0.5.3
>> > genlisp: 0.4.15
>> > message_generation: 0.2.10
>> > rosbuild: 1.11.8
>> > rosconsole: 1.11.13
>> > std_msgs: 0.5.9
>> > rosgraph_msgs: 1.11.1
>> > xmlrpcpp: 1.11.13
>> > roscpp: 1.11.13
>> > rosgraph: 1.11.13
>> > rospack: 2.2.5
>> > roslib: 1.11.8
>> > rospy: 1.11.13
>> > rosserial_msgs: 0.6.3
>> > diagnostic_msgs: 1.11.8
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/start-jsk/jsk_apc/issues/885#issuecomment-146199317
>> >.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/start-jsk/jsk_apc/issues/885#issuecomment-146448614>.
>>
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com
>
>

-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by k-okada** [comment]
rosserial_msgs が違うからマイコンから送る方もコンパイルしなおしでしょうか．

--
◉ Kei Okada


2015-10-08 17:11 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
ソフトウェアのバージョンは関係なかったようです。
ノートPCでは同じバージョンでできました。
```
% for i in $(rospack depends rosserial_python); do echo "$i: `rosversion $i`"; done
genmsg: 0.5.6
genpy: 0.5.5
cpp_common: 0.5.6
rostime: 0.5.6
roscpp_traits: 0.5.6
roscpp_serialization: 0.5.6
message_runtime: 0.4.12
catkin: 0.6.15
gencpp: 0.5.3
genlisp: 0.4.15
message_generation: 0.2.10
rosbuild: 1.11.9
rosconsole: 1.11.14
std_msgs: 0.5.9
rosgraph_msgs: 1.11.1
xmlrpcpp: 1.11.14
roscpp: 1.11.14
rosgraph: 1.11.14
rospack: 2.2.5
roslib: 1.11.9
rospy: 1.11.14
rosserial_msgs: 0.6.4
diagnostic_msgs: 1.11.8
```

**Comment by wkentaro** [comment]
これは、sheetaとすべて同じバージョンです。

**Comment by wkentaro** [comment]
しばらく使っているとエラーが出るようになったため、別のPCにつないでいます。

**Comment by k-okada** [comment]
キチンと原因を究明して治したいところ．

--
◉ Kei Okada

**Comment by wkentaro** [comment]
はい、そうですね。

**Comment by wkentaro** [comment]
baxter@doura
```
genmsg 0.5.6
genpy 0.5.4
cpp_common 0.5.6
rostime 0.5.6
roscpp_traits 0.5.6
roscpp_serialization 0.5.6
message_runtime 0.4.12
catkin 0.6.14
gencpp 0.5.3
genlisp 0.4.15
message_generation 0.2.10
rosbuild 1.11.8
rosconsole 1.11.13
std_msgs 0.5.9
rosgraph_msgs 1.11.1
xmlrpcpp 1.11.13
roscpp 1.11.13
rosgraph 1.11.13
rospack 2.2.5
roslib 1.11.8
rospy 1.11.13
rosserial_msgs 0.6.4
diagnostic_msgs 1.11.8
```

**Comment by wkentaro** [comment]
wkentaro@cobra
```
```

**Comment by wkentaro** [comment]
```
genmsg 0.5.6
genpy 0.5.5
cpp_common 0.5.6
rostime 0.5.6
roscpp_traits 0.5.6
roscpp_serialization 0.5.6
message_runtime 0.4.12
catkin 0.6.15
gencpp 0.5.3
genlisp 0.4.15
message_generation 0.2.10
rosbuild 1.11.9
rosconsole 1.11.14
std_msgs 0.5.9
rosgraph_msgs 1.11.1
xmlrpcpp 1.11.14
roscpp 1.11.14
rosgraph 1.11.14
rospack 2.2.5
roslib 1.11.9
rospy 1.11.14
rosserial_msgs 0.6.4
diagnostic_msgs 1.11.8
```

**Comment by wkentaro** [comment]
エラーメッセージ
```
% rosrun rosserial_python serial_node.py _port:=/dev/ttyUSB0 _baud:=115200
[INFO] [WallTime: 1444743760.324098] ROS Serial Python Node
[INFO] [WallTime: 1444743760.331972] Connecting to /dev/ttyUSB0 at 115200 baud
[WARN] [WallTime: 1444743762.445800] Serial Port read failure: device reports readiness to read but returned no data (device disconnected?)
[INFO] [WallTime: 1444743762.446595] Packet Failed :  Failed to read msg data
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/rosserial_python/serial_node.py", line 82, in <module>
    client.run()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 475, in run
    rospy.loginfo("msg len is %d",len(msg))
UnboundLocalError: local variable 'msg' referenced before assignment
```

**Comment by wkentaro** [comment]
This was caused by bug in kernel.
