### ISSUE TITLE
Possibility of making a common apc_common package?

### ISSUE THREAD

**Issue by rethink-imcmahon** [start-jsk/jsk_apc#957]
At JSK, you have done wonderful work putting together Gazebo models for the Picking Challenge. Would you be open to the idea of creating an independent apc_common package with all of the models (stripped of any JSK competition scripts / launch files)? I'd be happy to help in putting this together.

**Comment by wkentaro** [comment]
That would be fine, but I wonder I should name the package as apc2015_common,
because it is highly possible the object list in the competition is changed in the future.
(If the object name is unique, we can use apc_common as the package name)

@k-okada any idea?

**Comment by k-okada** [comment]
I'd be comfortable if you can create
https://github.com/amazon-picking-challenge/apc_common (this means you'll
have almost same setup for apc 2016, if you plan to have completely
different setup, apc2015_common would be better) ,  put some of our codes
into that package, and transfer ownership/maintainer to APC team.

you can also take look at rviz plugins for showing scores and robot's
intentions (
https://github.com/start-jsk/jsk_apc/blob/cd7aa869c410b93046889368b4bb4b858fc60a1a/jsk_2015_05_baxter_apc/config/challenge.rviz
)
https://github.com/start-jsk/jsk_apc/pull/622 for score board
? showing which object the robot is trying to pick

they are published from this (
https://github.com/start-jsk/jsk_apc/blob/c475126ea9b38c6066b12d2d82e11c517cb79e83/archives/robot-visualization.l
;)

do you have screenshot of our apc information on rviz ? @wkentaro


--
◉ Kei Okada

**Comment by wkentaro** [comment]
@k-okada 
> do you have screenshot of our apc information on rviz ? @wkentaro

![image](https://cloud.githubusercontent.com/assets/4310419/10927826/632d5330-82e6-11e5-81b5-d53d19a550df.png)

I don't think the score board is very important, and it is not easy to use with existing program,
because it is not a rviz plugin but marker published by roseus.
I think it should be a rviz plugin to which we can add points with service call if we put it to apc_common package.

I think the only code which can be commonly used by every team is the python package in jsk_2015_apc_common.
https://github.com/start-jsk/jsk_apc/blob/master/jsk_2015_apc_common/src/jsk_2015_apc_common/data.py#L9

**Comment by k-okada** [comment]
scoerboard is just for fun,but important thing is

> ? showing which object the robot is trying to pick

more precisely  audience would  like to know
1) what is requierd job, need to know list of the item to be picked
2) what is the robot is going to pick
optional) how robot think about the motion (did he recognize the object?
what object is going to be piced etc)

and what we need is text plugin (
https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/jsk_rviz_plugins/src/overlay_text_display.cpp
, https://github.com/jsk-ros-pkg/jsk_visualization/pull/29) and common json
reader server

--
◉ Kei Okada

**Comment by wkentaro** [comment]
> more precisely  audience would  like to know
1) what is requierd job, need to know list of the item to be picked
2) what is the robot is going to pick
optional) how robot think about the motion (did he recognize the object?
what object is going to be piced etc)

@k-okada I agree with you that these things are important in the competition.
To do this, `jsk_rviz_plugins` is released on deb so what we need is to create the rviz config template and a sample of displaying robot intention, and create server to read and visualize json?

**Comment by wkentaro** [comment]
Closed via https://github.com/amazon-picking-challenge/apc_common/pull/1
